force-app/main/default/objects/Acao_historico_OS__c/Acao_historico_OS__c.object-meta.xml
<CustomObject>
    <label>Ação do histórico da OS</label>
    <nameField>
        <label>Nome da Categorização da OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ações do histórico da OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Acao_historico_OS__c/fields/Categoria_contato__c.field-meta.xml
<CustomField>
    <fullName>Categoria_contato__c</fullName>
    <label>Categoria do contato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrativo</fullName>
            </value>
            <value>
                <fullName>Efetivo</fullName>
            </value>
            <value>
                <fullName>Não efetivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Acao_historico_OS__c/fields/Codigo_externo__c.field-meta.xml
<CustomField>
    <fullName>Codigo_externo__c</fullName>
    <externalId>true</externalId>
    <label>Código externo</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Acao_historico_OS__c/fields/Data_cadastro__c.field-meta.xml
<CustomField>
    <fullName>Data_cadastro__c</fullName>
    <label>Data de cadastro</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/Teste_Exportar_Acao_Historico_OS.cls
@isTest
public class Teste_Exportar_Acao_Historico_OS {

    // Método para teste da classe
    static testmethod void teste() {

        Acao_historico_OS__c acao = new Acao_historico_OS__c();
        acao.Name = 'teste';
        acao.Categoria_contato__c = 'Efetivo';
		acao.Data_cadastro__c = System.now();
		acao.Ativo__c = true;
        acao.Codigo_externo__c = '1';
        insert acao;

        Test.startTest();

        new Exportar_Acao_Historico_OS();

        Test.stopTest();

    } // Fim teste

}