force-app/main/default/objects/Acao_historico_OS__c/Acao_historico_OS__c.object-meta.xml
<CustomObject>
    <label>Ação do histórico da OS</label>
    <nameField>
        <label>Nome da Categorização da OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ações do histórico da OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Acao_historico_OS__c/fields/Categoria_contato__c.field-meta.xml
<CustomField>
    <fullName>Categoria_contato__c</fullName>
    <label>Categoria do contato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrativo</fullName>
            </value>
            <value>
                <fullName>Efetivo</fullName>
            </value>
            <value>
                <fullName>Não efetivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Acao_historico_OS__c/fields/Codigo_externo__c.field-meta.xml
<CustomField>
    <fullName>Codigo_externo__c</fullName>
    <externalId>true</externalId>
    <label>Código externo</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Acao_historico_OS__c/fields/Pais_referencia__c.field-meta.xml
<CustomField>
    <fullName>Pais_referencia__c</fullName>
    <description>ISO Alpha-3 do país que será usado o registro</description>
    <label>País de Referência</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_OS__c/Historico_OS__c.object-meta.xml
<CustomObject>
    <label>Histórico da OS</label>
    <nameField>
        <displayFormat>HO-{000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Históricos da OS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Historico_OS__c/fields/Categoria_contato__c.field-meta.xml
<CustomField>
    <fullName>Categoria_contato__c</fullName>
    <formula>TEXT( Status__r.Categoria_contato__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Categoria do contato</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_OS__c/fields/Codigo_externo__c.field-meta.xml
<CustomField>
    <fullName>Codigo_externo__c</fullName>
    <description>Código externo para identificar o registro</description>
    <externalId>true</externalId>
    <label>Código externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Historico_OS__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Historico_OS__c/fields/Data_agenda__c.field-meta.xml
<CustomField>
    <fullName>Data_agenda__c</fullName>
    <label>Data agenda</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Historico_OS__c/fields/Observacao__c.field-meta.xml
<CustomField>
    <fullName>Observacao__c</fullName>
    <label>Observação</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Historico_OS__c/fields/Ordem_servico__c.field-meta.xml
<CustomField>
    <fullName>Ordem_servico__c</fullName>
    <label>Ordem de serviço</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Históricos da OS</relationshipLabel>
    <relationshipName>Historicos_OS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Historico_OS__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Ação do histórico da OS</description>
    <label>Status</label>
    <referenceTo>Acao_historico_OS__c</referenceTo>
    <relationshipLabel>Históricos da OS</relationshipLabel>
    <relationshipName>Historicos_OS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Teste_Util_Historico_OS.cls
/*
    Classe de testes para cadastro do objeto Historico da OS
    Criado por: Mario Reis
    Data: 27/06/2018
*/
@isTest
public class Teste_Util_Historico_OS {


    //Método para criar HistoricoEfetivo
    public static Historico_OS__c criarHistoricoEfetivo(String idOS){

        Acao_historico_OS__c acao = new Acao_historico_OS__c();
        acao.Name = 'Ordem de serviço cancelada';
        acao.Categoria_contato__c = 'Não efetivo';
        acao.Codigo_externo__c = '123456';
        acao.Pais_referencia__c = 'BRA';
        insert acao;

       	Historico_OS__c ho = new Historico_OS__c();
        ho.Codigo_externo__c = '1';
        ho.Data_agenda__c = System.now();
        ho.Data__c = System.now();
        ho.Observacao__c = 'Observação';
        ho.Ordem_servico__c = idOS;
        ho.Status__c = acao.Id;
        insert ho;
        return ho;

    }// Fim criarHistoricoEfetivo


    //Método para criar HistoricoEfetivo
    public static Historico_OS__c criarHistoricoSemAcao(String idOS){

       	Historico_OS__c ho = new Historico_OS__c();
        ho.Codigo_externo__c = '1';
        ho.Data_agenda__c = System.now();
        ho.Observacao__c = 'Ordem de serviço cancelada';
        ho.Ordem_servico__c = idOS;
        insert ho;
        return ho;

    }// Fim criarHistoricoEfetivo

}