force-app/main/default/objects/Tipo_OS__c/Tipo_OS__c.object-meta.xml
<CustomObject>
    <description>Registra os tipos de OS disponíveis para uso</description>
    <label>Tipo de OS</label>
    <nameField>
        <label>Nome do Tipo de OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_OS__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se um registro está ativo ou não</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Teste_DAO_Tipo_OS.cls
/*
	@testClass DAO_Tipo_OS
	
	@author Renan Rocha
	@date 07/01/2019
*/

@isTest
public class Teste_DAO_Tipo_OS{
	
	/*
		@author Renan Rocha
		@date 08/01/2019
	*/
	static testMethod void getListaTipoOS(){
		Map<String, sObject> mapBase = Teste_Util.createMapBase();
		Tipo_OS__c tipoOS = (Tipo_OS__c) mapBase.get('Tipo_OS__c');
		tipoOS.Ativo__c = true;
		update tipoOS;

		System.assertEquals(1, DAO_Tipo_OS.getListaTipoOS().size());
	}
}