force-app/main/default/objects/Tipo_OS__c/Tipo_OS__c.object-meta.xml
<CustomObject>
    <description>Registra os tipos de OS disponíveis para uso</description>
    <label>Tipo de OS</label>
    <nameField>
        <label>Nome do Tipo de OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_OS__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se um registro está ativo ou não</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tipo_OS__c/fields/Codigo_Externo__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Externo__c</fullName>
    <description>ID do tipo de OS do ERP</description>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DAO_Tipo_OS.cls
/*
	@testClass Teste_DAO_Tipo_OS
	
	@description Classe para o Objeto: Tipo_OS__c
	
	@author Renan Rocha
	@date 07/01/2019
	@JIRA KCA-59
*/

public class DAO_Tipo_OS{
	private static String CLASS_NAME = 'DAO_Tipo_OS';
	
	// Método que retorna todos os Tipos de OS Ativos
    public static List<Tipo_OS__c> getListaTipoOS(){
        String METHOD_NAME = 'getListaTipoOS';

        return
            [SELECT Id
                  , Ativo__c
                  , Name
            FROM Tipo_OS__c 
            WHERE Ativo__c = true 
            AND Pais_referencia__c = 'BRA'
            AND Codigo_externo__c <> '3'
            ORDER BY Name];
    } // Fim método getListaTipoOS
}