force-app/main/default/objects/Tipo_OS__c/Tipo_OS__c.object-meta.xml
<CustomObject>
    <description>Registra os tipos de OS disponíveis para uso</description>
    <label>Tipo de OS</label>
    <nameField>
        <label>Nome do Tipo de OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_OS__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se um registro está ativo ou não</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tipo_OS__c/fields/Codigo_Externo__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Externo__c</fullName>
    <description>ID do tipo de OS do ERP</description>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Teste_Util_Tipo_OS.cls
/*
    Classe de testes para cadastro do objeto Tipo OS
    Criado por: Mario Reis
    Data: 12/06/2018
*/
@isTest
public class Teste_Util_Tipo_OS {


    //Método para criar Tipo de OS Autorizado
    public static Tipo_OS__c criarTipoOSAutorizado(){

        Tipo_OS__c tipoOS = new Tipo_OS__c();
        tipoOS.Name = 'INSTALAÇÃO';
        tipoOS.Codigo_Externo__c = '1';
        tipoOS.Ativo__c = true;
        tipoOS.Pais_Referencia__c = 'BRA';

        insert tipoOS;
        return tipoOS;
    }// Fim criarTipoOSAutorizado

}