force-app/main/default/objects/Case/fields/CNPJ_CPF__c.field-meta.xml
<CustomField>
    <fullName>CNPJ_CPF__c</fullName>
    <label>CNPJ/CPF</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NivelEscalacao__c.field-meta.xml
<CustomField>
    <fullName>NivelEscalacao__c</fullName>
    <label>Nível de escalação</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N1</fullName>
                <default>true</default>
                <label>N1</label>
            </value>
            <value>
                <fullName>N2</fullName>
            </value>
            <value>
                <fullName>N3</fullName>
            </value>
            <value>
                <fullName>N4</fullName>
            </value>
            <value>
                <fullName>N5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/StatusResposta__c.field-meta.xml
<CustomField>
    <fullName>StatusResposta__c</fullName>
    <label>Status da resposta</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Não iniciada</fullName>
            </value>
            <value>
                <fullName>Em andamento</fullName>
            </value>
            <value>
                <fullName>Atrasada</fullName>
            </value>
            <value>
                <fullName>Em andamento aguardando cliente</fullName>
            </value>
            <value>
                <fullName>Atrasado aguardando cliente</fullName>
            </value>
            <value>
                <fullName>Concluída</fullName>
            </value>
            <value>
                <fullName>Concluída com atraso</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/StatusSolucao__c.field-meta.xml
<CustomField>
    <fullName>StatusSolucao__c</fullName>
    <label>Status da solução</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Não iniciada</fullName>
            </value>
            <value>
                <fullName>Atrasada</fullName>
            </value>
            <value>
                <fullName>Em andamento</fullName>
            </value>
            <value>
                <fullName>Em andamento aguardando cliente</fullName>
            </value>
            <value>
                <fullName>Atrasado aguardando cliente</fullName>
            </value>
            <value>
                <fullName>Concluída</fullName>
            </value>
            <value>
                <fullName>Concluída com atraso</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/TelefoneCliente__c.field-meta.xml
<CustomField>
    <fullName>TelefoneCliente__c</fullName>
    <label>Telefone do cliente</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/CaseBuild.cls
@isTest
public class CaseBuild {
    
    public static Case newCase(Id recordTypeId){
        Case caso = new Case(
            Subject = 'Reclamação',
            Status = 'Não iniciado',
            Origin = 'E-mail',
            StatusResposta__c = 'Não iniciada',
            StatusSolucao__c = 'Não iniciada',
            TelefoneCliente__c = '1144445555',
            CNPJ_CPF__c = '83813009084',
            NivelEscalacao__c = 'N1'
        );   
        return caso;
    }

}