force-app/main/default/objects/Case/fields/StatusResposta__c.field-meta.xml
<CustomField>
    <fullName>StatusResposta__c</fullName>
    <label>Status da resposta</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Não iniciada</fullName>
            </value>
            <value>
                <fullName>Em andamento</fullName>
            </value>
            <value>
                <fullName>Atrasada</fullName>
            </value>
            <value>
                <fullName>Em andamento aguardando cliente</fullName>
            </value>
            <value>
                <fullName>Atrasado aguardando cliente</fullName>
            </value>
            <value>
                <fullName>Concluída</fullName>
            </value>
            <value>
                <fullName>Concluída com atraso</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/StatusSolucao__c.field-meta.xml
<CustomField>
    <fullName>StatusSolucao__c</fullName>
    <label>Status da solução</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Não iniciada</fullName>
            </value>
            <value>
                <fullName>Atrasada</fullName>
            </value>
            <value>
                <fullName>Em andamento</fullName>
            </value>
            <value>
                <fullName>Em andamento aguardando cliente</fullName>
            </value>
            <value>
                <fullName>Atrasado aguardando cliente</fullName>
            </value>
            <value>
                <fullName>Concluída</fullName>
            </value>
            <value>
                <fullName>Concluída com atraso</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateStatusCase.cls
Global class UpdateStatusCase {
    
    WebService static String updateStatusResponse(Id caseId) {  
        
        Case caso = [SELECT Id, StatusResposta__c FROM Case WHERE Id =: caseId LIMIT 1];
        
        if(caso.StatusResposta__c == 'Não iniciada' || caso.StatusResposta__c == 'Em andamento'){
            caso.StatusResposta__c = 'Em andamento aguardando cliente';
            Update caso;
        }
        
        if(caso.StatusResposta__c == 'Atrasada'){
            caso.StatusResposta__c = 'Atrasado aguardando cliente';
            Update caso;
        }
        
        if(caso.StatusResposta__c != 'Em andamento aguardando cliente' && caso.StatusResposta__c != 'Em andamento aguardando cliente' &&
          caso.StatusResposta__c != 'Atrasado aguardando cliente'){
            return 'Esta resposta está ' + caso.StatusResposta__c + '.';
        } 
        
        return 'Sucesso!';
    }
    
    WebService static String updateStatusSolution(Id caseId) {  
        
        Case caso = [SELECT Id, StatusSolucao__c FROM Case WHERE Id =: caseId LIMIT 1];
        
        if(caso.StatusSolucao__c == 'Não iniciada' || caso.StatusSolucao__c == 'Em andamento'){
            caso.StatusSolucao__c = 'Em andamento aguardando cliente';
            Update caso;
        }
        
        if(caso.StatusSolucao__c == 'Atrasada'){
            caso.StatusSolucao__c = 'Atrasado aguardando cliente';
            Update caso;
        }
        
        if(caso.StatusSolucao__c != 'Em andamento aguardando cliente' && caso.StatusSolucao__c != 'Em andamento aguardando cliente' &&
          caso.StatusSolucao__c != 'Atrasado aguardando cliente'){
            return 'Esta solução está ' + caso.StatusSolucao__c + '.';
        } 
        
        return 'Sucesso!';
    }
    
}