force-app/main/default/objects/Atendente_Direcionamento_OS__c/Atendente_Direcionamento_OS__c.object-meta.xml
<CustomObject>
    <label>Atendente Direcionamento OS</label>
    <nameField>
        <displayFormat>ADOS-{000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Atendentes Direcionamento OS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Atendente_Direcionamento_OS__c/fields/Direcionamento_OS__c.field-meta.xml
<CustomField>
    <fullName>Direcionamento_OS__c</fullName>
    <label>Direcionamento de OS</label>
    <referenceTo>Direcionamento_os__c</referenceTo>
    <relationshipLabel>Atendentes Direcionamento OS</relationshipLabel>
    <relationshipName>Atendentes_Direcionamento_OS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/Direcionamento_os__c.object-meta.xml
<CustomObject>
    <label>Direcionamento de OS</label>
    <nameField>
        <label>Descrição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Direcionamentos de OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Direcionamento_os__c/fields/Agendamento_proximo_contato__c.field-meta.xml
<CustomField>
    <fullName>Agendamento_proximo_contato__c</fullName>
    <label>Agendamento próximo contato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Aging_final__c.field-meta.xml
<CustomField>
    <fullName>Aging_final__c</fullName>
    <description>Quantidade de dias do Aging final</description>
    <label>Aging final</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Aging_inicial__c.field-meta.xml
<CustomField>
    <fullName>Aging_inicial__c</fullName>
    <description>Quantidade de dias do Aging inicial</description>
    <label>Aging inicial</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Classe__c.field-meta.xml
<CustomField>
    <fullName>Classe__c</fullName>
    <label>Classe</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACESSÓRIOS CARRETA</fullName>
            </value>
            <value>
                <fullName>BT AEROPORTOS</fullName>
            </value>
            <value>
                <fullName>BT CONSTRUCAO CIVIL</fullName>
            </value>
            <value>
                <fullName>BT Industria - Avançado</fullName>
            </value>
            <value>
                <fullName>BT Industria - Basico</fullName>
            </value>
            <value>
                <fullName>BT Industria - Rental</fullName>
            </value>
            <value>
                <fullName>BT MINA JORNADA</fullName>
            </value>
            <value>
                <fullName>BT MINA PRODUTIVIDADE</fullName>
            </value>
            <value>
                <fullName>BT MINA SEGURANÇA</fullName>
            </value>
            <value>
                <fullName>BT MINERACAO GSM</fullName>
            </value>
            <value>
                <fullName>BT PORTO AVANÇADO</fullName>
            </value>
            <value>
                <fullName>BT PORTO BASICO</fullName>
            </value>
            <value>
                <fullName>CARRETA LOG</fullName>
            </value>
            <value>
                <fullName>CARRETA SOLAR</fullName>
            </value>
            <value>
                <fullName>CCO - GESTÃO AVANÇADA</fullName>
            </value>
            <value>
                <fullName>CCO - GESTÃO AVANÇADA IDENTIFICAÇÃO CAVALO</fullName>
            </value>
            <value>
                <fullName>CCO - GESTAO AVANÇADA (POSICIONAMENTO FREQUENTE)</fullName>
            </value>
            <value>
                <fullName>CCO - GESTÃO AVANÇADA REPETIDORA</fullName>
            </value>
            <value>
                <fullName>CCO - GESTÃO DA PRODUTIVIDADE</fullName>
            </value>
            <value>
                <fullName>CCO - GESTAO DA PRODUTIVIDADE (POSICIONAMENTO FREQUENTE)</fullName>
            </value>
            <value>
                <fullName>CCO - MONITORAMENTO LOGÍSTICO</fullName>
            </value>
            <value>
                <fullName>CCO - MONITORAMENTO LOGÍSTICO (POSICIONAMENTO FREQUENTE)</fullName>
            </value>
            <value>
                <fullName>CELULAR/GSM</fullName>
            </value>
            <value>
                <fullName>EUROPA CARRETA CONECTADA - FRIDGE</fullName>
            </value>
            <value>
                <fullName>EUROPA CARRETA CONECTADA - GEOLOC AND USAGE</fullName>
            </value>
            <value>
                <fullName>EUROPA CARRETA CONECTADA - MAINTENANCE AND SAFETY</fullName>
            </value>
            <value>
                <fullName>EXCLUSIVE LIGHT</fullName>
            </value>
            <value>
                <fullName>FAMILIA GSM</fullName>
            </value>
            <value>
                <fullName>FAMILIA SASMOTO</fullName>
            </value>
            <value>
                <fullName>GESTÃO DE FROTAS - INDONÉSIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <description>Nome do cliente</description>
    <inlineHelpText>Nome do cliente</inlineHelpText>
    <label>Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Cliente_KA__c.field-meta.xml
<CustomField>
    <fullName>Cliente_KA__c</fullName>
    <label>Cliente KA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
            <value>
                <fullName>Todos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Contato_fora_faixa__c.field-meta.xml
<CustomField>
    <fullName>Contato_fora_faixa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contato fora da faixa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Data_agendamento_final__c.field-meta.xml
<CustomField>
    <fullName>Data_agendamento_final__c</fullName>
    <label>Data de agendamento final</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Data_agendamento_inicial__c.field-meta.xml
<CustomField>
    <fullName>Data_agendamento_inicial__c</fullName>
    <label>Data de agendamento inicial</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Acessório</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Equipamento</label>
            </value>
            <value>
                <fullName>K</fullName>
                <label>Kit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Motivo__c.field-meta.xml
<CustomField>
    <fullName>Motivo__c</fullName>
    <description>ID&#39;s de Tipo do Item da OS</description>
    <label>Motivo</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Motivo_noshow__c.field-meta.xml
<CustomField>
    <fullName>Motivo_noshow__c</fullName>
    <label>Motivo de noshow</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NOSHOW_CLIENTE</fullName>
            </value>
            <value>
                <fullName>ERRO_AGENDAMENTO</fullName>
            </value>
            <value>
                <fullName>NOSHOW_TECNICO</fullName>
            </value>
            <value>
                <fullName>FALTA_EQUIPAMENTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Numero_OS__c.field-meta.xml
<CustomField>
    <fullName>Numero_OS__c</fullName>
    <description>Número da OS</description>
    <label>Número da OS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/OS_com_agendamento__c.field-meta.xml
<CustomField>
    <fullName>OS_com_agendamento__c</fullName>
    <defaultValue>false</defaultValue>
    <description>OS com agendamento válido</description>
    <label>OS com agendamento</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/OS_sem_agendamento__c.field-meta.xml
<CustomField>
    <fullName>OS_sem_agendamento__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OS sem agendamento</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/OS_sem_agendamento_aging_85_dias__c.field-meta.xml
<CustomField>
    <fullName>OS_sem_agendamento_aging_85_dias__c</fullName>
    <defaultValue>false</defaultValue>
    <description>OS sem agendamento com Aging de 85 dias</description>
    <label>OS sem agendamento Aging 85 dias</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/OS_sem_direcionamento__c.field-meta.xml
<CustomField>
    <fullName>OS_sem_direcionamento__c</fullName>
    <defaultValue>false</defaultValue>
    <description>OS não direcionada para nenhum atendente</description>
    <label>OS sem direcionamento</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/OS_sem_servico__c.field-meta.xml
<CustomField>
    <fullName>OS_sem_servico__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OS sem serviço</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Quantidade_OS__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_OS__c</fullName>
    <label>Quantidade de OS</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Regiao_comercial__c.field-meta.xml
<CustomField>
    <fullName>Regiao_comercial__c</fullName>
    <label>Região Comercial</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regiao_comercial</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Status_OS__c.field-meta.xml
<CustomField>
    <fullName>Status_OS__c</fullName>
    <description>ID&#39;s dos Status da OS</description>
    <label>Status da OS</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Tipo_contrato__c.field-meta.xml
<CustomField>
    <fullName>Tipo_contrato__c</fullName>
    <description>ID&#39;s dos tipos de contrato</description>
    <label>Tipo de contrato</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Tipo_OS__c.field-meta.xml
<CustomField>
    <fullName>Tipo_OS__c</fullName>
    <label>Tipo de OS</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Tipo_OS_Macro__c.field-meta.xml
<CustomField>
    <fullName>Tipo_OS_Macro__c</fullName>
    <label>Tipo de OS Macro</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_macro_Os</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Tipo_OS_Micro__c.field-meta.xml
<CustomField>
    <fullName>Tipo_OS_Micro__c</fullName>
    <label>Tipo de OS Micro</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_micro_OS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Regiao_comercial.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ASSOCIAÇÃO</fullName>
    </customValue>
    <customValue>
        <fullName>BLUETEC</fullName>
    </customValue>
    <customValue>
        <fullName>CANAL SEGURADORAS</fullName>
    </customValue>
    <customValue>
        <fullName>CANAL TELEVENDAS</fullName>
    </customValue>
    <customValue>
        <fullName>CARGO TRACCK</fullName>
    </customValue>
    <customValue>
        <fullName>FRETEIROS</fullName>
    </customValue>
    <customValue>
        <fullName>INATIVOS</fullName>
    </customValue>
    <customValue>
        <fullName>OUTROS</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL CO</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL KA</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL MG/RJ/ES</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL NO/NE</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL NO/NE/CO</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL PR</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL RS</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL SP</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL SPC</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL SPI</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL SP INT</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL SUL</fullName>
    </customValue>
    <customValue>
        <fullName>SBTEC</fullName>
    </customValue>
    <customValue>
        <fullName>SIGGO</fullName>
    </customValue>
    <customValue>
        <fullName>VAREJO</fullName>
    </customValue>
    <customValue>
        <fullName>VIVO</fullName>
    </customValue>
    <customValue>
        <fullName>VAZIO</fullName>
    </customValue>
    <description>Região comercial do BI</description>
    <masterLabel>Região Comercial</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tipo_macro_Os.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Assistência</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação não cobrar</fullName>
    </customValue>
    <customValue>
        <fullName>Retirada</fullName>
    </customValue>
    <customValue>
        <fullName>Sem motivo cadastrado</fullName>
    </customValue>
    <description>Tipos macros da OS.</description>
    <masterLabel>Tipo Macro da Os</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tipo_micro_OS.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sem item cadastrado</fullName>
    </customValue>
    <customValue>
        <fullName>Assistência</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação – Downgrade</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação – Upgrade</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação de Equipamento</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação – TRC</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação não cobrar</fullName>
    </customValue>
    <customValue>
        <fullName>Retirada</fullName>
    </customValue>
    <customValue>
        <fullName>Retirada - TRC</fullName>
    </customValue>
    <masterLabel>Tipo Micro da OS</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DAO_Direcionamento_OS.cls
/*
    Classe de teste: Teste_DAO_Direcionamento_OS
    Criado por: Mario Reis
    Data de criação: 16/04/2018
    Descrição: Classe DAO para o objeto: Direcionamento_os__c
    ---------------------------------
    @author Renan Rocha
    @date 07/01/2019
    @description:
        - Classe refatorada
        - Novos debugs inseridos
        - Criado método getQueryBatch
        - Método getUsuariosSelecionados direcionado para classe DAO_Atendente_Direcionamento_OS e referências corrigidas
        - Métodos getListaUserDisponivel e getListaUser direcionados para classe DAO_Usuario e referências corrigidas
        - Método getListaTipoOS direcionado para classe DAO_Tipo_OS e referências corrigidas
        - Método getListaTipoContrato direcionado para classe DAO_TipoContrato e referências corrigidas
        - Método getListaStatusOS direcionado para classe DAO_Status_OS e referências corrigidas
        - Método getListaTipoItemOS direcionado para classe DAO_Tipo_Item_OS e referências corrigidas
        - Métodos getListaOS, filtrarConsultaPorQuantidadeOS, getListaOsByUser, getMapClienteAtd e getAtdQtd direcionado para classe DAO_Ordem_Servico e referências corrigidas
    @JIRA KCA-59
*/
public class DAO_Direcionamento_OS {

    private static String CLASS_NAME = 'DAO_Direcionamento_OS';

    // Método que retorna o direcionamento de OS pelo Id
    public static Direcionamento_os__c getDirecionamentoOsById(String idRegistro){
        String METHOD_NAME = 'getDirecionamentoOsById';

        System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - idRegistro: '+ idRegistro);

        return
            [SELECT Id
                  , Agendamento_proximo_contato__c
                  , Aging_final__c
                  , Aging_inicial__c
                  , Classe__c
                  , Cliente__c
                  , Cliente_KA__c
                  , Contato_fora_faixa__c
                  , CreatedDate 
                  , Data_agendamento_final__c
                  , Data_agendamento_inicial__c
                  , Item__c
                  , Motivo__c
                  , Motivo_noshow__c
                  , Name
                  , Numero_OS__c
                  , OS_com_agendamento__c
                  , OS_sem_agendamento__c
                  , OS_sem_agendamento_aging_85_dias__c
                  , OS_sem_direcionamento__c
                  , OS_sem_servico__c
                  , Owner.Id
                  , Owner.Name
                  , Quantidade_OS__c
                  , Regiao_comercial__c
                  , Status_OS__c
                  , Tipo_contrato__c
                  , Tipo_OS__c
                  , Tipo_OS_macro__c
                  , Tipo_OS_micro__c
                  , Ultima_acao_OS__c
                  , (SELECT Id
                          , Usuario__c 
                    FROM Atendentes_Direcionamento_OS__r)
            FROM Direcionamento_os__c 
            WHERE Id =: idRegistro];
    } // Fim método getDirecionamentoOsById

    // Método que retorna todos os Direcionamentos de OS por usuário
    public static List<Direcionamento_os__c> getListaDirecionamentoOS(){
        String METHOD_NAME = 'getListaDirecionamentoOS';

        return
            [SELECT Id
                  , Agendamento_proximo_contato__c
                  , Aging_final__c
                  , Aging_inicial__c
                  , Classe__c
                  , Cliente__c
                  , Cliente_KA__c
                  , Contato_fora_faixa__c
                  , CreatedDate 
                  , Data_agendamento_final__c
                  , Data_agendamento_inicial__c
                  , Item__c
                  , Motivo__c
                  , Motivo_noshow__c
                  , Name
                  , Numero_OS__c
                  , OS_com_agendamento__c
                  , OS_sem_agendamento__c
                  , OS_sem_agendamento_aging_85_dias__c
                  , OS_sem_direcionamento__c
                  , OS_sem_servico__c
                  , Owner.Id
                  , Owner.Name
                  , Quantidade_OS__c
                  , Regiao_comercial__c
                  , Status_OS__c
                  , Tipo_contrato__c
                  , Tipo_OS__c
                  , Tipo_OS_macro__c
                  , Tipo_OS_micro__c
                  , Ultima_acao_OS__c
            FROM Direcionamento_os__c 
            WHERE Quantidade_OS__c > 0
            OR Quantidade_OS__c = 0 
            OR Quantidade_OS__c = NULL
            ORDER BY CreatedDate ASC];
    } // Fim método getListaDirecionamentoOS

    /*
        @description Retorna uma string com a query que será utilizada na Batch: Direcionamento_OS_Batch
        @param 
        @return String
        
        @author Renan Rocha
        @date 07/01/2019
        @JIRA KCA-59
    */
    public static String getQueryBatch(){
        String METHOD_NAME = 'getQueryBatch';
        
        return
            'SELECT Id'+
                  ', Agendamento_proximo_contato__c'+
                  ', Aging_final__c'+
                  ', Aging_inicial__c'+
                  ', Classe__c'+
                  ', Cliente__c'+
                  ', Cliente_KA__c'+
                  ', Contato_fora_faixa__c'+
                  ', CreatedDate'+
                  ', Data_agendamento_final__c'+
                  ', Data_agendamento_inicial__c'+
                  ', Item__c'+
                  ', Motivo__c'+
                  ', Motivo_noshow__c'+
                  ', Name'+
                  ', Numero_OS__c'+
                  ', OS_com_agendamento__c'+
                  ', OS_sem_agendamento__c'+
                  ', OS_sem_agendamento_aging_85_dias__c'+
                  ', OS_sem_direcionamento__c'+
                  ', OS_sem_servico__c'+
                  ', Owner.Id'+
                  ', Owner.Name'+
                  ', Quantidade_OS__c'+
                  ', Regiao_comercial__c'+
                  ', Status_OS__c'+
                  ', Tipo_contrato__c'+
                  ', Tipo_OS__c'+
                  ', Tipo_OS_macro__c'+
                  ', Tipo_OS_micro__c'+
                  ', Ultima_acao_OS__c'+
            ' FROM Direcionamento_os__c'+
            ' ORDER BY CreatedDate ASC';
    }
}