force-app/main/default/objects/Atendente_Direcionamento_OS__c/Atendente_Direcionamento_OS__c.object-meta.xml
<CustomObject>
    <label>Atendente Direcionamento OS</label>
    <nameField>
        <displayFormat>ADOS-{000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Atendentes Direcionamento OS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Atendente_Direcionamento_OS__c/fields/Direcionamento_OS__c.field-meta.xml
<CustomField>
    <fullName>Direcionamento_OS__c</fullName>
    <label>Direcionamento de OS</label>
    <referenceTo>Direcionamento_os__c</referenceTo>
    <relationshipLabel>Atendentes Direcionamento OS</relationshipLabel>
    <relationshipName>Atendentes_Direcionamento_OS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Atendente_Direcionamento_OS__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Permitido somente usuários do Atendimento</errorMessage>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Atendimento</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Atendentes_Direcionamento_OS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/Direcionamento_os__c.object-meta.xml
<CustomObject>
    <label>Direcionamento de OS</label>
    <nameField>
        <label>Descrição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Direcionamentos de OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DAO_Atendente_Direcionamento_OS.cls
/*
	@testClass Teste_DAO_Atendente_Direcionamento_OS
	
	@description Classe para o Objeto: Atendente_Direcionamento_OS__c
	
	@author Renan Rocha
	@date 07/01/2019
	@JIRA KCA-59
*/

public class DAO_Atendente_Direcionamento_OS{
	private static String CLASS_NAME = 'DAO_Atendente_Direcionamento_OS';
	
	// Método que retorna lista de Usuarios selecionados na configração
    public static List<Atendente_Direcionamento_OS__c> getUsuariosSelecionados(String idRegistro){
        String METHOD_NAME = 'getUsuariosSelecionados';

        System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - idRegistro: '+ idRegistro);

        return
            [SELECT Id
                  , Direcionamento_OS__c
                  , Name
                  , Usuario__c
                  , Usuario__r.Name
            FROM Atendente_Direcionamento_OS__c
            WHERE Direcionamento_OS__c =: idRegistro];
    } // Fim método getUsuariosSelecionados
}