force-app/main/default/objects/Atendente_Direcionamento_OS__c/Atendente_Direcionamento_OS__c.object-meta.xml
<CustomObject>
    <label>Atendente Direcionamento OS</label>
    <nameField>
        <displayFormat>ADOS-{000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Atendentes Direcionamento OS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Atendente_Direcionamento_OS__c/fields/Direcionamento_OS__c.field-meta.xml
<CustomField>
    <fullName>Direcionamento_OS__c</fullName>
    <label>Direcionamento de OS</label>
    <referenceTo>Direcionamento_os__c</referenceTo>
    <relationshipLabel>Atendentes Direcionamento OS</relationshipLabel>
    <relationshipName>Atendentes_Direcionamento_OS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/Direcionamento_os__c.object-meta.xml
<CustomObject>
    <label>Direcionamento de OS</label>
    <nameField>
        <label>Descrição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Direcionamentos de OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Direcionamento_os__c/fields/Aging_final__c.field-meta.xml
<CustomField>
    <fullName>Aging_final__c</fullName>
    <description>Quantidade de dias do Aging final</description>
    <label>Aging final</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Aging_inicial__c.field-meta.xml
<CustomField>
    <fullName>Aging_inicial__c</fullName>
    <description>Quantidade de dias do Aging inicial</description>
    <label>Aging inicial</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Classe__c.field-meta.xml
<CustomField>
    <fullName>Classe__c</fullName>
    <label>Classe</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACESSÓRIOS CARRETA</fullName>
            </value>
            <value>
                <fullName>BT AEROPORTOS</fullName>
            </value>
            <value>
                <fullName>BT CONSTRUCAO CIVIL</fullName>
            </value>
            <value>
                <fullName>BT Industria - Avançado</fullName>
            </value>
            <value>
                <fullName>BT Industria - Basico</fullName>
            </value>
            <value>
                <fullName>BT Industria - Rental</fullName>
            </value>
            <value>
                <fullName>BT MINA JORNADA</fullName>
            </value>
            <value>
                <fullName>BT MINA PRODUTIVIDADE</fullName>
            </value>
            <value>
                <fullName>BT MINA SEGURANÇA</fullName>
            </value>
            <value>
                <fullName>BT MINERACAO GSM</fullName>
            </value>
            <value>
                <fullName>BT PORTO AVANÇADO</fullName>
            </value>
            <value>
                <fullName>BT PORTO BASICO</fullName>
            </value>
            <value>
                <fullName>CARRETA LOG</fullName>
            </value>
            <value>
                <fullName>CARRETA SOLAR</fullName>
            </value>
            <value>
                <fullName>CCO - GESTÃO AVANÇADA</fullName>
            </value>
            <value>
                <fullName>CCO - GESTÃO AVANÇADA IDENTIFICAÇÃO CAVALO</fullName>
            </value>
            <value>
                <fullName>CCO - GESTAO AVANÇADA (POSICIONAMENTO FREQUENTE)</fullName>
            </value>
            <value>
                <fullName>CCO - GESTÃO AVANÇADA REPETIDORA</fullName>
            </value>
            <value>
                <fullName>CCO - GESTÃO DA PRODUTIVIDADE</fullName>
            </value>
            <value>
                <fullName>CCO - GESTAO DA PRODUTIVIDADE (POSICIONAMENTO FREQUENTE)</fullName>
            </value>
            <value>
                <fullName>CCO - MONITORAMENTO LOGÍSTICO</fullName>
            </value>
            <value>
                <fullName>CCO - MONITORAMENTO LOGÍSTICO (POSICIONAMENTO FREQUENTE)</fullName>
            </value>
            <value>
                <fullName>CELULAR/GSM</fullName>
            </value>
            <value>
                <fullName>EUROPA CARRETA CONECTADA - FRIDGE</fullName>
            </value>
            <value>
                <fullName>EUROPA CARRETA CONECTADA - GEOLOC AND USAGE</fullName>
            </value>
            <value>
                <fullName>EUROPA CARRETA CONECTADA - MAINTENANCE AND SAFETY</fullName>
            </value>
            <value>
                <fullName>EXCLUSIVE LIGHT</fullName>
            </value>
            <value>
                <fullName>FAMILIA GSM</fullName>
            </value>
            <value>
                <fullName>FAMILIA SASMOTO</fullName>
            </value>
            <value>
                <fullName>GESTÃO DE FROTAS - INDONÉSIA</fullName>
            </value>
            <value>
                <fullName>SASTM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <description>Nome do cliente</description>
    <inlineHelpText>Nome do cliente</inlineHelpText>
    <label>Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Cliente_KA__c.field-meta.xml
<CustomField>
    <fullName>Cliente_KA__c</fullName>
    <label>Cliente KA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
            <value>
                <fullName>Todos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Contato_fora_faixa__c.field-meta.xml
<CustomField>
    <fullName>Contato_fora_faixa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contato fora da faixa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Acessório</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Equipamento</label>
            </value>
            <value>
                <fullName>K</fullName>
                <label>Kit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Motivo__c.field-meta.xml
<CustomField>
    <fullName>Motivo__c</fullName>
    <description>ID&#39;s de Tipo do Item da OS</description>
    <label>Motivo</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Motivo_noshow__c.field-meta.xml
<CustomField>
    <fullName>Motivo_noshow__c</fullName>
    <label>Motivo de noshow</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NOSHOW_CLIENTE</fullName>
            </value>
            <value>
                <fullName>ERRO_AGENDAMENTO</fullName>
            </value>
            <value>
                <fullName>NOSHOW_TECNICO</fullName>
            </value>
            <value>
                <fullName>FALTA_EQUIPAMENTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Numero_OS__c.field-meta.xml
<CustomField>
    <fullName>Numero_OS__c</fullName>
    <description>Número da OS</description>
    <label>Número da OS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/OS_com_agendamento__c.field-meta.xml
<CustomField>
    <fullName>OS_com_agendamento__c</fullName>
    <defaultValue>false</defaultValue>
    <description>OS com agendamento válido</description>
    <label>OS com agendamento</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/OS_sem_agendamento_aging_85_dias__c.field-meta.xml
<CustomField>
    <fullName>OS_sem_agendamento_aging_85_dias__c</fullName>
    <defaultValue>false</defaultValue>
    <description>OS sem agendamento com Aging de 85 dias</description>
    <label>OS sem agendamento Aging 85 dias</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/OS_sem_direcionamento__c.field-meta.xml
<CustomField>
    <fullName>OS_sem_direcionamento__c</fullName>
    <defaultValue>false</defaultValue>
    <description>OS não direcionada para nenhum atendente</description>
    <label>OS sem direcionamento</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/OS_sem_servico__c.field-meta.xml
<CustomField>
    <fullName>OS_sem_servico__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OS sem serviço</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Quantidade_OS__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_OS__c</fullName>
    <label>Quantidade de OS</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Status_OS__c.field-meta.xml
<CustomField>
    <fullName>Status_OS__c</fullName>
    <description>ID&#39;s dos Status da OS</description>
    <label>Status da OS</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Tipo_contrato__c.field-meta.xml
<CustomField>
    <fullName>Tipo_contrato__c</fullName>
    <description>ID&#39;s dos tipos de contrato</description>
    <label>Tipo de contrato</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Tipo_OS__c.field-meta.xml
<CustomField>
    <fullName>Tipo_OS__c</fullName>
    <label>Tipo de OS</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Ultima_acao_OS__c.field-meta.xml
<CustomField>
    <fullName>Ultima_acao_OS__c</fullName>
    <label>Última ação da OS</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abertura de O.S</fullName>
            </value>
            <value>
                <fullName>Agendamento Comercial</fullName>
            </value>
            <value>
                <fullName>Agendamento com serviço  não executado</fullName>
            </value>
            <value>
                <fullName>Agendamento não realizado/Agenda indisponível</fullName>
            </value>
            <value>
                <fullName>Agendamento Próximo Contato</fullName>
            </value>
            <value>
                <fullName>Agendamento próximo contato URA</fullName>
            </value>
            <value>
                <fullName>Agendamento realizado com sucesso</fullName>
            </value>
            <value>
                <fullName>Agendamento sem Equipamento (Data Futura)</fullName>
            </value>
            <value>
                <fullName>Agendamento sem Reserva de Estoque</fullName>
            </value>
            <value>
                <fullName>Agendamento via Representação</fullName>
            </value>
            <value>
                <fullName>Aguardando Análise de Deslocamento</fullName>
            </value>
            <value>
                <fullName>Aguardando avaliação de deslocamento</fullName>
            </value>
            <value>
                <fullName>Aguardando Carta de Migração</fullName>
            </value>
            <value>
                <fullName>Aguardando Carta de rescisão</fullName>
            </value>
            <value>
                <fullName>Aguardando o 3º Dia</fullName>
            </value>
            <value>
                <fullName>Aguardando Retorno Cliente</fullName>
            </value>
            <value>
                <fullName>Aguardando Retorno da Corretora</fullName>
            </value>
            <value>
                <fullName>Alterada Combinação</fullName>
            </value>
            <value>
                <fullName>Apoio Comercial</fullName>
            </value>
            <value>
                <fullName>Atraso técnico/Agendamento cancelado</fullName>
            </value>
            <value>
                <fullName>Autorizado (O.S.)</fullName>
            </value>
            <value>
                <fullName>Autorizado Instalação</fullName>
            </value>
            <value>
                <fullName>Cadastro Concluído</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Cancelado pela Seguradora</fullName>
            </value>
            <value>
                <fullName>Cidade Não Mapeada</fullName>
            </value>
            <value>
                <fullName>Cliente Desistiu da Instalação</fullName>
            </value>
            <value>
                <fullName>Cliente Desmarcou</fullName>
            </value>
            <value>
                <fullName>Cliente já possui dispositivo anti-furto</fullName>
            </value>
            <value>
                <fullName>Cliente não concorda c/ contrato locação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Teste_Util_Direcionamento.cls
/*
    Classe de testes para classe: Util_Direcionamento
    Criado por: Mario Reis
    Data: 11/06/2018

*/
@isTest
public class Teste_Util_Direcionamento {

    //Método para criar um direcionamento de OS
    public static Direcionamento_OS__c criarDirecionamentoOSPadrao(){

		Direcionamento_OS__c direcionamentoOS = new Direcionamento_OS__c();

        direcionamentoOS.Name = 'Direcionamento OS';

		insert direcionamentoOS;
        return direcionamentoOS;
    } // Fim criarDirecionamentoOS


    //Método para criar um direcionamento de OS preenchido
    public static Direcionamento_OS__c criarDirecionamentoOSPreenchido(String idStatusOS, 
                                                                       String idTipoContrato, 
                                                                       String idTipoOS){

		Direcionamento_OS__c direcionamentoOS = new Direcionamento_OS__c();

        direcionamentoOS.Name = 'Direcionamento OS';
        direcionamentoOS.Cliente__c = 'cliente';
        direcionamentoOS.Numero_OS__c = '123456';
        direcionamentoOS.OS_sem_agendamento_aging_85_dias__c = true;
        direcionamentoOS.Contato_fora_faixa__c = true;
        direcionamentoOS.OS_com_agendamento__c = true;
        direcionamentoOS.Ultima_acao_OS__c = 'Autorizado (O.S.);Vazio';
        direcionamentoOS.Motivo_noshow__c = 'Motivo no show';
        direcionamentoOS.Status_OS__c = idStatusOS;
        direcionamentoOS.Tipo_contrato__c = idTipoContrato;
        direcionamentoOS.Classe__c = 'SASTM';
        direcionamentoOS.Cliente_KA__c = 'Todos';
        direcionamentoOS.OS_sem_servico__c = true;
        direcionamentoOS.OS_sem_direcionamento__c = true;
        direcionamentoOS.Aging_inicial__c = 0;
        direcionamentoOS.Aging_final__c = 5;
        direcionamentoOS.Tipo_OS__c = idTipoOS;
        // direcionamentoOS.Motivo__c = 'idMotivo';
        direcionamentoOS.Item__c = 'idItem';
        direcionamentoOS.Quantidade_OS__c = 0;

		insert direcionamentoOS;
        return direcionamentoOS;
    } // Fim criarDirecionamentoOSPreenchido


    //Método para criar um atendente do direcionamento
    public static Atendente_Direcionamento_OS__c criarAtendenteDirecionamento(String idDirecionamento, 
                                                                              String idUsuario){

        Atendente_Direcionamento_OS__c atendente = new Atendente_Direcionamento_OS__c();
        atendente.Direcionamento_OS__c = idDirecionamento;
		atendente.Usuario__c = idUsuario;

		insert atendente;
		return atendente;

    } // Fim criarAtendenteDirecionamento

}