force-app/main/default/objects/Lead/recordTypes/Mercosul.recordType-meta.xml
<RecordType>
    <fullName>Mercosul</fullName>
    <active>true</active>
    <businessProcess>CORP</businessProcess>
    <label>Mercosul</label>
</RecordType>

force-app/main/default/objects/Triggers__c/Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuração para ativação/desativação da trigger</description>
    <label>Triggers</label>
</CustomObject>

force-app/main/default/objects/Triggers__c/fields/Trigger_lead__c.field-meta.xml
<CustomField>
    <fullName>Trigger_lead__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Validação para rodar a Trigger_lead</description>
    <inlineHelpText>Validação para rodar a Trigger_lead</inlineHelpText>
    <label>Trigger lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Teste_Trigger_Lead.cls
/*
    Classe de testes para a Trigger "Trigger_Lead"

    Criado por: Mario Reis
    Data: 02/10/2017

*/
@isTest
public class Teste_Trigger_Lead{

    /*
        @author Renan Rocha
        @date 16/11/2018
    */
    static testMethod void teste(){
        Triggers__c confTrigger = new Triggers__c();
        confTrigger.Trigger_lead__c = true;
        insert confTrigger;

        Id mercosulId = Schema.getGlobalDescribe().get('Lead').getDescribe().getRecordTypeInfosByName().get('Mercosul').getRecordTypeId();

        Lead lead = Teste_Util_Lead.criaLeadMercosulCUIT(mercosulId, '27-28081114-4');
    }
}