force-app/main/default/objects/Resumo_analise_manual_oportunidade__c/Resumo_analise_manual_oportunidade__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para receber os dados dos processos de aprovação finalizados, seja com recall, negação ou aprovação. A partir deste objeto é gerado o relatório de processos de aprovação.</description>
    <label>Resumo análise manual oportunidade</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Linha de resumo análise manual oportunid</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resumos análise manual oportunidade</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resumo_analise_manual_oportunidade__c/fields/Aprovador__c.field-meta.xml
<CustomField>
    <fullName>Aprovador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contêm o aprovador desta etapa do processo.</description>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resumos_an_lise_manual_oport_aprovador</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resumo_analise_manual_oportunidade__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <description>Oportunidade que gerou este processo de aprovação.</description>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Resumos análise manual oportunidade</relationshipLabel>
    <relationshipName>Resumos_an_lise_manual_oportunidade</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Resumo_analise_manual_oportunidade__c/fields/Resultado_do_processo__c.field-meta.xml
<CustomField>
    <fullName>Resultado_do_processo__c</fullName>
    <description>Resultado final do processo de aprovação.</description>
    <label>Resultado do processo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resumo_analise_manual_oportunidade__c/fields/T_rmino_do_processo_em__c.field-meta.xml
<CustomField>
    <fullName>T_rmino_do_processo_em__c</fullName>
    <description>Data e hora em que a oportunidade foi aprovada ou rejeitada.</description>
    <label>Término do processo em</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/DAO_ResumoAnaliseManualOpp.cls
/*
  @testClass Teste_DAO_ResumoAnaliseManualOpp

  @description DAO para o objeto: Resumo_analise_manual_oportunidade__c

  @author Renan Rocha
  @date 20/11/2018
  @JIRA KCA-9
*/

public class DAO_ResumoAnaliseManualOpp{

  private static String CLASS_NAME = 'DAO_ResumoAnaliseManualOpp';
  
   /*
    @description Retorna uma lista de Resumo_analise_manual_oportunidade__c conforme o Set informado
    @param Set<Id> pSetId
    @return List<Oportunidade__c>
    
    @author Renan Rocha
  */
  public static List<Resumo_analise_manual_oportunidade__c> getResumoAnaliseManualOppBySetId(Set<Id> pSetId){
    String METHOD_NAME = 'getOportunidade__cBySetId';
  
    return
      [SELECT Id
            , Oportunidade__c
            , Resultado_do_processo__c
            , T_rmino_do_processo_em__c
            , Aprovador__c
      FROM Resumo_analise_manual_oportunidade__c 
      WHERE Oportunidade__c IN: pSetId];    
  }
}