force-app/main/default/objects/Parametrizacao_faixa_aging__c/Parametrizacao_faixa_aging__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para a parametrização das Faixas de Aging.</description>
    <label>Parametrização Faixa de Aging</label>
    <nameField>
        <displayFormat>FA-{0000}</displayFormat>
        <label>Nome de Parametrização Faixa de Aging</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parametrizações Faixas de Aging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/fields/Aging_ate__c.field-meta.xml
<CustomField>
    <fullName>Aging_ate__c</fullName>
    <label>Aging até</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/fields/Aging_de__c.field-meta.xml
<CustomField>
    <fullName>Aging_de__c</fullName>
    <description>Preencher esse campo.</description>
    <label>Aging de</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/fields/Contatos_dias_distintos__c.field-meta.xml
<CustomField>
    <fullName>Contatos_dias_distintos__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Contatos em dias distintos dentro da faixa.</description>
    <label>Contatos dias distintos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/fields/Contatos_faixa__c.field-meta.xml
<CustomField>
    <fullName>Contatos_faixa__c</fullName>
    <defaultValue>false</defaultValue>
    <description>contato por dia dentro da faixa.</description>
    <label>Contatos por faixa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/fields/Nome_faixa__c.field-meta.xml
<CustomField>
    <fullName>Nome_faixa__c</fullName>
    <label>Nome da faixa</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/fields/Quantidade_contatos__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_contatos__c</fullName>
    <label>Quantidade de contatos</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/fields/Quantidade_minima_contatos_por_faixa__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_minima_contatos_por_faixa__c</fullName>
    <label>Quantidade mínima de contatos por faixa</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/fields/Tipo_Macro_OS__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Macro_OS__c</fullName>
    <label>Tipo Macro da Os</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_macro_Os</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/fields/Tipo_Micro_OS__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Micro_OS__c</fullName>
    <label>Tipo Micro da OS</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_micro_OS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Tipo_macro_Os.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Assistência</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação não cobrar</fullName>
    </customValue>
    <customValue>
        <fullName>Retirada</fullName>
    </customValue>
    <customValue>
        <fullName>Sem motivo cadastrado</fullName>
    </customValue>
    <description>Tipos macros da OS.</description>
    <masterLabel>Tipo Macro da Os</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tipo_micro_OS.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sem item cadastrado</fullName>
    </customValue>
    <customValue>
        <fullName>Assistência</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação – Downgrade</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação – Upgrade</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação de Equipamento</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação – TRC</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação não cobrar</fullName>
    </customValue>
    <customValue>
        <fullName>Retirada</fullName>
    </customValue>
    <customValue>
        <fullName>Retirada - TRC</fullName>
    </customValue>
    <masterLabel>Tipo Micro da OS</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DAO_Parametrizacao_Faixa_Aging.cls
/*
	@testClass Teste_DAO_Parametrizacao_Faixa_Aging

	@description DAO para o Objeto: Parametrizacao_faixa_aging__c

	@author Renan Rocha
	@date 03/12/2018
	@JIRA KCA-86
*/

public class DAO_Parametrizacao_Faixa_Aging{
	private static String CLASS_NAME = 'DAO_Parametrizacao_Faixa_Aging';

	/*
		@description Retorna todas as parametrizações cadastradas
		@return List<Parametrizacao_faixa_aging__c>
		
		@author Renan Rocha
		@date 03/12/2018
		@JIRA KCA-86
	*/
	public static List<Parametrizacao_faixa_aging__c> getListParametrizacaoFaixaAging(){
		String METHOD_NAME = 'getListParametrizacaoFaixaAging';
		
		return
			[SELECT Id
				  , Aging_ate__c
				  , Aging_de__c
				  , Contatos_dias_distintos__c
				  , Contatos_faixa__c
				  , Name
				  , Nome_faixa__c
				  , Quantidade_contatos__c
				  , Quantidade_minima_contatos_por_faixa__c
				  , Tipo_Macro_OS__c
				  , Tipo_Micro_OS__c
			FROM Parametrizacao_faixa_aging__c];
	}
}