force-app/main/default/objects/Parametrizacao_faixa_aging__c/Parametrizacao_faixa_aging__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para a parametrização das Faixas de Aging.</description>
    <label>Parametrização Faixa de Aging</label>
    <nameField>
        <displayFormat>FA-{0000}</displayFormat>
        <label>Nome de Parametrização Faixa de Aging</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parametrizações Faixas de Aging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/fields/Aging_ate__c.field-meta.xml
<CustomField>
    <fullName>Aging_ate__c</fullName>
    <label>Aging até</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/fields/Aging_de__c.field-meta.xml
<CustomField>
    <fullName>Aging_de__c</fullName>
    <description>Preencher esse campo.</description>
    <label>Aging de</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/fields/Tipo_Macro_OS__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Macro_OS__c</fullName>
    <label>Tipo Macro da Os</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_macro_Os</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/fields/Tipo_Micro_OS__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Micro_OS__c</fullName>
    <label>Tipo Micro da OS</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_micro_OS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Status_OS__c/Status_OS__c.object-meta.xml
<CustomObject>
    <description>Status das ordens de serviço</description>
    <label>Status da OS</label>
    <nameField>
        <label>Nome do Status da OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Status da OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Status_OS__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Tipo_macro_Os.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Assistência</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação não cobrar</fullName>
    </customValue>
    <customValue>
        <fullName>Retirada</fullName>
    </customValue>
    <customValue>
        <fullName>Sem motivo cadastrado</fullName>
    </customValue>
    <description>Tipos macros da OS.</description>
    <masterLabel>Tipo Macro da Os</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tipo_micro_OS.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sem item cadastrado</fullName>
    </customValue>
    <customValue>
        <fullName>Assistência</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação – Downgrade</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação – Upgrade</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação de Equipamento</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação – TRC</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação não cobrar</fullName>
    </customValue>
    <customValue>
        <fullName>Retirada</fullName>
    </customValue>
    <customValue>
        <fullName>Retirada - TRC</fullName>
    </customValue>
    <masterLabel>Tipo Micro da OS</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Teste_Util_OS_Atualizar_Informacoes.cls
/*
	@testClass Util_OS_Atualizar_Informacoes
	
	@author Renan Rocha
	@date 05/12/2018
*/

@isTest
public class Teste_Util_OS_Atualizar_Informacoes{
	
	/*
		@author Renan Rocha
		@date 05/12/2018
	*/
	static testMethod void atualizarInformacoesOS(){
		Map<String, sObject> mapBase = Teste_Util.createMapBase();

		Parametrizacao_faixa_aging__c paramAging = (Parametrizacao_faixa_aging__c) mapBase.get('Parametrizacao_faixa_aging__c');
		paramAging.Tipo_macro_OS__c = 'Instalação';
		paramAging.Tipo_micro_OS__c = 'Instalação';
		paramAging.Aging_de__c = 2;
		paramAging.Aging_ate__c = null;
		update paramAging;

		WorkOrder OS = (WorkOrder) mapBase.get('WorkOrder');
		OS.Tipo_macro_OS__c = 'Instalação';
		OS.Tipo_micro_OS__c = 'Instalação';
		OS.Aging__c = 4;
		OS.StartDate = System.today().addDays(-4);
		update OS;

		Status_OS__c statusOS = (Status_OS__c) mapBase.get('Status_OS__c');
		statusOS.Tipo__c = 'Pendente';
		update statusOS;

		System.assertEquals(1, Util_OS_Atualizar_informacoes.atualizarInformacoesOS(new List<WorkOrder>{OS}).size());

		statusOS.Tipo__c = 'Finalizado';
		update statusOS;

		OS.Data_atualizacao_status_OS__c  = System.today();
		update OS;

		System.assertEquals(1, Util_OS_Atualizar_informacoes.atualizarInformacoesOS(new List<WorkOrder>{OS}).size());
	}
}