force-app/main/default/objects/Duplicidade_conta__c/Duplicidade_conta__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuração para determinar para quais tipos de registro que a validação será utilizada</description>
    <label>Duplicidade de conta</label>
</CustomObject>

force-app/main/default/objects/Duplicidade_conta__c/fields/Bluetec__c.field-meta.xml
<CustomField>
    <fullName>Bluetec__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Tipo de registro da conta &quot;OTR&quot;</description>
    <inlineHelpText>Ativado para &quot;OTR&quot;</inlineHelpText>
    <label>OTR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Duplicidade_conta__c/fields/CORP__c.field-meta.xml
<CustomField>
    <fullName>CORP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Tipo de registro da conta &quot;CORP&quot;</description>
    <inlineHelpText>Ativado para &quot;CORP&quot;</inlineHelpText>
    <label>CORP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Duplicidade_conta__c/fields/Grupo_economico__c.field-meta.xml
<CustomField>
    <fullName>Grupo_economico__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Tipo de registro da conta &quot;Grupo econômico&quot;</description>
    <inlineHelpText>Ativado para &quot;Grupo econômico&quot;</inlineHelpText>
    <label>Grupo econômico</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Duplicidade_conta__c/fields/Michelin__c.field-meta.xml
<CustomField>
    <fullName>Michelin__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Tipo de registro da conta &quot;Michelin&quot;</description>
    <inlineHelpText>Ativado para &quot;Michelin&quot;</inlineHelpText>
    <label>Michelin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Duplicidade_conta__c/fields/SIGGO__c.field-meta.xml
<CustomField>
    <fullName>SIGGO__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Tipo de registro da conta &quot;SIGGO&quot;</description>
    <inlineHelpText>Ativado para &quot;SIGGO&quot;</inlineHelpText>
    <label>SIGGO</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuração que possui todos os endereços para integração separado por ambiente</description>
    <label>Integrações</label>
</CustomObject>

force-app/main/default/objects/Integracoes__c/fields/Busca_CEP_desenvolvimento__c.field-meta.xml
<CustomField>
    <fullName>Busca_CEP_desenvolvimento__c</fullName>
    <description>Endereço do endpoint de desenvolvimento da busca de CEP</description>
    <inlineHelpText>Endereço do endpoint de desenvolvimento da busca de CEP</inlineHelpText>
    <label>Busca CEP desenvolvimento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integracoes__c/fields/Busca_CEP_homologacao__c.field-meta.xml
<CustomField>
    <fullName>Busca_CEP_homologacao__c</fullName>
    <description>Endereço do endpoint de homologação da busca de CEP</description>
    <inlineHelpText>Endereço do endpoint de homologação da busca de CEP</inlineHelpText>
    <label>Busca CEP homologação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integracoes__c/fields/Busca_CEP_producao__c.field-meta.xml
<CustomField>
    <fullName>Busca_CEP_producao__c</fullName>
    <description>Endereço do endpoint de produção da busca de CEP</description>
    <inlineHelpText>Endereço do endpoint de produção da busca de CEP</inlineHelpText>
    <label>Busca CEP produção</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integracoes__c/fields/Oportunidade_CORP_GP_desenvolvimento__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade_CORP_GP_desenvolvimento__c</fullName>
    <description>Endereço do endpoint de desenvolvimento do serviço &quot;GenerateProposal&quot; da Oportunidade CORP</description>
    <inlineHelpText>Endereço do endpoint de desenvolvimento do serviço &quot;GenerateProposal&quot; da Oportunidade CORP</inlineHelpText>
    <label>Oportunidade CORP GP desenvolvimento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integracoes__c/fields/Oportunidade_CORP_GP_homologacao__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade_CORP_GP_homologacao__c</fullName>
    <description>Endereço do endpoint de homologação do serviço &quot;GenerateProposal&quot; da Oportunidade CORP</description>
    <inlineHelpText>Endereço do endpoint de homologação do serviço &quot;GenerateProposal&quot; da Oportunidade CORP</inlineHelpText>
    <label>Oportunidade CORP GP homologação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integracoes__c/fields/Oportunidade_CORP_GP_producao__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade_CORP_GP_producao__c</fullName>
    <description>Endereço do endpoint de produção do serviço &quot;GenerateProposal&quot; da Oportunidade CORP</description>
    <inlineHelpText>Endereço do endpoint de produção do serviço &quot;GenerateProposal&quot; da Oportunidade CORP</inlineHelpText>
    <label>Oportunidade CORP GP produção</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integracoes__c/fields/Oportunidade_freteiro_GP_desenvolvimento__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade_freteiro_GP_desenvolvimento__c</fullName>
    <description>Endereço do endpoint de desenvolvimento do serviço &quot;GenerateProposal&quot; da Oportunidade FRETEIRO</description>
    <inlineHelpText>Endereço do endpoint de desenvolvimento do serviço &quot;GenerateProposal&quot; da Oportunidade FRETEIRO</inlineHelpText>
    <label>Oportunidade FRETEIRO GP desenvolvimento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integracoes__c/fields/Oportunidade_freteiro_GP_homologacao__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade_freteiro_GP_homologacao__c</fullName>
    <description>Endereço do endpoint de homologação do serviço &quot;GenerateProposal&quot; da Oportunidade FRETEIRO</description>
    <inlineHelpText>Endereço do endpoint de homologação do serviço &quot;GenerateProposal&quot; da Oportunidade FRETEIRO</inlineHelpText>
    <label>Oportunidade FRETEIRO GP homologação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integracoes__c/fields/Oportunidade_freteiro_GP_producao__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade_freteiro_GP_producao__c</fullName>
    <description>Endereço do endpoint de produção do serviço &quot;GenerateProposal&quot; da Oportunidade FRETEIRO</description>
    <inlineHelpText>Endereço do endpoint de produção do serviço &quot;GenerateProposal&quot; da Oportunidade FRETEIRO</inlineHelpText>
    <label>Oportunidade FRETEIRO GP produção</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integracoes__c/fields/Server_cargo_tracck_desenvolvimento__c.field-meta.xml
<CustomField>
    <fullName>Server_cargo_tracck_desenvolvimento__c</fullName>
    <description>Endereço do endpoint de desenvolvimento da Cargo Tracck</description>
    <inlineHelpText>Endereço do endpoint de desenvolvimento da Cargo Tracck</inlineHelpText>
    <label>Server Cargo Tracck desenvolvimento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integracoes__c/fields/Server_cargo_tracck_homologacao__c.field-meta.xml
<CustomField>
    <fullName>Server_cargo_tracck_homologacao__c</fullName>
    <description>Endereço do endpoint de homologação da Cargo Tracck</description>
    <inlineHelpText>Endereço do endpoint de homologação da Cargo Tracck</inlineHelpText>
    <label>Server Cargo Tracck homologação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integracoes__c/fields/Server_cargo_tracck_producao__c.field-meta.xml
<CustomField>
    <fullName>Server_cargo_tracck_producao__c</fullName>
    <description>Endereço do endpoint de produção da Cargo Tracck</description>
    <inlineHelpText>Endereço do endpoint de produção da Cargo Tracck</inlineHelpText>
    <label>Server Cargo Tracck produção</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integracoes__c/fields/Server_SIGGO_desenvolvimento__c.field-meta.xml
<CustomField>
    <fullName>Server_SIGGO_desenvolvimento__c</fullName>
    <description>Endereço do endpoint de desenvolvimento do Server SIGGO</description>
    <inlineHelpText>Endereço do endpoint de desenvolvimento do Server SIGGO</inlineHelpText>
    <label>Server SIGGO desenvolvimento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integracoes__c/fields/Server_SIGGO_homologacao__c.field-meta.xml
<CustomField>
    <fullName>Server_SIGGO_homologacao__c</fullName>
    <description>Endereço do endpoint de homologação do Server SIGGO</description>
    <inlineHelpText>Endereço do endpoint de homologação do Server SIGGO</inlineHelpText>
    <label>Server SIGGO homologação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integracoes__c/fields/Server_SIGGO_producao__c.field-meta.xml
<CustomField>
    <fullName>Server_SIGGO_producao__c</fullName>
    <description>Endereço do endpoint de produção do Server SIGGO</description>
    <inlineHelpText>Endereço do endpoint de produção do Server SIGGO</inlineHelpText>
    <label>Server SIGGO produção</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametros_ORG__c/Parametros_ORG__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Parâmetros gerais da ORG</description>
    <label>Parâmetros ORG</label>
</CustomObject>

force-app/main/default/objects/Parametros_ORG__c/fields/Email_usuario_pentaho__c.field-meta.xml
<CustomField>
    <fullName>Email_usuario_pentaho__c</fullName>
    <description>Email utilizado pelo usuário do pentaho para integração</description>
    <label>Email do usuário do Pentaho</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Servicos__c/Servicos__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Serviços</label>
</CustomObject>

force-app/main/default/objects/Servicos__c/fields/Busca_CEP_Conta__c.field-meta.xml
<CustomField>
    <fullName>Busca_CEP_Conta__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Realizar busca de CEP para a Conta</description>
    <inlineHelpText>Realizar busca de CEP para a Conta</inlineHelpText>
    <label>Busca CEP Conta</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Servicos__c/fields/Busca_CEP_Lead__c.field-meta.xml
<CustomField>
    <fullName>Busca_CEP_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Realizar busca de CEP para o Lead</description>
    <inlineHelpText>Realizar busca de CEP para o Lead</inlineHelpText>
    <label>Busca CEP Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Triggers__c/Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuração para ativação/desativação da trigger</description>
    <label>Triggers</label>
</CustomObject>

force-app/main/default/objects/Triggers__c/fields/Duplicidade_conta__c.field-meta.xml
<CustomField>
    <fullName>Duplicidade_conta__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Trigger &quot;DuplicidadeConta&quot;</description>
    <label>Duplicidade conta</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Triggers__c/fields/Trigger_conta__c.field-meta.xml
<CustomField>
    <fullName>Trigger_conta__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Validação para rodar a Trigger_conta</description>
    <label>Trigger conta</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Triggers__c/fields/Trigger_lead__c.field-meta.xml
<CustomField>
    <fullName>Trigger_lead__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Validação para rodar a Trigger_lead</description>
    <inlineHelpText>Validação para rodar a Trigger_lead</inlineHelpText>
    <label>Trigger lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Teste_Util_Configuracao.cls
/*
    Criado por: Mario Reis
    Data de criação: 25/08/2017
    Descrição: Classe com métodos para criar registros de Configuração Personalizada 
                    para apoio as classes de teste
*/
@isTest
public class Teste_Util_Configuracao {

    // Método para criar a configuração personalizada "Parâmetros ORG"
    public static Parametros_ORG__c criarConfiguracaoParametrosORG(){

        Parametros_ORG__c conf = new Parametros_ORG__c();
        conf.Email_usuario_pentaho__c = 'pentaho@sascar.com.br';

        insert conf;
        return conf;
    } // Fim método criarConfiguracaoParametrosORG


    // Método para criar a configuração personalizada "Triggers"
    public static Triggers__c criarConfiguracaoTriggers(){

        Triggers__c conf = new Triggers__c();
        conf.Duplicidade_conta__c = false;
        conf.Trigger_conta__c = false;
        conf.Trigger_lead__c = false;

        insert conf;
        return conf;
    } // Fim método criarConfiguracaoTriggers


    // Método para criar a configuração personalizada "Integrações"
    public static Integracoes__c criarConfiguracaoIntegracoes(){

        Integracoes__c conf = new Integracoes__c();
		conf.Busca_CEP_desenvolvimento__c = 'http://desenvolvimento.sascar.com.br/sistemaWeb/WS_Siggo/WS_SiggoCRM.php';
        conf.Busca_CEP_homologacao__c = 'http://hom1-intranet.sascar.com.br/sistemaWeb/WS_Siggo/WS_SiggoCRM.php';
        conf.Busca_CEP_producao__c = 'http://intranet.sascar.com.br/WS_Siggo/WS_SiggoCRM.php';
        conf.Oportunidade_CORP_GP_desenvolvimento__c = 'http://desenvolvimento.sascar.com.br/sistemaWeb/WS_CEP/?cep=';
        conf.Oportunidade_CORP_GP_homologacao__c = 'http://hom1.intranet.sascar.com.br/sistemaWeb/WS_CEP/?cep=';
        conf.Oportunidade_CORP_GP_producao__c = 'http://intranet.sascar.com.br/WS_CEP/?cep=';
        conf.Oportunidade_freteiro_GP_desenvolvimento__c = 'http://desenvolvimento.sascar.com.br/sistemaWeb/RESTful/FRETEIRO/GenerateProposal.php';
        conf.Oportunidade_freteiro_GP_homologacao__c = 'http://hom1-intranet.sascar.com.br/sistemaWeb/RESTful/FRETEIRO/GenerateProposal.php';
        conf.Oportunidade_freteiro_GP_producao__c = 'http://intranet.sascar.com.br/RESTful/FRETEIRO/GenerateProposal.php';
        conf.Server_SIGGO_desenvolvimento__c = 'http://desenvolvimento.sascar.com.br/sistemaWeb/RESTful/CORP/GenerateProposal.php';
        conf.Server_SIGGO_homologacao__c = 'http://hom1-intranet.sascar.com.br/sistemaWeb/RESTful/CORP/GenerateProposal.php';
        conf.Server_SIGGO_producao__c = 'http://intranet.sascar.com.br/RESTful/CORP/GenerateProposal.php';
        conf.Server_cargo_tracck_desenvolvimento__c = 'http://desenvolvimento.sascar.com.br/sistemaWeb/WS_SALESFORCE/WS_IntegracaoSalesForce.php';
        conf.Server_cargo_tracck_homologacao__c = 'http://hom1-intranet.sascar.com.br/sistemaWeb/WS_SALESFORCE/WS_IntegracaoSalesForce.php';
        conf.Server_cargo_tracck_producao__c = 'http://intranet.sascar.com.br/WS_SALESFORCE/WS_IntegracaoSalesForce.php';

        insert conf;
        return conf;
    } // Fim método criarConfiguracaoIntegracoes


    // Método para criar a configuração personalizada "Duplicidade de conta"
    public static Duplicidade_conta__c criarConfiguracaoDuplicidadeConta(Boolean verificarBluetec,
        Boolean verificarCORP, Boolean verificarGrupoEconomico, Boolean verificarMichelin, 
        Boolean verificarSIGGO){

        Duplicidade_conta__c conf = new Duplicidade_conta__c();
        conf.Bluetec__c = verificarBluetec;
        conf.CORP__c = verificarCORP;
        conf.Grupo_economico__c = verificarGrupoEconomico;
        conf.Michelin__c = verificarMichelin;
        conf.SIGGO__c = verificarSIGGO;

        insert conf;
        return conf;
    } // Fim método criarConfiguracaoDuplicidadeConta



    // Método para criar a configuração personalizada "Serviços"
    public static Servicos__c criarConfiguracaoServicosORG(){

        Servicos__c conf = new Servicos__c();
        conf.Busca_CEP_Lead__c = false;
		conf.Busca_CEP_Conta__c = false;

        insert conf;
        return conf;
    } // Fim método criarConfiguracaoServicosORG

}