force-app/main/default/objects/TipoContrato__c/TipoContrato__c.object-meta.xml
<CustomObject>
    <label>Tipo de Contrato</label>
    <nameField>
        <label>Tipo de Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Contratos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoContrato__c/fields/Codigo_Externo__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Externo__c</fullName>
    <description>ID do tipo de contrato no ERP</description>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TipoContrato__c/fields/Pais_Referencia__c.field-meta.xml
<CustomField>
    <fullName>Pais_Referencia__c</fullName>
    <description>Iso no padrão Alpha-3 do país</description>
    <inlineHelpText>Insira a sigla com 3 letras no padrão ISO do país que relativo a este registro</inlineHelpText>
    <label>País de Referência</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Teste_Util_Tipo_Contrato.cls
/*
    Classe de testes para cadastro do objeto Tipo de Contrato
    Criado por: Mario Reis
    Data: 12/06/2018
*/
@isTest
public class Teste_Util_Tipo_Contrato {

    //Método para criar Status Concluido Finalizado
    public static TipoContrato__c criarTipoContratoPadrao(){

        TipoContrato__c tipoContrato = new TipoContrato__c();
        tipoContrato.Name = 'Contrato Padrao';
        tipoContrato.Codigo_Externo__c = '1';
        tipoContrato.Ativo__c = true;
        tipoContrato.Pais_Referencia__c = 'BRA';

		insert tipoContrato;
        return tipoContrato;
    }// Fim criarTipoOSInstalacao

}