force-app/main/default/objects/TipoContrato__c/TipoContrato__c.object-meta.xml
<CustomObject>
    <label>Tipo de Contrato</label>
    <nameField>
        <label>Tipo de Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Contratos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoContrato__c/fields/Pais_Referencia__c.field-meta.xml
<CustomField>
    <fullName>Pais_Referencia__c</fullName>
    <description>Iso no padrão Alpha-3 do país</description>
    <inlineHelpText>Insira a sigla com 3 letras no padrão ISO do país que relativo a este registro</inlineHelpText>
    <label>País de Referência</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DAO_TipoContrato.cls
/*
	@testClass Teste_DAO_TipoContrato
	
	@description Classe para o Objeto: TipoContrato__c
	
	@author Renan Rocha
	@date 07/01/2019
	@JIRA KCA-59
*/

public class DAO_TipoContrato{
	private static String CLASS_NAME = 'DAO_TipoContrato';
	
	// Método que retorna todos os Tipos de contrato
    public static List<TipoContrato__c> getListaTipoContrato(){
        String METHOD_NAME = 'getListaTipoContrato';

        return
            [SELECT Id
                  , Ativo__c
                  , Name
            FROM TipoContrato__c 
            WHERE Ativo__c = true 
            AND Pais_referencia__c = 'BRA'
            ORDER BY Name];
    } // Fim método getListaTipoContrato
}