force-app/main/default/objects/Direcionamento_os__c/Direcionamento_os__c.object-meta.xml
<CustomObject>
    <label>Direcionamento de OS</label>
    <nameField>
        <label>Descrição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Direcionamentos de OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Direcionamento_os__c/fields/Classe__c.field-meta.xml
<CustomField>
    <fullName>Classe__c</fullName>
    <label>Classe</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACESSÓRIOS CARRETA</fullName>
            </value>
            <value>
                <fullName>BT AEROPORTOS</fullName>
            </value>
            <value>
                <fullName>BT CONSTRUCAO CIVIL</fullName>
            </value>
            <value>
                <fullName>BT Industria - Avançado</fullName>
            </value>
            <value>
                <fullName>BT Industria - Basico</fullName>
            </value>
            <value>
                <fullName>BT Industria - Rental</fullName>
            </value>
            <value>
                <fullName>BT MINA JORNADA</fullName>
            </value>
            <value>
                <fullName>BT MINA PRODUTIVIDADE</fullName>
            </value>
            <value>
                <fullName>BT MINA SEGURANÇA</fullName>
            </value>
            <value>
                <fullName>BT MINERACAO GSM</fullName>
            </value>
            <value>
                <fullName>BT PORTO AVANÇADO</fullName>
            </value>
            <value>
                <fullName>BT PORTO BASICO</fullName>
            </value>
            <value>
                <fullName>CARRETA LOG</fullName>
            </value>
            <value>
                <fullName>CARRETA SOLAR</fullName>
            </value>
            <value>
                <fullName>CCO - GESTÃO AVANÇADA</fullName>
            </value>
            <value>
                <fullName>CCO - GESTÃO AVANÇADA IDENTIFICAÇÃO CAVALO</fullName>
            </value>
            <value>
                <fullName>CCO - GESTAO AVANÇADA (POSICIONAMENTO FREQUENTE)</fullName>
            </value>
            <value>
                <fullName>CCO - GESTÃO AVANÇADA REPETIDORA</fullName>
            </value>
            <value>
                <fullName>CCO - GESTÃO DA PRODUTIVIDADE</fullName>
            </value>
            <value>
                <fullName>CCO - GESTAO DA PRODUTIVIDADE (POSICIONAMENTO FREQUENTE)</fullName>
            </value>
            <value>
                <fullName>CCO - MONITORAMENTO LOGÍSTICO</fullName>
            </value>
            <value>
                <fullName>CCO - MONITORAMENTO LOGÍSTICO (POSICIONAMENTO FREQUENTE)</fullName>
            </value>
            <value>
                <fullName>CELULAR/GSM</fullName>
            </value>
            <value>
                <fullName>EUROPA CARRETA CONECTADA - FRIDGE</fullName>
            </value>
            <value>
                <fullName>EUROPA CARRETA CONECTADA - GEOLOC AND USAGE</fullName>
            </value>
            <value>
                <fullName>EUROPA CARRETA CONECTADA - MAINTENANCE AND SAFETY</fullName>
            </value>
            <value>
                <fullName>EXCLUSIVE LIGHT</fullName>
            </value>
            <value>
                <fullName>FAMILIA GSM</fullName>
            </value>
            <value>
                <fullName>FAMILIA SASMOTO</fullName>
            </value>
            <value>
                <fullName>GESTÃO DE FROTAS - INDONÉSIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Cliente_KA__c.field-meta.xml
<CustomField>
    <fullName>Cliente_KA__c</fullName>
    <label>Cliente KA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
            <value>
                <fullName>Todos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Acessório</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Equipamento</label>
            </value>
            <value>
                <fullName>K</fullName>
                <label>Kit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Motivo_noshow__c.field-meta.xml
<CustomField>
    <fullName>Motivo_noshow__c</fullName>
    <label>Motivo de noshow</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NOSHOW_CLIENTE</fullName>
            </value>
            <value>
                <fullName>ERRO_AGENDAMENTO</fullName>
            </value>
            <value>
                <fullName>NOSHOW_TECNICO</fullName>
            </value>
            <value>
                <fullName>FALTA_EQUIPAMENTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Regiao_comercial__c.field-meta.xml
<CustomField>
    <fullName>Regiao_comercial__c</fullName>
    <label>Região Comercial</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regiao_comercial</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Status_OS__c.field-meta.xml
<CustomField>
    <fullName>Status_OS__c</fullName>
    <description>ID&#39;s dos Status da OS</description>
    <label>Status da OS</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Status_solicitacao_equipamento__c.field-meta.xml
<CustomField>
    <fullName>Status_solicitacao_equipamento__c</fullName>
    <description>Status solicitação equipamento para distribuição</description>
    <label>Status solicitação equipamento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando estoque CD</fullName>
            </value>
            <value>
                <fullName>Atendido</fullName>
            </value>
            <value>
                <fullName>Estoque CD reabastecido</fullName>
            </value>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Recusado</fullName>
            </value>
            <value>
                <fullName>Sem Solicitação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Tipo_OS__c.field-meta.xml
<CustomField>
    <fullName>Tipo_OS__c</fullName>
    <label>Tipo de OS</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Tipo_OS_Macro__c.field-meta.xml
<CustomField>
    <fullName>Tipo_OS_Macro__c</fullName>
    <label>Tipo de OS Macro</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_macro_Os</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Tipo_OS_Micro__c.field-meta.xml
<CustomField>
    <fullName>Tipo_OS_Micro__c</fullName>
    <label>Tipo de OS Micro</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_micro_OS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Ultima_acao_OS__c.field-meta.xml
<CustomField>
    <fullName>Ultima_acao_OS__c</fullName>
    <label>Última ação da OS</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abertura de O.S</fullName>
            </value>
            <value>
                <fullName>Agendamento Comercial</fullName>
            </value>
            <value>
                <fullName>Agendamento com serviço  não executado</fullName>
            </value>
            <value>
                <fullName>Agendamento não realizado/Agenda indisponível</fullName>
            </value>
            <value>
                <fullName>Agendamento Próximo Contato</fullName>
            </value>
            <value>
                <fullName>Agendamento próximo contato URA</fullName>
            </value>
            <value>
                <fullName>Agendamento realizado com sucesso</fullName>
            </value>
            <value>
                <fullName>Agendamento sem Equipamento (Data Futura)</fullName>
            </value>
            <value>
                <fullName>Agendamento sem Reserva de Estoque</fullName>
            </value>
            <value>
                <fullName>Agendamento via Representação</fullName>
            </value>
            <value>
                <fullName>Aguardando Análise de Deslocamento</fullName>
            </value>
            <value>
                <fullName>Aguardando avaliação de deslocamento</fullName>
            </value>
            <value>
                <fullName>Aguardando Carta de Migração</fullName>
            </value>
            <value>
                <fullName>Aguardando Carta de rescisão</fullName>
            </value>
            <value>
                <fullName>Aguardando o 3º Dia</fullName>
            </value>
            <value>
                <fullName>Aguardando Retorno Cliente</fullName>
            </value>
            <value>
                <fullName>Aguardando Retorno da Corretora</fullName>
            </value>
            <value>
                <fullName>Alterada Combinação</fullName>
            </value>
            <value>
                <fullName>Apoio Comercial</fullName>
            </value>
            <value>
                <fullName>Atraso técnico/Agendamento cancelado</fullName>
            </value>
            <value>
                <fullName>Autorizado (O.S.)</fullName>
            </value>
            <value>
                <fullName>Autorizado Instalação</fullName>
            </value>
            <value>
                <fullName>Cadastro Concluído</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Cancelado pela Seguradora</fullName>
            </value>
            <value>
                <fullName>Cidade Não Mapeada</fullName>
            </value>
            <value>
                <fullName>Cliente Desistiu da Instalação</fullName>
            </value>
            <value>
                <fullName>Cliente Desmarcou</fullName>
            </value>
            <value>
                <fullName>Cliente já possui dispositivo anti-furto</fullName>
            </value>
            <value>
                <fullName>Cliente não concorda c/ contrato locação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Status_OS__c/Status_OS__c.object-meta.xml
<CustomObject>
    <description>Status das ordens de serviço</description>
    <label>Status da OS</label>
    <nameField>
        <label>Nome do Status da OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Status da OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_item_OS__c/Tipo_item_OS__c.object-meta.xml
<CustomObject>
    <label>Tipo do item da OS</label>
    <nameField>
        <label>Nome do tipo do item da OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos dos itens da OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_item_OS__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <description>Classificação do Item da OS (A=Acessório, E= Equipamento e K= Kit)</description>
    <inlineHelpText>A = Acessório
E = Equipamento
K = Kit</inlineHelpText>
    <label>Item</label>
    <length>1</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tipo_item_OS__c/fields/Tipo_OS__c.field-meta.xml
<CustomField>
    <fullName>Tipo_OS__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Tipo de OS</description>
    <label>Tipo de OS</label>
    <referenceTo>Tipo_OS__c</referenceTo>
    <relationshipLabel>Tipos dos itens da OS</relationshipLabel>
    <relationshipName>Tipos_dos_itens_da_OS</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tipo_OS__c/Tipo_OS__c.object-meta.xml
<CustomObject>
    <description>Registra os tipos de OS disponíveis para uso</description>
    <label>Tipo de OS</label>
    <nameField>
        <label>Nome do Tipo de OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoContrato__c/TipoContrato__c.object-meta.xml
<CustomObject>
    <label>Tipo de Contrato</label>
    <nameField>
        <label>Tipo de Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Contratos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Regiao_comercial.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ASSOCIAÇÃO</fullName>
    </customValue>
    <customValue>
        <fullName>BLUETEC</fullName>
    </customValue>
    <customValue>
        <fullName>CANAL SEGURADORAS</fullName>
    </customValue>
    <customValue>
        <fullName>CANAL TELEVENDAS</fullName>
    </customValue>
    <customValue>
        <fullName>CARGO TRACCK</fullName>
    </customValue>
    <customValue>
        <fullName>FRETEIROS</fullName>
    </customValue>
    <customValue>
        <fullName>INATIVOS</fullName>
    </customValue>
    <customValue>
        <fullName>OUTROS</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL CO</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL KA</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL MG/RJ/ES</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL NO/NE</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL NO/NE/CO</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL PR</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL RS</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL SP</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL SPC</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL SPI</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL SP INT</fullName>
    </customValue>
    <customValue>
        <fullName>REGIONAL SUL</fullName>
    </customValue>
    <customValue>
        <fullName>SBTEC</fullName>
    </customValue>
    <customValue>
        <fullName>SIGGO</fullName>
    </customValue>
    <customValue>
        <fullName>VAREJO</fullName>
    </customValue>
    <customValue>
        <fullName>VIVO</fullName>
    </customValue>
    <customValue>
        <fullName>VAZIO</fullName>
    </customValue>
    <description>Região comercial do BI</description>
    <masterLabel>Região Comercial</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tipo_macro_Os.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Assistência</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação não cobrar</fullName>
    </customValue>
    <customValue>
        <fullName>Retirada</fullName>
    </customValue>
    <customValue>
        <fullName>Sem motivo cadastrado</fullName>
    </customValue>
    <description>Tipos macros da OS.</description>
    <masterLabel>Tipo Macro da Os</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tipo_micro_OS.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sem item cadastrado</fullName>
    </customValue>
    <customValue>
        <fullName>Assistência</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação – Downgrade</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação – Upgrade</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação de Equipamento</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação – TRC</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação não cobrar</fullName>
    </customValue>
    <customValue>
        <fullName>Retirada</fullName>
    </customValue>
    <customValue>
        <fullName>Retirada - TRC</fullName>
    </customValue>
    <masterLabel>Tipo Micro da OS</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Util_Direcionamento.cls
/*
	Classe de teste: Teste_Util_Direcionamento
	Criado por: Mario Reis
	Data de criação: 20/05/2018
	Descrição: Classe com métodos para a tela de Direcionamento de OS
    ---------------------------------
    @author Renan Rocha
    @date 09/01/2019
    @description:
        - Classe refatorada
        - Novos debugs inseridos
        - Alterado classe de busca no método getStatusOS da classe DAO_Direcionamento_OS para a classe DAO_Status_OS
        - Alterado classe de busca no método getTipoOS da classe DAO_Direcionamento_OS para a classe DAO_Tipo_OS
        - Alterado classe de busca no método getTipoContrato da classe DAO_Direcionamento_OS para a classe DAO_TipoContrato
        - Alterado classe de busca no método getListaMotivo da classe DAO_Direcionamento_OS para a classe DAO_Tipo_Item_OS
    @JIRA KCA-59
*/
global with sharing class Util_Direcionamento {

    private static String CLASS_NAME = 'Util_Direcionamento';

    // Método que retorna se o usuário tem permissão para criar o direcionamento
    webservice static Boolean getStatusCriarDirecionamento(){
        String METHOD_NAME = 'getStatusCriarDirecionamento';

        Boolean retorno = false;
        
        try {
            List<PermissionSetAssignment> conjuntoPerm = DAO_Conjunto_Permissao.getConjPermissaoByUserAssignedIdAndName(UserInfo.getUserId(), 'Acesso_criar_direcionamento');
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - conjuntoPerm: '+ conjuntoPerm);

            if(conjuntoPerm.size() > 0) retorno = true;
            else retorno = false;

            return retorno;
        } catch (Exception e){
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - #ERROR: '+ e.getLineNumber() +':'+ e.getMessage());

            return false;
        } // Fim try/catch
    } // Fim getStatusCriarDirecionamento

    // Método que retorna a lista de Status solicitação equipamento para distribuição
    webservice static List<String> getStatusSolicitacaoEquipamento(){
        String METHOD_NAME = 'getStatusSolicitacaoEquipamento';

        List<String> listaRetorno = new List<String>();
        
        try {
            // Busca a lista de Status solicitação equipamento para distribuição do objeto Direcionamento_os__c
            Schema.DescribeFieldResult campos = Direcionamento_os__c.Status_solicitacao_equipamento__c.getDescribe();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - campos: '+ campos);

            List<Schema.PicklistEntry> ple = campos.getPicklistValues();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - ple: '+ ple);
            
            for(Schema.PicklistEntry f : ple) listaRetorno.add(f.getValue()+'|'+f.getLabel());
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - listaRetorno: '+ listaRetorno);

            return listaRetorno;
        } catch (Exception e){
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - #ERROR: '+ e.getLineNumber() +':'+ e.getMessage());

            return new List<String>();
        } // Fim try/catch
    } // Fim getStatusSolicitacaoEquipamento

    // Método que retorna a lista de Status da OS
    webservice static List<Status_OS__c> getStatusOS(){
        String METHOD_NAME = 'getStatusOS';

        try {
            // Busca lista de Status da OS
            List<Status_OS__c> listaRetorno = DAO_Status_OS.getListaStatusOS();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - listaRetorno: '+ listaRetorno);

            return listaRetorno;
        } catch (Exception e){
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - #ERROR: '+ e.getLineNumber() +':'+ e.getMessage());

            return new List<Status_OS__c>();
        } // Fim try/catch
    } // Fim getStatusOS

    // Método que retorna a lista de Ultima ação da OS
    webservice static List<String> getUltimaAcaoOS(){
        String METHOD_NAME = 'getUltimaAcaoOS';

        List<String> listaRetorno = new List<String>();

        try {
            // Busca a lista de ultima ação da OS do objeto Direcionamento_os__c
            Schema.DescribeFieldResult campos = Direcionamento_os__c.Ultima_acao_OS__c.getDescribe();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - campos: '+ campos);
            
            List<Schema.PicklistEntry> ple = campos.getPicklistValues();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - ple: '+ ple);

            for(Schema.PicklistEntry f : ple) listaRetorno.add(f.getValue()+'|'+f.getLabel());
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - listaRetorno: '+ listaRetorno);

            return listaRetorno;
        } catch (Exception e){
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - #ERROR: '+ e.getLineNumber() +':'+ e.getMessage());

            return new List<String>();
        } // Fim try/catch
    } // Fim getUltimaAcaoOS

     // Método que retorna a lista de Tipo da OS
    webservice static List<Tipo_OS__c> getTipoOS(){
        String METHOD_NAME = 'getTipoOS';

        try {
            // Busca lista de tipo da OS
            List<Tipo_OS__c> listaRetorno = DAO_Tipo_OS.getListaTipoOS();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - listaRetorno: '+ listaRetorno);

            return listaRetorno;
        } catch (Exception e){
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - #ERROR: '+ e.getLineNumber() +':'+ e.getMessage());

            return new List<Tipo_OS__c>();
        } // Fim try/catch
    } // Fim getTipoOS

     // Método que retorna a lista de Item
    webservice static List<String> getListaItem(){
        String METHOD_NAME = 'getListaItem';

        List<String> listaRetorno = new List<String>();

        try {
            // Busca a lista de item do objeto Direcionamento_os__c
            Schema.DescribeFieldResult campos = Direcionamento_os__c.Item__c.getDescribe();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - campos: '+ campos);

            List<Schema.PicklistEntry> ple = campos.getPicklistValues();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - ple: '+ ple);
            
            for( Schema.PicklistEntry f : ple) listaRetorno.add(f.getValue()+'|'+f.getLabel());
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - listaRetorno: '+ listaRetorno);

            return listaRetorno;
        } catch (Exception e){
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - #ERROR: '+ e.getLineNumber() +':'+ e.getMessage());

            return new List<String>();
        } // Fim try/catch
    } // Fim getListaItem

    // Método que retorna a lista de Tipo de Contrato
    webservice static List<TipoContrato__c> getTipoContrato(){
        String METHOD_NAME = 'getTipoContrato';

        try {
            // Busca lista de tipo de contrato
            List<TipoContrato__c> listaRetorno = DAO_TipoContrato.getListaTipoContrato();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - listaRetorno: '+ listaRetorno);

            return listaRetorno;
        } catch (Exception e){
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - #ERROR: '+ e.getLineNumber() +':'+ e.getMessage());

            return new List<TipoContrato__c>();
        } // Fim try/catch
    } // Fim getTipoContrato

    // Método que retorna a lista de classe
    webservice static List<String> getListaClasse(){
        String METHOD_NAME = 'getListaClasse';

        List<String> listaRetorno = new List<String>();
        
        try {
            // Busca a lista de classe do objeto Direcionamento_os__c
            Schema.DescribeFieldResult campos = Direcionamento_os__c.Classe__c.getDescribe();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - campos: '+ campos);
            
            List<Schema.PicklistEntry> ple = campos.getPicklistValues();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - ple: '+ ple);
            
            for(Schema.PicklistEntry f : ple) listaRetorno.add(f.getValue()+'|'+f.getLabel());
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - listaRetorno: '+ listaRetorno);

            return listaRetorno;
        } catch (Exception e){
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - #ERROR: '+ e.getLineNumber() +':'+ e.getMessage());
            
            return new List<String>();
        } // Fim try/catch
    } // Fim getListaClasse

    // Método que retorna a lista de Motivo de noshow
    webservice static List<String> getMotivoNoshowOS(){
        String METHOD_NAME = 'getMotivoNoshowOS';

        List<String> listaRetorno = new List<String>();

        try {
            // Busca a lista de motivo noshow do objeto Direcionamento_os__c
            Schema.DescribeFieldResult campos = Direcionamento_os__c.Motivo_noshow__c.getDescribe();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - campos: '+ campos);
            
            List<Schema.PicklistEntry> ple = campos.getPicklistValues();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - ple: '+ ple);
            
            for(Schema.PicklistEntry f : ple) listaRetorno.add(f.getValue()+'|'+f.getLabel());
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - listaRetorno: '+ listaRetorno);

            return listaRetorno;
        } catch (Exception e){
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - #ERROR: '+ e.getLineNumber() +':'+ e.getMessage());
            
            return new List<String>();
        } // Fim try/catch
    } // Fim getMotivoNoshowOS
    
    // Método que retorna a lista de cliente KA
    webservice static List<String> getClienteKA(){
        String METHOD_NAME = 'getClienteKA';

        List<String> listaRetorno = new List<String>();

        try {
            // Busca a lista de cliente KA do objeto Direcionamento_os__c
            Schema.DescribeFieldResult campos = Direcionamento_os__c.Cliente_KA__c.getDescribe();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - campos: '+ campos);

            List<Schema.PicklistEntry> ple = campos.getPicklistValues();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - ple: '+ ple);
            
            for(Schema.PicklistEntry f : ple) listaRetorno.add(f.getValue()+'|'+f.getLabel());
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - listaRetorno: '+ listaRetorno);

            return listaRetorno;
        } catch (Exception e){
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - #ERROR: '+ e.getLineNumber() +':'+ e.getMessage());
            
            return new List<String>();
        } // Fim try/catch
    } // Fim getClienteKA

    // Método que retorna a lista de Motivo conforme item e tipo
    webservice static List<Tipo_item_OS__c> getListaMotivo(String tipoParametro, String itemParametro){
        String METHOD_NAME = 'getListaMotivo';

        System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - tipoParametro: '+ tipoParametro);
        System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - itemParametro: '+ itemParametro);

        try {
            // Busca lista de tipo de item da OS
            List<Tipo_item_OS__c> listaRetorno = DAO_Tipo_Item_OS.getListaTipoItemOS(tipoParametro, itemParametro);
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - listaRetorno: '+ listaRetorno);

            return listaRetorno;
        } catch (Exception e){
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - #ERROR: '+ e.getLineNumber() +':'+ e.getMessage());

            return new List<Tipo_item_OS__c>();
        } // Fim try/catch
    } // Fim getListaMotivo

    // Método que retorna a lista de Região Comercial
    webservice static List<String> getRegiaoComercial(){
        String METHOD_NAME = 'getRegiaoComercial';

        List<String> listaRetorno = new List<String>();

        try {
            // Busca a lista de cliente KA do objeto Direcionamento_os__c
            Schema.DescribeFieldResult campos = Direcionamento_os__c.Regiao_comercial__c.getDescribe();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - campos: '+ campos);

            List<Schema.PicklistEntry> ple = campos.getPicklistValues();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - ple: '+ ple);

            for(Schema.PicklistEntry f : ple) listaRetorno.add(f.getValue()+'|'+f.getLabel());
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - listaRetorno: '+ listaRetorno);

            return listaRetorno;
        } catch (Exception e){
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - #ERROR: '+ e.getLineNumber() +':'+ e.getMessage());

            return new List<String>();
        } // Fim try/catch
    } // Fim getRegiaoComercial

    // Método que retorna a lista de Tipo de OS Macro
    webservice static List<String> getTipoOSMacro(){
        String METHOD_NAME = 'getTipoOSMacro';

        List<String> listaRetorno = new List<String>();

        try {
            // Busca a lista de cliente KA do objeto Direcionamento_os__c
            Schema.DescribeFieldResult campos = Direcionamento_os__c.Tipo_OS_macro__c.getDescribe();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - campos: '+ campos);

            List<Schema.PicklistEntry> ple = campos.getPicklistValues();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - ple: '+ ple);

            for( Schema.PicklistEntry f : ple) listaRetorno.add(f.getValue()+'|'+f.getLabel());
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - listaRetorno: '+ listaRetorno);

            return listaRetorno;
        } catch (Exception e){
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - #ERROR: '+ e.getLineNumber() +':'+ e.getMessage());

            return new List<String>();
        } // Fim try/catch
    } // Fim getTipoOSMacro

    // Método que retorna a lista de Tipo de OS Micro
    webservice static List<String> getTipoOSMicro(){
        String METHOD_NAME = 'getTipoOSMicro';

        List<String> listaRetorno = new List<String>();

        try {
            // Busca a lista de cliente KA do objeto Direcionamento_os__c
            Schema.DescribeFieldResult campos = Direcionamento_os__c.Tipo_OS_micro__c.getDescribe();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - campos: '+ campos);

            List<Schema.PicklistEntry> ple = campos.getPicklistValues();
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - ple: '+ ple);

            for( Schema.PicklistEntry f : ple) listaRetorno.add(f.getValue()+'|'+f.getLabel());
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - listaRetorno: '+ listaRetorno);

            return listaRetorno;
        } catch (Exception e){
            System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - #ERROR: '+ e.getLineNumber() +':'+ e.getMessage());

            return new List<String>();
        } // Fim try/catch
    } // Fim getTipoOSMicro
}