force-app/main/default/objects/Direcionamento_os__c/Direcionamento_os__c.object-meta.xml
<CustomObject>
    <label>Direcionamento de OS</label>
    <nameField>
        <label>Descrição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Direcionamentos de OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Direcionamento_os__c/fields/Aging_final__c.field-meta.xml
<CustomField>
    <fullName>Aging_final__c</fullName>
    <description>Quantidade de dias do Aging final</description>
    <label>Aging final</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Aging_inicial__c.field-meta.xml
<CustomField>
    <fullName>Aging_inicial__c</fullName>
    <description>Quantidade de dias do Aging inicial</description>
    <label>Aging inicial</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <description>Nome do cliente</description>
    <inlineHelpText>Nome do cliente</inlineHelpText>
    <label>Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Cliente_KA__c.field-meta.xml
<CustomField>
    <fullName>Cliente_KA__c</fullName>
    <label>Cliente KA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
            <value>
                <fullName>Todos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Quantidade_OS__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_OS__c</fullName>
    <label>Quantidade de OS</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Status_OS__c.field-meta.xml
<CustomField>
    <fullName>Status_OS__c</fullName>
    <description>ID&#39;s dos Status da OS</description>
    <label>Status da OS</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Tipo_OS__c.field-meta.xml
<CustomField>
    <fullName>Tipo_OS__c</fullName>
    <label>Tipo de OS</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Ultima_acao_OS__c.field-meta.xml
<CustomField>
    <fullName>Ultima_acao_OS__c</fullName>
    <label>Última ação da OS</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abertura de O.S</fullName>
            </value>
            <value>
                <fullName>Agendamento Comercial</fullName>
            </value>
            <value>
                <fullName>Agendamento com serviço  não executado</fullName>
            </value>
            <value>
                <fullName>Agendamento não realizado/Agenda indisponível</fullName>
            </value>
            <value>
                <fullName>Agendamento Próximo Contato</fullName>
            </value>
            <value>
                <fullName>Agendamento próximo contato URA</fullName>
            </value>
            <value>
                <fullName>Agendamento realizado com sucesso</fullName>
            </value>
            <value>
                <fullName>Agendamento sem Equipamento (Data Futura)</fullName>
            </value>
            <value>
                <fullName>Agendamento sem Reserva de Estoque</fullName>
            </value>
            <value>
                <fullName>Agendamento via Representação</fullName>
            </value>
            <value>
                <fullName>Aguardando Análise de Deslocamento</fullName>
            </value>
            <value>
                <fullName>Aguardando avaliação de deslocamento</fullName>
            </value>
            <value>
                <fullName>Aguardando Carta de Migração</fullName>
            </value>
            <value>
                <fullName>Aguardando Carta de rescisão</fullName>
            </value>
            <value>
                <fullName>Aguardando o 3º Dia</fullName>
            </value>
            <value>
                <fullName>Aguardando Retorno Cliente</fullName>
            </value>
            <value>
                <fullName>Aguardando Retorno da Corretora</fullName>
            </value>
            <value>
                <fullName>Alterada Combinação</fullName>
            </value>
            <value>
                <fullName>Apoio Comercial</fullName>
            </value>
            <value>
                <fullName>Atraso técnico/Agendamento cancelado</fullName>
            </value>
            <value>
                <fullName>Autorizado (O.S.)</fullName>
            </value>
            <value>
                <fullName>Autorizado Instalação</fullName>
            </value>
            <value>
                <fullName>Cadastro Concluído</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Cancelado pela Seguradora</fullName>
            </value>
            <value>
                <fullName>Cidade Não Mapeada</fullName>
            </value>
            <value>
                <fullName>Cliente Desistiu da Instalação</fullName>
            </value>
            <value>
                <fullName>Cliente Desmarcou</fullName>
            </value>
            <value>
                <fullName>Cliente já possui dispositivo anti-furto</fullName>
            </value>
            <value>
                <fullName>Cliente não concorda c/ contrato locação</fullName>
            </value>
            <value>
                <fullName>Vazio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Status_OS__c/Status_OS__c.object-meta.xml
<CustomObject>
    <description>Status das ordens de serviço</description>
    <label>Status da OS</label>
    <nameField>
        <label>Nome do Status da OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Status da OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_OS__c/Tipo_OS__c.object-meta.xml
<CustomObject>
    <description>Registra os tipos de OS disponíveis para uso</description>
    <label>Tipo de OS</label>
    <nameField>
        <label>Nome do Tipo de OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoContrato__c/TipoContrato__c.object-meta.xml
<CustomObject>
    <label>Tipo de Contrato</label>
    <nameField>
        <label>Tipo de Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Contratos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Teste_DAO_Ordem_Servico.cls
/*
	@testClass DAO_Ordem_Servico
	
	@author Renan Rocha
	@date 04/12/2018
*/

@isTest
public class Teste_DAO_Ordem_Servico{
	
	/*
		@author Renan Rocha
		@date 04/12/2018
	*/
	static testMethod void  getListaOrdemServico(){
		Map<String, sObject> mapBase = Teste_Util.createMapBase();
		WorkOrder OS = (WorkOrder) mapBase.get('WorkOrder');

		System.assertEquals(1, DAO_Ordem_Servico.getListaOrdemServico(new Set<Id>{OS.Id}).size());
	}

	/*
		@author Renan Rocha
		@date 04/12/2018
	*/
	static testMethod void getQueryBatch(){
		System.assertNotEquals(null, DAO_Ordem_Servico.getQueryBatch(null));
	}

	/*
		@author Renan Rocha
		@date 05/12/2018
	*/
	static testMethod void getOrdemById(){
		Map<String, sObject> mapBase = Teste_Util.createMapBase();
		WorkOrder OS = (WorkOrder) mapBase.get('WorkOrder');

		System.assertEquals(OS.Id, DAO_Ordem_Servico.getOrdemById(OS.Id).Id);
	}

	static testMethod void getListaOS(){
                Status_OS__c statusPendente = Teste_Util_Status_OS.criarStatusAutorizadoPendente();
                Tipo_OS__c tipoOSInstalacao = Teste_Util_Tipo_OS.criarTipoOSAutorizado();

                TipoContrato__c tipoContrato = Teste_Util_Tipo_Contrato.criarTipoContratoPadrao();

                WorkOrder OS = Teste_Util_OS.criarOSPadrao(statusPendente.Id);

                Direcionamento_os__c direcionamentoOS = Teste_Util_Direcionamento.criarDirecionamentoOSPadrao();
                Direcionamento_os__c direcionamentoOSPreenchido = Teste_Util_Direcionamento.criarDirecionamentoOSPreenchido(
                                                                statusPendente.Id, tipoContrato.Id, tipoOSInstalacao.Id);
                Profile perfil = Teste_Util_Usuario.getPerfilPorNome('Administrador do Sistema');
                User usuario = Teste_Util_Usuario.criaNovoUsuarioBR(perfil.Id, 'testedaodirecionamento@tt.com', 454654);
                direcionamentoOS.OwnerId = usuario.Id;
                direcionamentoOS.Quantidade_OS__c = 0;
                update direcionamentoOS;

                Profile perfilAtendimento = Teste_Util_Usuario.getPerfilPorNome('Atendimento');
                User usuarioAtendimento = Teste_Util_Usuario.criaNovoUsuarioBR(perfilAtendimento.Id, 'testedaoatendimento@tt.com', 454655);

                Teste_Util_Direcionamento.criarAtendenteDirecionamento(direcionamentoOS.Id, usuarioAtendimento.Id);

                OS.OwnerId = usuarioAtendimento.Id;
                update OS;

                Test.startTest();

                DAO_Ordem_Servico.getListaOS(direcionamentoOS, new List<String>{OS.Cliente__c, OS.Cliente__c});
                DAO_Ordem_Servico.getListaOS(direcionamentoOSPreenchido, new List<String>{OS.Cliente__c, OS.Cliente__c});
                direcionamentoOSPreenchido.Ultima_acao_OS__c = 'Vazio';
                direcionamentoOSPreenchido.Aging_inicial__c = 5;
                direcionamentoOSPreenchido.Aging_final__c = null;
                direcionamentoOSPreenchido.Cliente_KA__c = 'Sim';
                update direcionamentoOSPreenchido;
                DAO_Ordem_Servico.getListaOS(direcionamentoOSPreenchido, new List<String>{OS.Cliente__c, OS.Cliente__c});
                direcionamentoOSPreenchido.Ultima_acao_OS__c = 'Autorizado (O.S.)';
                direcionamentoOSPreenchido.Aging_inicial__c = null;
                direcionamentoOSPreenchido.Aging_final__c = 5;
                direcionamentoOSPreenchido.Cliente_KA__c = 'Não';
                update direcionamentoOSPreenchido;
                DAO_Ordem_Servico.getListaOS(direcionamentoOSPreenchido, new List<String>{OS.Cliente__c, OS.Cliente__c});
                DAO_Ordem_Servico.getListaOsByUser(new Set<Id>{usuarioAtendimento.Id});

                Test.stopTest();
	}
}