force-app/main/default/objects/Historico_Lead__c/Historico_Lead__c.object-meta.xml
<CustomObject>
    <description>Armazena o histórico de contato com o lead.</description>
    <label>Histórico Lead</label>
    <nameField>
        <label>Título</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Histórico Lead</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Historico_Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Historico_Leads_Campo_Descricao</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/CORP.recordType-meta.xml
<RecordType>
    <fullName>CORP</fullName>
    <active>true</active>
    <businessProcess>CORP</businessProcess>
    <label>CORP</label>
</RecordType>

force-app/main/default/classes/HistoricoLead_Teste.cls
@isTest(SeeAllData=true)
public class HistoricoLead_Teste{

    public static testMethod void teste(){
        Map<String, Schema.RecordTypeInfo> recordTypeLead = Lead.SObjectType.getDescribe().getRecordTypeInfosByName();
        
        lead l = new lead();
            l.RecordTypeId = recordTypeLead.get('CORP').getRecordTypeId(); 
            l.LastName = 'teste';
            l.FirstName = 'teste';
            l.Company= 'teste';
            l.Phone = '+55 11 2222 3333';
            l.Email = 'teste@testelead.com.br';
            insert l;
            
            Historico_Lead__c n = new Historico_Lead__c ();
            n.Name = 'teste';
            n.Lead__c = l.Id;
            insert n;
            }
}