force-app/main/default/objects/Historico_Lead__c/Historico_Lead__c.object-meta.xml
<CustomObject>
    <description>Armazena o histórico de contato com o lead.</description>
    <label>Histórico Lead</label>
    <nameField>
        <label>Título</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Histórico Lead</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Historico_Lead__c/fields/Data_da_Alteracao__c.field-meta.xml
<CustomField>
    <fullName>Data_da_Alteracao__c</fullName>
    <label>Data e Hora da Alteracao</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Historico_Lead__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descrição Completa</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Historico_Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Historico_Leads_Campo_Descricao</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Historico_Lead__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário responsável</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Historico_Leads_Campo_Descricao</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DAO_Historico_Lead.cls
/*
	@testClass Teste_DAO_Historico_Lead

	@description DAO para o objeto:

	@author Renan Rocha
	@date 19/11/2018
	@JIRA KCA-9
*/

public class DAO_Historico_Lead{

	private static String CLASS_NAME = 'DAO_Historico_Lead';
	
	/*
		@description 
		@param List<Id> pListaLeadId
		@return List<Historico_Lead__c>
		
		@author Renan Rocha
		@date 19/11/2018
	*/
	public static List<Historico_Lead__c> getHistoricoBySetIdLead(Set<String> pSetLeadId){
		String METHOD_NAME = 'getHistoricoByListaLead';
	
		return
			[SELECT Id
			      , Data_da_Alteracao__c
			      , Descricao__c
			      , Lead__c
			      , Name
			      , Usuario__c
         	FROM Historico_Lead__c
			WHERE Lead__c IN: pSetLeadId];
	}
}