force-app/main/default/objects/ItemPropostaSiggo__c/ItemPropostaSiggo__c.object-meta.xml
<CustomObject>
    <description>Estrutura que descreve os itens de uma proposta</description>
    <label>Veículo</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Veículo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Veículos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ItemPropostaSiggo__c/fields/AnalPrel_CodigoRetorno__c.field-meta.xml
<CustomField>
    <fullName>AnalPrel_CodigoRetorno__c</fullName>
    <description>Recebe o código da cotação de seguro.</description>
    <inlineHelpText>Campo somente leitura - conterá o retorno da cotação de seguro.</inlineHelpText>
    <label>Código de retorno</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ItemPropostaSiggo__c/fields/AnalPrel_MensagemRetorno__c.field-meta.xml
<CustomField>
    <fullName>AnalPrel_MensagemRetorno__c</fullName>
    <description>Recebe a mensagem de retorno da cotação de seguro.</description>
    <inlineHelpText>Campo somente leitura - conterá o retorno da cotação de seguro.</inlineHelpText>
    <label>Mensagem de retorno</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ItemPropostaSiggo__c/fields/AnalPrel_NumeroOrcamento__c.field-meta.xml
<CustomField>
    <fullName>AnalPrel_NumeroOrcamento__c</fullName>
    <description>Recebe o orçamento da cotação de seguro.</description>
    <inlineHelpText>Campo somente leitura - conterá o retorno da cotação de seguro.</inlineHelpText>
    <label>Orçamento</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ItemPropostaSiggo__c/fields/AnalPrel_ValorPremio__c.field-meta.xml
<CustomField>
    <fullName>AnalPrel_ValorPremio__c</fullName>
    <description>Recebe o retorno do prêmio da cotação de seguro.</description>
    <inlineHelpText>Campo somente leitura - conterá o retorno da cotação de seguro.</inlineHelpText>
    <label>Prêmio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ItemPropostaSiggo__c/fields/NumeroContrato__c.field-meta.xml
<CustomField>
    <fullName>NumeroContrato__c</fullName>
    <description>Recebe o número do contrato após geração de termo.</description>
    <inlineHelpText>Campo somente leitura - conterá o retorno do contrato.</inlineHelpText>
    <label>Número do Contrato</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ItemPropostaSiggo__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>ItensPropostaSiggo_Oportunidade</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ItemPropostaSiggo__c/fields/Ordenador__c.field-meta.xml
<CustomField>
    <fullName>Ordenador__c</fullName>
    <description>Campo utilizado para ordernar os itens da proposta porque o serviço da intranet não permite identificar cada um dos itens.</description>
    <label>Ordenador</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/ItemPropostaSiggo__c/fields/StatusContrato__c.field-meta.xml
<CustomField>
    <fullName>StatusContrato__c</fullName>
    <description>Recebe o status do contrato após geração de termo.</description>
    <inlineHelpText>Campo somente leitura - conterá o retorno do contrato.</inlineHelpText>
    <label>Status do Contrato</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DAO_ItemPropostaSiggo.cls
/*
	@testClass Teste_DAO_ItemPropostaSiggo
	
	@description DAO para o objeto:
	
	@author Renan Rocha
	@date 12/12/2018
	@JIRA KCA-10
*/

public class DAO_ItemPropostaSiggo{
	private static String CLASS_NAME = 'DAO_ItemPropostaSiggo';
	
	/*
		@description Retorna um Item de proposta siggo conforme o id da oportunidade
		@param String pOppId
		@return List<ItemPropostaSiggo__c>
		
		@author Renan Rocha
		@date 12/12/2018
		@JIRA KCA-10
	*/
	public static List<ItemPropostaSiggo__c> getItemPropostaByOppId(String pOppId){
		String METHOD_NAME = 'getItemPropostaByOppId';
		
		return
			[SELECT Id
				  , AnalPrel_CodigoRetorno__c
				  , AnalPrel_MensagemRetorno__c
				  , AnalPrel_NumeroOrcamento__c
				  , AnalPrel_ValorPremio__c
			FROM ItemPropostaSiggo__c
			WHERE Oportunidade__c =: pOppId];	
	}

	/*
		@description Retorna um Item de proposta siggo conforme o id da oportunidade
		@param String pOppId, Boolean pNull
		@return List<ItemPropostaSiggo__c>
		
		@author Renan Rocha
		@date 12/12/2018
		@JIRA KCA-10
	*/
	public static List<ItemPropostaSiggo__c> getItemPropostaByOppId(String pOppId, Boolean pNull){
		String METHOD_NAME = 'getItemPropostaByOppId';
		
		return
			[SELECT Id
				  , AnalPrel_CodigoRetorno__c
				  , AnalPrel_MensagemRetorno__c
				  , AnalPrel_NumeroOrcamento__c
				  , AnalPrel_ValorPremio__c
				  , NumeroContrato__c
				  , StatusContrato__c
			FROM ItemPropostaSiggo__c
			WHERE Oportunidade__c =: pOppId
			ORDER BY Ordenador__c ASC NULLS FIRST];	
	}
}