force-app/main/default/objects/Account/fields/A_o_judicial__c.field-meta.xml
<CustomField>
    <fullName>A_o_judicial__c</fullName>
    <label>Ação judicial</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Faturamento_medio_trimestral__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_medio_trimestral__c</fullName>
    <label>Faturamento médio trimestral</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Frota_total_Concorrente_Potencial__c.field-meta.xml
<CustomField>
    <fullName>Frota_total_Concorrente_Potencial__c</fullName>
    <label>Frota Concorrente/Potencial</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Frota_total_Sascar__c.field-meta.xml
<CustomField>
    <fullName>Frota_total_Sascar__c</fullName>
    <label>Frota Sascar</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Principal_concorrente__c.field-meta.xml
<CustomField>
    <fullName>Principal_concorrente__c</fullName>
    <label>Principal concorrente</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Principal_necessidade__c.field-meta.xml
<CustomField>
    <fullName>Principal_necessidade__c</fullName>
    <label>Principal necessidade</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rentabilidade_mensal__c.field-meta.xml
<CustomField>
    <fullName>Rentabilidade_mensal__c</fullName>
    <label>Rentabilidade mensal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rentabilidade_YTD__c.field-meta.xml
<CustomField>
    <fullName>Rentabilidade_YTD__c</fullName>
    <label>Rentabilidade YTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Situacao_financeira__c.field-meta.xml
<CustomField>
    <fullName>Situacao_financeira__c</fullName>
    <label>Situação financeira</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Situacao_sinal__c.field-meta.xml
<CustomField>
    <fullName>Situacao_sinal__c</fullName>
    <label>Situação do sinal</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Frota_Potencial__c/Frota_Potencial__c.object-meta.xml
<CustomObject>
    <label>Frota total do cliente</label>
    <nameField>
        <displayFormat>FP-{0000000000}</displayFormat>
        <label>Frota Potencial</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Frota total do cliente</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Frota_Potencial__c/fields/Concorrente__c.field-meta.xml
<CustomField>
    <fullName>Concorrente__c</fullName>
    <label>Fornecedor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AUTOTRAC</fullName>
            </value>
            <value>
                <fullName>BRIDGESTONE</fullName>
                <isActive>false</isActive>
                <label>BRIDGESTONE</label>
            </value>
            <value>
                <fullName>BYSAT</fullName>
            </value>
            <value>
                <fullName>CARSYSTEM</fullName>
            </value>
            <value>
                <fullName>CEABS</fullName>
            </value>
            <value>
                <fullName>CIELO</fullName>
            </value>
            <value>
                <fullName>CONFORCE</fullName>
            </value>
            <value>
                <fullName>CONTINENTAL</fullName>
                <isActive>false</isActive>
                <label>CONTINENTAL</label>
            </value>
            <value>
                <fullName>CORPVS</fullName>
            </value>
            <value>
                <fullName>FIRESTONE</fullName>
                <isActive>false</isActive>
                <label>FIRESTONE</label>
            </value>
            <value>
                <fullName>GABRER</fullName>
            </value>
            <value>
                <fullName>GOLSAT</fullName>
            </value>
            <value>
                <fullName>GOODYEAR</fullName>
                <isActive>false</isActive>
                <label>GOODYEAR</label>
            </value>
            <value>
                <fullName>ITURAN</fullName>
            </value>
            <value>
                <fullName>LINK</fullName>
            </value>
            <value>
                <fullName>LO JACK</fullName>
            </value>
            <value>
                <fullName>MEGATRANS</fullName>
            </value>
            <value>
                <fullName>MICROTRACK</fullName>
            </value>
            <value>
                <fullName>MINIMAX</fullName>
            </value>
            <value>
                <fullName>MIX</fullName>
            </value>
            <value>
                <fullName>Mix telematics</fullName>
                <isActive>false</isActive>
                <label>Mix telematics</label>
            </value>
            <value>
                <fullName>NÃO POSSUI</fullName>
            </value>
            <value>
                <fullName>Ningun</fullName>
                <isActive>false</isActive>
                <label>Ningun</label>
            </value>
            <value>
                <fullName>Ninguno</fullName>
            </value>
            <value>
                <fullName>OMNILINK</fullName>
            </value>
            <value>
                <fullName>ONIXSAT</fullName>
            </value>
            <value>
                <fullName>OUTROS</fullName>
            </value>
            <value>
                <fullName>PIRELLI</fullName>
                <isActive>false</isActive>
                <label>PIRELLI</label>
            </value>
            <value>
                <fullName>POINTER</fullName>
            </value>
            <value>
                <fullName>PORTO SEGURO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Frota_Potencial__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Frota_Potencial</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Frota_Potencial__c/fields/Necessidade_do_negocio__c.field-meta.xml
<CustomField>
    <fullName>Necessidade_do_negocio__c</fullName>
    <label>Necessidade do negócio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Necessidade_principal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Frota_Potencial__c/fields/Quantidade_de_veiculos__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_de_veiculos__c</fullName>
    <inlineHelpText>Quantidade de veículos</inlineHelpText>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Frota_Sascar__c/Frota_Sascar__c.object-meta.xml
<CustomObject>
    <label>Frota Sascar</label>
    <nameField>
        <displayFormat>PS-{0000000000}</displayFormat>
        <label>Frota Sascar</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Frota Sascar</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Frota_Sascar__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Frota Sascar</relationshipLabel>
    <relationshipName>Frota_Sascar</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Frota_Sascar__c/fields/Quantidade_de_veiculos__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_de_veiculos__c</fullName>
    <label>Quantidade de veículos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Frota_Total__c/Frota_Total__c.object-meta.xml
<CustomObject>
    <label>Frota Total</label>
    <nameField>
        <displayFormat>FT-{0000000000}</displayFormat>
        <label>Frota Total</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Frota Total</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Frota_Total__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Frota Total</relationshipLabel>
    <relationshipName>Frota_Total</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Frota_Total__c/fields/Quantidade_Potencial__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_Potencial__c</fullName>
    <label>Quantidade &quot;Potencial&quot;</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Frota_Total__c/fields/Quantidade_Sascar__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_Sascar__c</fullName>
    <label>Quantidade Sascar</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interacoes__c/Interacoes__c.object-meta.xml
<CustomObject>
    <label>Interação</label>
    <nameField>
        <displayFormat>INT-{000000000}</displayFormat>
        <label>Nome de Interacoes</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interacoes__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Interações</relationshipLabel>
    <relationshipName>Interacoes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Situacao_do_Termo__c/Situacao_do_Termo__c.object-meta.xml
<CustomObject>
    <label>Situação do Termo</label>
    <nameField>
        <displayFormat>ST-{000000000}</displayFormat>
        <label>Nome de Situação do Termo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Situações dos Termos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Situacao_do_Termo__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Situações dos Termos</relationshipLabel>
    <relationshipName>Situacoes_do_Termo</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Situacao_Financeira__c/Situacao_Financeira__c.object-meta.xml
<CustomObject>
    <label>Situação Financeira</label>
    <nameField>
        <displayFormat>SF-{0000000000}</displayFormat>
        <label>Nome de Situação Financeira</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Situação Financeira</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Situacao_Financeira__c/fields/Acao_judicial__c.field-meta.xml
<CustomField>
    <fullName>Acao_judicial__c</fullName>
    <label>Ação judicial</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Situacao_Financeira__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Situação Financeira</relationshipLabel>
    <relationshipName>Situacao_Financeira</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Situacao_Financeira__c/fields/Faturamento_medio_trimestral__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_medio_trimestral__c</fullName>
    <description>Faturamento médio trimestral do cliente</description>
    <label>Faturamento médio trimestral</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Situacao_Financeira__c/fields/Rentabilidade_Mensal__c.field-meta.xml
<CustomField>
    <fullName>Rentabilidade_Mensal__c</fullName>
    <label>Rentabilidade Mensal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Situacao_Financeira__c/fields/Rentabilidade_YTD__c.field-meta.xml
<CustomField>
    <fullName>Rentabilidade_YTD__c</fullName>
    <inlineHelpText>Rentabilidade Year to Date</inlineHelpText>
    <label>Rentabilidade YTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Situacao_Financeira__c/fields/Situacao_Financeira__c.field-meta.xml
<CustomField>
    <fullName>Situacao_Financeira__c</fullName>
    <label>Situação Financeira</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Situacao_Financeira__c/fields/Situacao_sinal__c.field-meta.xml
<CustomField>
    <fullName>Situacao_sinal__c</fullName>
    <label>Situação do sinal</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Veiculos_e_placas__c/Veiculos_e_placas__c.object-meta.xml
<CustomObject>
    <label>Veículos e placas</label>
    <nameField>
        <displayFormat>VP-{0000000000}</displayFormat>
        <label>Nome de Veículos e placas</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Veículos e placas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Veiculos_e_placas__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Veículos e placas</relationshipLabel>
    <relationshipName>Veiculos_e_placas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Necessidade_principal.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Conservação da carga</fullName>
    </customValue>
    <customValue>
        <fullName>Controle de custos</fullName>
    </customValue>
    <customValue>
        <fullName>Cross border</fullName>
    </customValue>
    <customValue>
        <fullName>Gestão de riscos</fullName>
    </customValue>
    <customValue>
        <fullName>Pontualidade</fullName>
    </customValue>
    <customValue>
        <fullName>Prevenção de acidentes</fullName>
    </customValue>
    <customValue>
        <fullName>Produtividade</fullName>
    </customValue>
    <customValue>
        <fullName>Segurança da carga</fullName>
    </customValue>
    <customValue>
        <fullName>Prevenção de acidentes - BT</fullName>
        <isActive>false</isActive>
        <label>Prevenção de acidentes - BT</label>
    </customValue>
    <customValue>
        <fullName>Segurança da carga e veículo</fullName>
        <isActive>false</isActive>
        <label>Segurança da carga e veículo</label>
    </customValue>
    <customValue>
        <fullName>Segurança</fullName>
        <isActive>false</isActive>
        <label>Segurança</label>
    </customValue>
    <customValue>
        <fullName>Produtividade - BT</fullName>
        <isActive>false</isActive>
        <label>Produtividade - BT</label>
    </customValue>
    <customValue>
        <fullName>Controle de custo - BT</fullName>
        <isActive>false</isActive>
        <label>Controle de custo - BT</label>
    </customValue>
    <masterLabel>Necessidade principal</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/ProjetoCRM.cls
public class ProjetoCRM{

    //Atualizando campos da Conta
    //Seção Informações Financeiras
    public static void setInformacoesFinanceirasInAccount(Id accId){
        /*Account acc = new Account();
        acc.Id = accId;
        
        List<Situacao_Financeira__c> sf = [SELECT
                                                Faturamento_medio_trimestral__c,
                                                Situacao_Financeira__c,
                                                Rentabilidade_Mensal__c,
                                                Situacao_sinal__c,
                                                Acao_judicial__c,
                                                Rentabilidade_YTD__c
                                            FROM
                                                Situacao_Financeira__c
                                            WHERE
                                                Conta__c=:accId
                                            ORDER BY CreatedDate DESC LIMIT 1];
        
        if(sf.size() > 0){
            acc.Faturamento_medio_trimestral__c = sf[0].Faturamento_medio_trimestral__c;
            acc.Situacao_financeira__c = sf[0].Situacao_Financeira__c;
            acc.Rentabilidade_mensal__c = sf[0].Rentabilidade_Mensal__c;
            acc.Situacao_sinal__c = sf[0].Situacao_sinal__c;
            acc.A_o_judicial__c = sf[0].Acao_judicial__c;
            acc.Rentabilidade_YTD__c = sf[0].Rentabilidade_YTD__c;
            update acc;
        }*/
    }
    
    //Atualizando campos da Conta
    //Soma total da Frota Sascar e Potencial
    public static void setTotalFrotaInAccount(Id accId){
        Account acc = new Account();
        acc.Id = accId;
        
        List<AggregateResult> total = [SELECT SUM(Quantidade_Sascar__c), SUM(Quantidade_Potencial__c) FROM Frota_Total__c WHERE Conta__c=:acc.Id];
        List<Situacao_Financeira__c> sf = [SELECT
                                                Faturamento_medio_trimestral__c,
                                                Situacao_Financeira__c,
                                                Rentabilidade_Mensal__c,
                                                Situacao_sinal__c,
                                                Acao_judicial__c,
                                                Rentabilidade_YTD__c
                                            FROM
                                                Situacao_Financeira__c
                                            WHERE
                                                Conta__c=:accId
                                            ORDER BY CreatedDate DESC LIMIT 1];
                                                
        List<AggregateResult> fpConcorrente = [SELECT SUM(Quantidade_de_veiculos__c), Concorrente__c FROM Frota_Potencial__c WHERE Conta__c=:accId GROUP BY Concorrente__c ORDER BY SUM(Quantidade_de_veiculos__c) DESC LIMIT 1];
        List<AggregateResult> fpNecessidade = [SELECT SUM(Quantidade_de_veiculos__c), Necessidade_do_negocio__c FROM Frota_Potencial__c WHERE Conta__c=:accId GROUP BY Necessidade_do_negocio__c ORDER BY SUM(Quantidade_de_veiculos__c) DESC LIMIT 1];
        
        system.debug('setTotalFrotaInAccount: '+total);
        system.debug('Situacao_Financeira__c: '+sf);
        
        acc.Frota_total_Sascar__c = Integer.valueOf(total[0].get('expr0'));
        acc.Frota_total_Concorrente_Potencial__c = Integer.valueOf(total[0].get('expr1'));
        
        if(sf.size() > 0){
            acc.Faturamento_medio_trimestral__c = sf[0].Faturamento_medio_trimestral__c;
            acc.Situacao_financeira__c = sf[0].Situacao_Financeira__c;
            acc.Rentabilidade_mensal__c = sf[0].Rentabilidade_Mensal__c;
            acc.Situacao_sinal__c = sf[0].Situacao_sinal__c;
            acc.A_o_judicial__c = sf[0].Acao_judicial__c;
            acc.Rentabilidade_YTD__c = sf[0].Rentabilidade_YTD__c;
        }
        
        if(fpConcorrente.size() > 0){
            acc.Principal_concorrente__c = String.valueOf(fpConcorrente[0].get('Concorrente__c'));
        }
        
        if(fpNecessidade.size() > 0){
            acc.Principal_necessidade__c = String.valueOf(fpNecessidade[0].get('Necessidade_do_negocio__c'));
        }
        
        update acc; 
    }
    
    //Atualiza o total da Frota Potencial no objeto Frota_Total
    //Conforme o tipo de veiculo
    public static void setPotencialInFrotaTotal(Id accId){
        Account acc = new Account();
        acc.Id = accId;
        
        List<AggregateResult> frotaPotencial = [SELECT
                                                        Tipo_de_ve_culo__c, SUM(Quantidade_de_veiculos__c)
                                                    FROM
                                                        Frota_Potencial__c
                                                    WHERE
                                                        Conta__c =: accId
                                                    GROUP BY
                                                        Tipo_de_ve_culo__c
                                                    ORDER BY
                                                        Tipo_de_ve_culo__c ASC];
                                                                
        List<Frota_Total__c> frtotal = [Select Id, Tipo_de_Veiculo__c FROM Frota_Total__c WHERE Conta__c=:accId];        
        Map<String, Id> mapFrotaTotal = new Map<String, Id>();
        
        for(Frota_Total__c a: frtotal){
            mapFrotaTotal.put(String.valueOf(a.Tipo_de_Veiculo__c), a.Id);
        }
                                                                     
        for(AggregateResult fp: frotaPotencial){
            String tipo_veiculo = String.valueOf(fp.get('Tipo_de_ve_culo__c'));
                        
            if(mapFrotaTotal.containsKey(tipo_veiculo)){
                //update
                Frota_Total__c newFrotaTotal = new Frota_Total__c();
                newFrotaTotal.Id = mapFrotaTotal.get(tipo_veiculo);
                newFrotaTotal.Tipo_de_veiculo__c = String.valueOf(fp.get('Tipo_de_ve_culo__c')); //Tipo_de_ve_culo__c;
                newFrotaTotal.Quantidade_Potencial__c = Integer.valueOf(fp.get('expr0')) + 0; //Quantidade_de_veiculos__c;
                update newFrotaTotal;
                
                system.debug('setPotencialInFrotaTotal - update FrotaTotal: ' +newFrotaTotal);
            } else{
                //insert
                Frota_Total__c newFrotaTotal = new Frota_Total__c();
                newFrotaTotal.Tipo_de_veiculo__c = String.valueOf(fp.get('Tipo_de_ve_culo__c')); //Tipo_de_ve_culo__c;
                newFrotaTotal.Id_Cliente__c = acc.Id;
                newFrotaTotal.Conta__c = acc.Id;
                newFrotaTotal.Quantidade_Potencial__c = Integer.valueOf(fp.get('expr0')) + 0; //Quantidade_de_veiculos__c;
                newFrotaTotal.External_Id__c = acc.Id+String.valueOf(fp.get('Tipo_de_ve_culo__c')).toUpperCase();
                
                system.debug('setPotencialInFrotaTotal  - insert newFrotaTotal - PANDA: ' +newFrotaTotal);
                
                insert newFrotaTotal;
            }
        
        }
        
        //Pega a nova lista atualiza
        List<Frota_Total__c> frotaT = [Select Id, Tipo_de_Veiculo__c FROM Frota_Total__c WHERE Conta__c=:accId];
        List<Frota_Potencial__c> frotaPtn = [SELECT Id, Tipo_de_ve_culo__c, Quantidade_de_veiculos__c FROM Frota_Potencial__c WHERE Conta__c =: accId ORDER BY Tipo_de_ve_culo__c ASC];
        List<Frota_Sascar__c> frotaScr = [SELECT Id, Tipo_de_veiculo__c, Quantidade_de_veiculos__c FROM Frota_Sascar__c WHERE Conta__c=:accId ORDER BY Tipo_de_veiculo__c ASC];
                                                                
        Map<String, Integer> mapFrotaP = new Map<String, Integer>();
        Map<String, Integer> mapFrotaS = new Map<String, Integer>();
        
        for(Frota_Potencial__c a: frotaPtn){
            mapFrotaP.put(String.valueOf(a.Tipo_de_ve_culo__c), Integer.valueOf(a.Quantidade_de_veiculos__c));
        }
        
        for(Frota_Sascar__c a: frotaScr){
            mapFrotaS.put(String.valueOf(a.Tipo_de_veiculo__c), Integer.valueOf(a.Quantidade_de_veiculos__c));
        }
        
        //Limpando lixo da Frota Total
        for(Frota_Total__c frT: frotaT){
          if(!mapFrotaP.containsKey(frT.Tipo_de_Veiculo__c) && !mapFrotaS.containsKey(frT.Tipo_de_Veiculo__c)){
            delete frT;
          } else if(mapFrotaP.containsKey(frT.Tipo_de_Veiculo__c) && !mapFrotaS.containsKey(frT.Tipo_de_Veiculo__c)){            
            frT.Quantidade_Sascar__c = 0;
            update frT;
          } else if(!mapFrotaP.containsKey(frT.Tipo_de_Veiculo__c) && mapFrotaS.containsKey(frT.Tipo_de_Veiculo__c)){
            frT.Quantidade_Potencial__c = 0;
            update frT;
          }
        }
        
        //Atualizando campos da Conta
        //Soma total da Frota Sascar e Potencial       
        ProjetoCRM.setTotalFrotaInAccount(accId);
    }
    
    //Atualiza o total da Frota Sascar no objeto Frota_Total
    //Conforme o tipo de veiculo
    public static void setSascarInFrotaTotal(Id accId){
        Account acc = new Account();
        acc.Id = accId;
        
        List<Frota_Sascar__c> frotaSascar = [SELECT
                                                Id, Tipo_de_Veiculo__c, Quantidade_de_veiculos__c
                                            FROM
                                                Frota_Sascar__c
                                            WHERE
                                                Conta__c=:accId
                                            ORDER BY
                                                Tipo_de_Veiculo__c ASC];
                                                                                                   
        system.debug('setSascarInFrotaTotal: '+frotaSascar);
        
        List<Frota_Total__c> frtotal = [Select Id, Tipo_de_Veiculo__c FROM Frota_Total__c WHERE Conta__c=:accId];        
        Map<String, Id> mapFrotaTotal = new Map<String, Id>();
        
        for(Frota_Total__c a: frtotal){
            mapFrotaTotal.put(String.valueOf(a.Tipo_de_Veiculo__c), a.Id);
        }
        
        for(Frota_Sascar__c fs: frotaSascar){            
            //update
            if(mapFrotaTotal.containsKey(fs.Tipo_de_Veiculo__c)){                
                Frota_Total__c newFT = new Frota_Total__c();
                newFT.Id = mapFrotaTotal.get(fs.Tipo_de_Veiculo__c);
                newFT.Quantidade_Sascar__c = fs.Quantidade_de_veiculos__c + 0;
                
                system.debug('setSascarInFrotaTotal - update newFT: ' +newFT);
                
                update newFT;                
            } else{
                //insert
                Frota_Total__c newFrotaTotal = new Frota_Total__c();
                newFrotaTotal.Tipo_de_veiculo__c = fs.Tipo_de_Veiculo__c;
                newFrotaTotal.Id_Cliente__c = acc.Id;
                newFrotaTotal.Conta__c = acc.Id;
                newFrotaTotal.Quantidade_Sascar__c = fs.Quantidade_de_veiculos__c + 0;
                
                system.debug('setSascarInFrotaTotal - insert newFrotaTotal: ' +newFrotaTotal);
                
                insert newFrotaTotal;                
            }        
        }
        
        //Atualizando campos da Conta
        //Soma total da Frota Sascar e Potencial       
        ProjetoCRM.setTotalFrotaInAccount(accId);
    }
    
    //Excluí o registro da Frota Total se não existir na Frota Potencial e na Frota Sascar
    public static void deleteTypesVehicles(Id accId, String tipoVeiculo){
        List<Frota_Total__c> frotaTotal = [SELECT Id, Tipo_de_veiculo__c, Quantidade_Potencial__c, Quantidade_Sascar__c FROM Frota_Total__c WHERE Conta__c=:accId AND Tipo_de_veiculo__c=:tipoVeiculo LIMIT 1];
        
        if(frotaTotal.size() > 0){
            List<Frota_Potencial__c> fp = [SELECT Id, Tipo_de_ve_culo__c FROM Frota_Potencial__c WHERE Conta__c=:accId AND Tipo_de_ve_culo__c=:tipoVeiculo];
            List<Frota_Sascar__c> fs = [SELECT Id, Tipo_de_veiculo__c FROM Frota_Sascar__c WHERE Conta__c=:accId AND Tipo_de_veiculo__c=:tipoVeiculo];
            
            for(Frota_Total__c ft : frotaTotal){
                if(fp.size() == 0 && fs.size() == 0){//Nao existe no potencial e nao existe no sascar
                    delete ft;
                } else if(fp.size() == 0 && fs.size() > 0){//Nao existe no potencial mas existe no sascar
                    ft.Quantidade_Potencial__c = 0;
                    update ft;
                } else if(fp.size() > 0 && fs.size() == 0){//Existe no potencial mas nao existe no sascar
                    ft.Quantidade_Sascar__c = 0;
                    update ft;
                }
            }
        }
    }
    
    //Inserir vazio nos campos Principal concorrente e Principal necessidade
    public static void setBlankInAccountFields(Id accId){
      List<Frota_Potencial__c> frotaP = [SELECT Id, Tipo_de_ve_culo__c FROM Frota_Potencial__c WHERE Conta__c=:accId];
      
      if(frotaP.size() == 0){
        Account acc = new Account();
        acc.Id = accId;
        acc.Principal_concorrente__c = null;
        acc.Principal_necessidade__c = null;
        update acc;
      }
    }
    
    //Vincula os registros que vem do Pentaho do objeto Frota Sascar no objeto Conta
    //Somente antes de inserir
    public static void pentahoUpsertInFrotaSascar(List<Frota_Sascar__c> frota, Boolean bln){
        /*system.debug('pentahoUpsertInFrotaSascar: '+frota);
        
        //before insert - isInsert
        if(bln){
            for(Frota_Sascar__c fs : frota){
                String Id_Cliente = fs.Id_Cliente__c;
                
                if(fs.Id_Cliente__c != ''){                     
                    system.debug('Pentaho: '+Id_Cliente);                
                    fs.Conta__c = fs.Id_Cliente__c;    
                }
            }     
        }*/
    }
    
    //Vincula os registros que vem do Pentaho do objeto Interacoes no objeto Conta
    //Somente antes de inserir
    public static void pentahoUpsertInteracoes(List<Interacoes__c> frota, Boolean bln){
        /*if(bln){
            for(Interacoes__c itc : frota){
                String Id_Cliente = itc.Id_Cliente__c;
                
                if(itc.Id_Cliente__c != ''){                     
                    system.debug('Pentaho: '+itc.Id_Cliente__c);                
                    itc.Conta__c = itc.Id_Cliente__c;    
                }
            }
        }*/
    }
    
    //Vincula os registros que vem do Pentaho do objeto Situacao Financeira no objeto Conta
    //Somente antes de inserir
    public static void pentahoUpsertSituacaoFinanceira(List<Situacao_Financeira__c> frota, Boolean bln){
        /*if(bln){
            for(Situacao_Financeira__c sf : frota){
                String Id_Cliente = sf.Id_Cliente__c;
                
                if(sf.Id_Cliente__c != ''){                     
                    system.debug('Pentaho: '+sf.Id_Cliente__c);                
                    sf.Conta__c = sf.Id_Cliente__c;    
                }
            }
        }*/
    }
    
    //Vincula os registros que vem do Pentaho do objeto Situacao do Termo no objeto Conta
    //Somente antes de inserir
    public static void pentahoUpsertSituacaoTermo(List<Situacao_do_Termo__c> frota, Boolean bln){
        /*if(bln){
            for(Situacao_do_Termo__c st : frota){
                String Id_Cliente = st.Id_Cliente__c;
                
                if(st.Id_Cliente__c != ''){                     
                    system.debug('Pentaho: '+st.Id_Cliente__c);                
                    st.Conta__c = st.Id_Cliente__c;    
                }
            }
        }*/
    }
    
    //Vincula os registros que vem do Pentaho do objeto Veiculoa e Placas no objeto Conta
    //Somente antes de inserir
    public static void pentahoUpsertVeiculosPlacas(List<Veiculos_e_placas__c> frota, Boolean bln){
        /*if(bln){               
            for(Veiculos_e_placas__c vp : frota){
                String Id_Cliente = vp.Id_Cliente__c;
                
                if(vp.Id_Cliente__c != ''){                     
                    system.debug('Pentaho: '+vp.Id_Cliente__c);                
                    vp.Conta__c = vp.Id_Cliente__c;    
                }
            }     
        }*/
    }
    
    //Vincula os registros que vem do Pentaho do objeto Veiculoa e Placas no objeto Conta
    //Somente antes de inserir
    public static void pentahoUpsertSetAccount(List<Frota_Total__c> frota, Boolean bln){
        /*if(bln){               
            for(Frota_Total__c ft : frota){
                String Id_Cliente = ft.Id_Cliente__c;
                
                if(ft.Id_Cliente__c != ''){
                    system.debug('PANDA Pentaho: '+Id_Cliente);             
                    ft.Conta__c = ft.Id_Cliente__c;    
                }
            }     
        }*/
    }
    
    public static void neverCallThisMethod() {
        integer a = 0;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
        a = a + 1;
     }
}