force-app/main/default/objects/Account/fields/Agencia__c.field-meta.xml
<CustomField>
    <fullName>Agencia__c</fullName>
    <label>Agencia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cobranca_Cartao_CodigoSeguranca_Cript__c.field-meta.xml
<CustomField>
    <fullName>Cobranca_Cartao_CodigoSeguranca_Cript__c</fullName>
    <label>Código de Segurança</label>
    <length>3</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cobranca_Cartao_Numero_Cript__c.field-meta.xml
<CustomField>
    <fullName>Cobranca_Cartao_Numero_Cript__c</fullName>
    <description>Campo com o número do Cartão de Crédito na forma Criptografada.</description>
    <label>Número do cartão</label>
    <length>19</length>
    <maskChar>X</maskChar>
    <maskType>creditCard</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cobranca_Cartao_Vcto__c.field-meta.xml
<CustomField>
    <fullName>Cobranca_Cartao_Vcto__c</fullName>
    <label>Vencimento do Cartão (MMAA)</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Física. Especifique o CPF do cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DadosPF_NomeMae__c.field-meta.xml
<CustomField>
    <fullName>DadosPF_NomeMae__c</fullName>
    <description>Quando a conta for uma conta pessoa física, esse campo deve armazernar o nome da mão do cliente.</description>
    <label>Nome da Mãe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DadosPF_RG__c.field-meta.xml
<CustomField>
    <fullName>DadosPF_RG__c</fullName>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Física. Especifique o RG do cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>RG</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DebAut_NomeTitular__c.field-meta.xml
<CustomField>
    <fullName>DebAut_NomeTitular__c</fullName>
    <label>Nome do titular</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EMail__c.field-meta.xml
<CustomField>
    <fullName>EMail__c</fullName>
    <description>Endereço de e-mail para contato com o cliente.</description>
    <inlineHelpText>Para contas do Tipo Pessoa Física, especifique o endereço de e-mail no qual o cliente pode ser encontrado. Para contas do Tipo Pesoal Jurídica, especifique o e-mail de contato comercial da empresa.</inlineHelpText>
    <label>EMail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/EMailNFE__c.field-meta.xml
<CustomField>
    <fullName>EMailNFE__c</fullName>
    <label>EMailNFE</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Cobranca_Bairro__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Cobranca_Bairro__c</fullName>
    <label>Bairro</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Cobranca_Cidade__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Cobranca_Cidade__c</fullName>
    <label>Cidade</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Cobranca_Complemento__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Cobranca_Complemento__c</fullName>
    <label>Complemento</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Cobranca_Logradouro__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Cobranca_Logradouro__c</fullName>
    <label>Logradouro</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Entrega_Bairro__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Entrega_Bairro__c</fullName>
    <label>Bairro</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Entrega_Cidade__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Entrega_Cidade__c</fullName>
    <label>Cidade</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Entrega_Complemento__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Entrega_Complemento__c</fullName>
    <label>Complemento</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Entrega_Logradouro__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Entrega_Logradouro__c</fullName>
    <label>Logradouro</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_Bairro__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_Bairro__c</fullName>
    <label>Bairro</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_Cidade__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_Cidade__c</fullName>
    <label>Cidade</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_Complemento__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_Complemento__c</fullName>
    <label>Complemento</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_Logradouro__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_Logradouro__c</fullName>
    <label>Logradouro</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TelefoneCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefoneCelular__c</fullName>
    <inlineHelpText>Especifique o telefone celular da conta.</inlineHelpText>
    <label>Celular</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/SIGGO.recordType-meta.xml
<RecordType>
    <fullName>SIGGO</fullName>
    <active>true</active>
    <description>Contas relacionadas a SIGGO</description>
    <label>SIGGO</label>
</RecordType>

force-app/main/default/classes/AccountCleanBlankSpaceFields.cls
public class AccountCleanBlankSpaceFields {
	/**
 	 * [MANTIS 7650] - ERRO AO SINCRONIZAR CONTA
 	 * Remove os espaços em brancos dos campos, pois ao enviar com o espaço em branco, o WS_Salesforce
 	 * retorna o seguinte erro: [-1400] String is not in UTF-8. Trigger executada before insert, before update.
 	 * @author Bruno B. Affonso <bruno.bonfim@sascar.com.br>
 	 * @sinze 05/10/2015
 	 */
	public static void cleanBlankSpaceFields(Account acc){
		try{
			//Aplicando .trim() para remover espaços em branco
			//no início e final do texto
			
			//CAMPOS UTILIZADOS NO LAYOUT SIGGO
			if(acc.Name != null) acc.Name = acc.Name.trim();
			if(acc.DadosPF_RG__c != null) acc.DadosPF_RG__c = acc.DadosPF_RG__c.trim();
			if(acc.CPF__c != null) acc.CPF__c = acc.CPF__c.trim();
			if(acc.DadosPF_NomeMae__c != null) acc.DadosPF_NomeMae__c = acc.DadosPF_NomeMae__c.trim();
			if(acc.Phone != null) acc.Phone = acc.Phone.trim();
			if(acc.TelefoneCelular__c != null) acc.TelefoneCelular__c = acc.TelefoneCelular__c.trim();
			if(acc.EMailNFE__c != null) acc.EMailNFE__c = acc.EMailNFE__c.trim();
			if(acc.EMail__c != null) acc.EMail__c = acc.EMail__c.trim();
			if(acc.Enderecos_Cobranca_Logradouro__c != null) acc.Enderecos_Cobranca_Logradouro__c = acc.Enderecos_Cobranca_Logradouro__c.trim();
			if(acc.Enderecos_Entrega_Logradouro__c != null) acc.Enderecos_Entrega_Logradouro__c = acc.Enderecos_Entrega_Logradouro__c.trim();
			if(acc.Enderecos_Principal_Logradouro__c != null) acc.Enderecos_Principal_Logradouro__c = acc.Enderecos_Principal_Logradouro__c.trim();
			if(acc.Enderecos_Cobranca_Complemento__c != null) acc.Enderecos_Cobranca_Complemento__c = acc.Enderecos_Cobranca_Complemento__c.trim();
			if(acc.Enderecos_Entrega_Complemento__c != null) acc.Enderecos_Entrega_Complemento__c = acc.Enderecos_Entrega_Complemento__c.trim();
			if(acc.Enderecos_Principal_Complemento__c != null) acc.Enderecos_Principal_Complemento__c = acc.Enderecos_Principal_Complemento__c.trim();
			if(acc.Enderecos_Cobranca_Bairro__c != null) acc.Enderecos_Cobranca_Bairro__c = acc.Enderecos_Cobranca_Bairro__c.trim();
			if(acc.Enderecos_Entrega_Bairro__c != null) acc.Enderecos_Entrega_Bairro__c = acc.Enderecos_Entrega_Bairro__c.trim();
			if(acc.Enderecos_Principal_Bairro__c != null) acc.Enderecos_Principal_Bairro__c = acc.Enderecos_Principal_Bairro__c.trim();
			if(acc.Enderecos_Cobranca_Cidade__c != null) acc.Enderecos_Cobranca_Cidade__c = acc.Enderecos_Cobranca_Cidade__c.trim();
			if(acc.Enderecos_Entrega_Cidade__c != null) acc.Enderecos_Entrega_Cidade__c = acc.Enderecos_Entrega_Cidade__c.trim();
			if(acc.Enderecos_Principal_Cidade__c != null) acc.Enderecos_Principal_Cidade__c = acc.Enderecos_Principal_Cidade__c.trim();
			if(acc.Cobranca_Cartao_Vcto__c != null) acc.Cobranca_Cartao_Vcto__c = acc.Cobranca_Cartao_Vcto__c.trim();			
			if(acc.Cobranca_Cartao_Numero_Cript__c != null) acc.Cobranca_Cartao_Numero_Cript__c = acc.Cobranca_Cartao_Numero_Cript__c.trim();
			if(acc.Cobranca_Cartao_CodigoSeguranca_Cript__c != null) acc.Cobranca_Cartao_CodigoSeguranca_Cript__c = acc.Cobranca_Cartao_CodigoSeguranca_Cript__c.trim();
			if(acc.Agencia__c != null) acc.Agencia__c = acc.Agencia__c.trim();
			if(acc.DebAut_NomeTitular__c != null) acc.DebAut_NomeTitular__c = acc.DebAut_NomeTitular__c.trim();
			if(acc.Conta__c != null) acc.Conta__c = acc.Conta__c.trim();
										
		} catch(System.NullPointerException e){
			System.debug('Account - NullPointerException: '+ e);
		}
    }
}