force-app/main/default/objects/Account/fields/agregado__c.field-meta.xml
<CustomField>
    <fullName>agregado__c</fullName>
    <label>Possui agregado?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>NÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_UF__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_UF__c</fullName>
    <label>UF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Qual_empresa_esta_agregando__c.field-meta.xml
<CustomField>
    <fullName>Qual_empresa_esta_agregando__c</fullName>
    <label>Qual empresa está agregando ?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/agregado__c.field-meta.xml
<CustomField>
    <fullName>agregado__c</fullName>
    <label>É agregado ?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Não</fullName>
            </value>
            <value>
                <fullName>Sim</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Possui_Escolta_Armada__c.field-meta.xml
<CustomField>
    <fullName>Possui_Escolta_Armada__c</fullName>
    <label>Possui Escolta Armada ?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NÃO</fullName>
            </value>
            <value>
                <fullName>SIM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Qual_empresa_esta_agregando__c.field-meta.xml
<CustomField>
    <fullName>Qual_empresa_esta_agregando__c</fullName>
    <label>Qual empresa está agregando ?</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/CopyFieldLeadToAccount.cls
/**
 * [STI 85892] - Novos campos objeto LEADs e CONTA.
 * @author Bruno B. Affonso <bruno.bonfim@sascar.com.br>
 * @sinze 20/08/2015
 */
public class CopyFieldLeadToAccount {
	
	/**
	 * Copia os dados atualizados do Lead para a Conta.
	 */
	public static void copyFieldLeadToAccount(Lead oldLead, Lead newLead){
		//Verificando se o Lead está convertido
	    if(oldLead.isConverted == false && newLead.isConverted == true){
	        // Verifica se o ID da conta existe, conta existente.
	        if(newLead.ConvertedAccountId != null){
	        	//Recupera informações da Conta.
	            Account accnt = [Select accnt.Possui_Escolta_Armada__c, accnt.agregado__c, accnt.Qual_empresa_esta_agregando__c
	                                From Account accnt
	                                    Where accnt.Id = :newLead.ConvertedAccountId];
	                                    
	            //Recupera informações do Lead                                    
	            Lead lead = [Select lead.state, lead.Possui_Escolta_Armada__c, lead.agregado__c, lead.Qual_empresa_esta_agregando__c
	                            From Lead lead
	                                Where lead.Id = :newLead.Id];
                
                System.debug('Preenchendo campos na conversão. lead: '+lead);
	                                
	            //Atualizando os dados da Conta
	        	accnt.Possui_Escolta_Armada__c = lead.Possui_Escolta_Armada__c;
	            accnt.agregado__c = lead.agregado__c;
	            accnt.Qual_empresa_esta_agregando__c = lead.Qual_empresa_esta_agregando__c;
                accnt.Enderecos_Principal_UF__c = lead.state;
	            update accnt;
	        }
	    }
	}
}