force-app/main/default/objects/Account/fields/agregado__c.field-meta.xml
<CustomField>
    <fullName>agregado__c</fullName>
    <label>Possui agregado?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>NÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Jurídica. Especifique o CNPJ da empresa cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Qual_empresa_esta_agregando__c.field-meta.xml
<CustomField>
    <fullName>Qual_empresa_esta_agregando__c</fullName>
    <label>Qual empresa está agregando ?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/agregado__c.field-meta.xml
<CustomField>
    <fullName>agregado__c</fullName>
    <label>É agregado ?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Não</fullName>
            </value>
            <value>
                <fullName>Sim</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Bairro_endereco__c.field-meta.xml
<CustomField>
    <fullName>Bairro_endereco__c</fullName>
    <label>Bairro endereço</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Complemento_endereco__c.field-meta.xml
<CustomField>
    <fullName>Complemento_endereco__c</fullName>
    <label>Complemento endereço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Numero_endereco__c.field-meta.xml
<CustomField>
    <fullName>Numero_endereco__c</fullName>
    <label>Número endereço</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Qual_empresa_esta_agregando__c.field-meta.xml
<CustomField>
    <fullName>Qual_empresa_esta_agregando__c</fullName>
    <label>Qual empresa está agregando ?</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/LeadConvertTest.cls
@isTest
private class LeadConvertTest {

	public static Lead aLead;

	static{
		alead = new Lead(
			FirstName = 'FirstName',
			LastName = 'LastName',
			CNPJ__c = '88581816000105',
			Company = 'Company Test',
			Description = 'Descrição do Lead',
            Street = 'a',
            City = 'b',
            PostalCode = '09090909',
            Country = 'Brazil',
            Numero_endereco__c = 21,
            Complemento_endereco__c = 'Complementation',
            Bairro_endereco__c = 'Bairralasso',
			agregado__c = 'Não',
			Qual_empresa_esta_agregando__c = 'Empresa teste'
		);
		Insert alead;
	}
	
	@isTest 
	static void testConvertLead() {
		// existe formatacao de CNPJ em lead
		Id accId = LeadConvert.convertLead(alead.Id, '88.581.816/0001-05');
		
		Account acc = [SELECT CNPJ__c FROM Account WHERE Id =: accId];

		// resposta deve ser igual ao CNPJ do Lead
		System.assertEquals('88581816000105', acc.CNPJ__c);
	}
}