force-app/main/default/objects/Account/fields/Cadencia__c.field-meta.xml
<CustomField>
    <fullName>Cadencia__c</fullName>
    <defaultValue>&#39;À planejar&#39;</defaultValue>
    <label>Cadência</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A planejar</fullName>
                <label>À planejar</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Circuito__c.field-meta.xml
<CustomField>
    <fullName>Circuito__c</fullName>
    <defaultValue>&#39;À planejar&#39;</defaultValue>
    <label>Circuito</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A planejar</fullName>
                <label>À planejar</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Jurídica. Especifique o CNPJ da empresa cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJ_CPF__c.field-meta.xml
<CustomField>
    <fullName>CNPJ_CPF__c</fullName>
    <label>CNPJ/CPF</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Física. Especifique o CPF do cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EMail__c.field-meta.xml
<CustomField>
    <fullName>EMail__c</fullName>
    <description>Endereço de e-mail para contato com o cliente.</description>
    <inlineHelpText>Para contas do Tipo Pessoa Física, especifique o endereço de e-mail no qual o cliente pode ser encontrado. Para contas do Tipo Pesoal Jurídica, especifique o e-mail de contato comercial da empresa.</inlineHelpText>
    <label>EMail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/EMailNFE__c.field-meta.xml
<CustomField>
    <fullName>EMailNFE__c</fullName>
    <label>EMailNFE</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Cobranca_Cidade__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Cobranca_Cidade__c</fullName>
    <label>Cidade</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Cobranca_UF__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Cobranca_UF__c</fullName>
    <label>UF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FormaCobranca__c.field-meta.xml
<CustomField>
    <fullName>FormaCobranca__c</fullName>
    <inlineHelpText>Especifique a forma como será realizada a cobrança do serviço de monitoramento.</inlineHelpText>
    <label>Forma de Cobrança</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1-Boleto Bancário</fullName>
            </value>
            <value>
                <fullName>24-Cartão Visa</fullName>
            </value>
            <value>
                <fullName>25-Cartão Mastercard</fullName>
            </value>
            <value>
                <fullName>82-Cartão Hipercard</fullName>
            </value>
            <value>
                <fullName>3-Débito Automático HSBC</fullName>
            </value>
            <value>
                <fullName>4-Débito Automático Itaú</fullName>
            </value>
            <value>
                <fullName>12-Débito Automático Bradesco</fullName>
            </value>
            <value>
                <fullName>13-Débito Automático Banco do Brasil</fullName>
            </value>
            <value>
                <fullName>81-Débito Automático Santander</fullName>
            </value>
            <value>
                <fullName>1- Transferência Bancaria</fullName>
            </value>
            <value>
                <fullName>2 - Débito Automático</fullName>
            </value>
            <value>
                <fullName>3 – Cheque</fullName>
            </value>
            <value>
                <fullName>4 – Pago Fácil</fullName>
            </value>
            <value>
                <fullName>10- Cartãode Crédito Visa</fullName>
            </value>
            <value>
                <fullName>11- Cartão de Crédito American Express</fullName>
            </value>
            <value>
                <fullName>12- Cartão de Crédito MasterCard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Inscri_o_estadual__c.field-meta.xml
<CustomField>
    <fullName>Inscri_o_estadual__c</fullName>
    <label>Inscrição estadual</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nome_contato_autorizado__c.field-meta.xml
<CustomField>
    <fullName>Nome_contato_autorizado__c</fullName>
    <label>Nome contato autorizado</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nome_contato_emergencia__c.field-meta.xml
<CustomField>
    <fullName>Nome_contato_emergencia__c</fullName>
    <label>Nome contato emergência</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nome_contato_instalacao__c.field-meta.xml
<CustomField>
    <fullName>Nome_contato_instalacao__c</fullName>
    <label>Nome contato instalação</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ramo_de_Atividade__c.field-meta.xml
<CustomField>
    <fullName>Ramo_de_Atividade__c</fullName>
    <label>Ramo de Atividade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aeroportos</fullName>
            </value>
            <value>
                <fullName>Agricultura</fullName>
            </value>
            <value>
                <fullName>Alimentos</fullName>
            </value>
            <value>
                <fullName>Alimentos e Bebidas</fullName>
            </value>
            <value>
                <fullName>ASSOCIACAO</fullName>
            </value>
            <value>
                <fullName>AUTOPECAS E COMBUSTIVEIS</fullName>
                <label>AUTOPEÇAS E COMBUSTÍVEIS</label>
            </value>
            <value>
                <fullName>BEBIDAS</fullName>
            </value>
            <value>
                <fullName>Cana de Acucar</fullName>
                <label>Cana de Açúcar</label>
            </value>
            <value>
                <fullName>Carga de Valor</fullName>
            </value>
            <value>
                <fullName>Carga Especial</fullName>
            </value>
            <value>
                <fullName>Carga Expressa</fullName>
            </value>
            <value>
                <fullName>Carga Refrigerada</fullName>
            </value>
            <value>
                <fullName>Carga Seca</fullName>
            </value>
            <value>
                <fullName>Carga Solida</fullName>
                <label>Carga Sólida</label>
            </value>
            <value>
                <fullName>Cargas Quimicas e Perigosas</fullName>
                <label>Cargas Químicas e Perigosas</label>
            </value>
            <value>
                <fullName>Carga Viva</fullName>
            </value>
            <value>
                <fullName>Cegonheiro</fullName>
            </value>
            <value>
                <fullName>CIGARRO</fullName>
            </value>
            <value>
                <fullName>Cimento e Betoneira</fullName>
            </value>
            <value>
                <fullName>Coleta de Lixo</fullName>
            </value>
            <value>
                <fullName>Combustivel</fullName>
                <label>Combustível</label>
            </value>
            <value>
                <fullName>COMERCIO</fullName>
                <label>COMÉRCIO</label>
            </value>
            <value>
                <fullName>Construcao</fullName>
                <label>Construção</label>
            </value>
            <value>
                <fullName>Construcao Civil</fullName>
                <label>Construção Civil</label>
            </value>
            <value>
                <fullName>Container</fullName>
            </value>
            <value>
                <fullName>Corretora</fullName>
            </value>
            <value>
                <fullName>DISTRIBUIDORA</fullName>
            </value>
            <value>
                <fullName>ELETROELETRONICOS</fullName>
                <label>ELETROELETRÔNICOS</label>
            </value>
            <value>
                <fullName>ESCOLAR</fullName>
            </value>
            <value>
                <fullName>EXTRACAO DE MINERIO</fullName>
                <label>EXTRAÇÃO DE MINÉRIO</label>
            </value>
            <value>
                <fullName>Seguradora</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Telefone_2__c.field-meta.xml
<CustomField>
    <fullName>Telefone_2__c</fullName>
    <label>Telefone 2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/TelefoneCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefoneCelular__c</fullName>
    <inlineHelpText>Especifique o telefone celular da conta.</inlineHelpText>
    <label>Celular</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_pessoa__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_pessoa__c</fullName>
    <description>Indica se a conta é uma pessoa física ou jurídica.</description>
    <inlineHelpText>Especifique se a conta descreve uma Pessoa Jurídica (empresa) ou uma Pessoa Física.</inlineHelpText>
    <label>Tipo de pessoa</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>F-Física</fullName>
            </value>
            <value>
                <fullName>J-Jurídica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Argentina.recordType-meta.xml
<RecordType>
    <fullName>Argentina</fullName>
    <active>true</active>
    <label>Argentina</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/CORP.recordType-meta.xml
<RecordType>
    <fullName>CORP</fullName>
    <active>true</active>
    <description>Contas relacionadas ao CORP</description>
    <label>CORP</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/FRETEIRO.recordType-meta.xml
<RecordType>
    <fullName>FRETEIRO</fullName>
    <active>true</active>
    <description>Contas relacionadas a FRETEIROS</description>
    <label>FRETEIRO</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Mercosul.recordType-meta.xml
<RecordType>
    <fullName>Mercosul</fullName>
    <active>true</active>
    <description>Tipo de registro para países do Mercosul, menos Brasil</description>
    <label>Mercosul</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Michelin.recordType-meta.xml
<RecordType>
    <fullName>Michelin</fullName>
    <active>true</active>
    <label>Michelin</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/SIGGO.recordType-meta.xml
<RecordType>
    <fullName>SIGGO</fullName>
    <active>true</active>
    <description>Contas relacionadas a SIGGO</description>
    <label>SIGGO</label>
</RecordType>

force-app/main/default/classes/Teste_Util_Conta.cls
/*
	Criado por: Mario Reis
	Data de criação: 25/08/2017
	Descrição: Classe com métodos para criar registros relacionados a Conta
					para apoio as classes de teste
*/
@isTest
public class Teste_Util_Conta {

	// Método para retornar a conta do tipo Bluetec Pessoa Fisica
    public static Account criaContaBluetecF(String idTipoRegistro, String CPF){

        Account conta = new Account();
		conta.RecordTypeId = idTipoRegistro;
        conta.Type = 'Corretora';
        conta.Name = 'Conta Bluetec teste';
        conta.Nome_fantasia__c = 'Conta Bluetec teste';
        conta.Tipo_de_pessoa__c = 'F-Física';
        conta.Ramo_de_Atividade__c = 'Cegonheiro';
        conta.CPF__c = CPF;
        conta.Circuito__c = '2';
        conta.Cadencia__c = '6';
        conta.TelefoneCelular__c = '(41) 9999-9999';
        conta.Phone = '(41) 9999-9999';
        conta.EMail__c = 'conta@teste.com.br';
        conta.EMailNFE__c = 'conta@teste.com.br';
        conta.Enderecos_Cobranca_UF__c = 'PR';
        conta.Enderecos_Cobranca_Cidade__c = 'Curitiba';

        insert conta;
        return conta;
    } // Fim método criaContaBluetecF


    // Método para retornar a conta do tipo Bluetec Pessoa Juridica
    public static Account criaContaBluetecJ(String idTipoRegistro, String CNPJ){

        Account conta = new Account();
		conta.RecordTypeId = idTipoRegistro;
        conta.Type = 'Corretora';
        conta.Name = 'Conta Bluetec teste';
        conta.Nome_fantasia__c = 'Conta Bluetec teste';
        conta.Tipo_de_pessoa__c = 'J-Jurídica';
        conta.Ramo_de_Atividade__c = 'Cegonheiro';
        conta.CNPJ__c = CNPJ;
        conta.Circuito__c = '2';
        conta.Cadencia__c = '6';
        conta.TelefoneCelular__c = '(41) 9999-9999';
        conta.Phone = '(41) 9999-9999';
        conta.EMail__c = 'conta@teste.com.br';
        conta.EMailNFE__c = 'conta@teste.com.br';
        conta.Enderecos_Cobranca_UF__c = 'PR';
        conta.Enderecos_Cobranca_Cidade__c = 'Curitiba';

        insert conta;
        return conta;
    } // Fim método criaContaBluetecJ


    // Método para retornar a conta do tipo Cargo Tracck Pessoa Fisica
    public static Account criaContaCargoTracckF(String idTipoRegistro, String CPF){

        Account conta = new Account();
		conta.RecordTypeId = idTipoRegistro;
        conta.Type = 'Seguradora';
        conta.Name = 'Conta Cargo Tracck teste';
        conta.Nome_fantasia__c = 'Conta Cargo Tracck teste';
        conta.Tipo_de_pessoa__c = 'F-Física';
        conta.Ramo_de_Atividade__c = 'Aeroportos';
        conta.CPF__c = CPF;
        conta.Cadencia__c = '8';
        conta.TelefoneCelular__c = '(41) 9999-9999';
        conta.Phone = '(41) 9999-9999';
        conta.Telefone_2__c = '(41) 9999-9999';
        conta.EMail__c = 'conta@teste.com.br';
        conta.EMailNFE__c = 'conta@teste.com.br';

        insert conta;
        return conta;
    } // Fim método criaContaCargoTracckF


	// Método para retornar a conta do tipo Cargo Tracck Pessoa Juridica
    public static Account criaContaCargoTracckJ(String idTipoRegistro, String CNPJ){

        Account conta = new Account();
		conta.RecordTypeId = idTipoRegistro;
        conta.Type = 'Seguradora';
        conta.Name = 'Conta Cargo Tracck teste';
        conta.Nome_fantasia__c = 'Conta Cargo Tracck teste';
        conta.Tipo_de_pessoa__c = 'J-Jurídica';
        conta.Ramo_de_Atividade__c = 'Aeroportos';
        conta.CNPJ__c = CNPJ;
        conta.Cadencia__c = '8';
        conta.TelefoneCelular__c = '(41) 9999-9999';
        conta.Phone = '(41) 9999-9999';
        conta.Telefone_2__c = '(41) 9999-9999';
        conta.EMail__c = 'conta@teste.com.br';
        conta.EMailNFE__c = 'conta@teste.com.br';

        insert conta;
        return conta;
    } // Fim método criaContaCargoTracckJ


    // Método para retornar a conta do tipo CORP
    public static Account criaContaCORP(String idTipoRegistro, String CNPJ){

        Account conta = new Account();
		conta.RecordTypeId = idTipoRegistro;
        conta.Type = 'Seguradora';
        conta.Name = 'Conta CORP teste';
        conta.Nome_fantasia__c = 'Conta CORP teste';
        conta.Ramo_de_Atividade__c = 'Cegonheiro';
        conta.CNPJ__c = CNPJ;
        conta.Inscri_o_estadual__c = 'ISENTO';
        conta.TelefoneCelular__c = '(41) 9999-9999';
        conta.Phone = '(41) 9999-9999';
        conta.Telefone_2__c = '(41) 9999-9999';
        conta.Telefone_3__c = '(41) 9999-9999';
        conta.EMail__c = 'conta@teste.com.br';
        conta.EMailNFE__c = 'conta@teste.com.br';
        conta.Circuito__c = '2';
        conta.Cadencia__c = '2';
        
        insert conta;
        return conta;
    } // Fim método criaContaCORP

    
    // Método para retornar a conta do tipo FRETEIRO Pessoa Fisica
    public static Account criaContaFreteiroF(String idTipoRegistro, String CPF){

        Account conta = new Account();
		conta.RecordTypeId = idTipoRegistro;
        conta.Name = 'Conta FRETEIRO teste';
        conta.Nome_fantasia__c = 'Conta FRETEIRO teste';
        conta.Tipo_de_pessoa__c = 'F-Física';
        conta.CNPJ_CPF__c = CPF;
        conta.TelefoneCelular__c = '(41) 9999-9999';
        conta.Phone = '(41) 9999-9999';
        conta.Telefone_2__c = '(41) 9999-9999';
        conta.Telefone_3__c = '(41) 9999-9999';
        conta.EMail__c = 'conta@teste.com.br';
        conta.EMailNFE__c = 'conta@teste.com.br';
        conta.FormaCobranca__c = '1-Boleto Bancário';

        insert conta;
        return conta;
    } // Fim método criaContaFreteiroF


    // Método para retornar a conta do tipo Grupo Economico
    public static Account criaContaGrupoEconomico(String idTipoRegistro, String nome){

        Account conta = new Account();
		conta.RecordTypeId = idTipoRegistro;
        conta.Name = nome;

        insert conta;
        return conta;
    } // Fim método criaContaGrupoEconomico


    // Método para retornar a conta do tipo Michelin
    public static Account criaContaMichelin(String idTipoRegistro, String CNPJ){

        Account conta = new Account();
		conta.RecordTypeId = idTipoRegistro;
        conta.Name = 'Conta Michelin teste';
        conta.Type = 'Indicador';
        conta.CNPJ_CPF__c = CNPJ;
        conta.Phone = '(41) 9999-9999';
        conta.Possui_Escolta_Armada__c = 'SIM';

        insert conta;
        return conta;
    } // Fim método criaContaMichelin


     // Método para retornar a conta do tipo SIGGO Pessoa Fisica
    public static Account criaContaSIGGOF(String idTipoRegistro, String CPF){

        Account conta = new Account();
		conta.RecordTypeId = idTipoRegistro;
        conta.Name = 'Conta SIGGO teste';
        conta.Tipo_de_pessoa__c = 'F-Física';
        conta.CPF__c = CPF;
        conta.Phone = '(41) 9999-9999';
        conta.Nome_contato_autorizado__c = 'Contato autorizado';
		conta.Nome_contato_emergencia__c = 'Contato emergencia';
		conta.Nome_contato_instalacao__c = 'Contato instalacao';
        conta.Enderecos_Principal_UF__c = 'PR';
		conta.Enderecos_Cobranca_UF__c = 'PR';
		conta.FormaCobranca__c = '1-Boleto Bancário';

        insert conta;
        return conta;
    } // Fim método criaContaSIGGOF


    // Método para retornar a conta do tipo Mercosul Pessoa Fisica
    public static Account criaContaArgentinaCUIT(String idTipoRegistro, String CUIT){

        Account conta = new Account();
		conta.RecordTypeId = idTipoRegistro;
        conta.Name = 'Conta Mercosul Argentina';
        conta.Tipo_de_pessoa__c = 'J-Juridica';
        conta.CUIT__c = CUIT;
        conta.Phone = '(41) 9999-9999';
        conta.BillingCountry = 'Argentina';
        conta.Enderecos_Principal_Pais__c = 'Argentina';

        insert conta;
        return conta;
    } // Fim método criaContaSIGGOF

}