force-app/main/default/objects/Account/fields/Cadencia__c.field-meta.xml
<CustomField>
    <fullName>Cadencia__c</fullName>
    <defaultValue>&#39;À planejar&#39;</defaultValue>
    <label>Cadência</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A planejar</fullName>
                <label>À planejar</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Circuito__c.field-meta.xml
<CustomField>
    <fullName>Circuito__c</fullName>
    <defaultValue>&#39;À planejar&#39;</defaultValue>
    <label>Circuito</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A planejar</fullName>
                <label>À planejar</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Jurídica. Especifique o CNPJ da empresa cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountDAOTest.cls
@isTest
private class AccountDAOTest {

	public static Account acc;

	static{

		acc = new Account(
			Name = 'Name',
			CNPJ__c = '71453355000184',
            Circuito__c = '2', 
            Cadencia__c = '2'
		);
		Insert acc;
	}
	
	@isTest 
	static void testGetAccountByCNPJ() {
        
        acc = new Account(
			Name = 'Name',
			CNPJ__c = '71453355000184',
            Circuito__c = '2', 
            Cadencia__c = '2'
		);
		Insert acc;
        System.debug('acc.Id'+acc.Id+'acc.CNPJ__c'+acc.CNPJ__c);
        
		// existe formatacao de CNPJ em Account
		Account conta = new Account();
        conta = AccountDAO.getAccountByCNPJ('71453355000184');
		// existe uppercase em nome de Account
		System.debug('conta'+conta);
		System.assertEquals('NAME', conta.Name);
	}
	
	@isTest 
	static void testAllFields() {
		String fields = AccountDAO.allFields();
		// existe uppercase em nome de Account
		System.assert(fields.contains('Name'));
	}
	
}