force-app/main/default/objects/Account/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo utilizado na conta CT para a identificação dos clientes.</description>
    <label>Clientes Key Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Status_OS__c/Status_OS__c.object-meta.xml
<CustomObject>
    <description>Status das ordens de serviço</description>
    <label>Status da OS</label>
    <nameField>
        <label>Nome do Status da OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Status da OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Status_OS__c/fields/Codigo_Externo__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Externo__c</fullName>
    <description>ID do Status da OS no ERP</description>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Status_OS__c/fields/Pais_Referencia__c.field-meta.xml
<CustomField>
    <fullName>Pais_Referencia__c</fullName>
    <description>Iso no padrão Alpha-3 do país</description>
    <inlineHelpText>Insira a sigla com 3 letras no padrão ISO do país que relativo a este registro</inlineHelpText>
    <label>País de Referência</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DashboardAccountControllerTest.cls
/**************************************************************************************************************
* 
* @author           Ernani href=<ernani.junior.ext@sascar.com>
* Project:          SASCAR
* 
*
* Changes (Version)
* ------------------------------------- 
*           No.     Date            Author                  Desc       		  Sprint
*           -----   ----------      --------------------    ---------------   -------------
* @version   1.0    2018-06-02      Ernani Junior (EJ)      Class created      8     
*************************************************************************************************************/
@isTest
public class DashboardAccountControllerTest 
{
	@isTest
	static void testeClassCalcularData() {

        Account conta = new Account();
        conta.Name = 'teste 1';        
       	insert conta;

        Status_OS__c statusAtorizada = criarStatus('Autorizada','1', true);
        Status_OS__c statusCancelada = criarStatus('Cancelada' ,'2', true);

    	WorkOrder ordem = new WorkOrder();
    	ordem.Cliente__c = 'teste';
        ordem.Status_OS__c = statusAtorizada.id;
        ordem.Codigo_Externo__c = 1234569;
        ordem.StartDate = system.now() -1;
        // ordem.Tipo_macro_OS__c = 'Assistência';
        // ordem.Tipo_micro_OS__c = 'Assistência';
    	insert ordem;
        
        ordem.Status_OS__c = statusCancelada.id;
        update ordem; 
        
        ApexPages.StandardController sc = new ApexPages.StandardController(conta);
        DashboardAccountController controller = new DashboardAccountController(sc);
        
        PageReference pageRef = Page.FilterDashboard;
        pageRef.getParameters().put('id', String.valueOf(conta.Id));
        Test.setCurrentPage(pageRef);
                
    }    
    
    
    
    private static Status_OS__c criarStatus( String NomeStatus, String codigoExterno  , Boolean isInsert) {

        Status_OS__c os = new Status_OS__c();
        
        os.Name = NomeStatus;
        os.Codigo_Externo__c = codigoExterno;
        os.Pais_Referencia__c = 'BR';
        
        if(isInsert){
            insert os;
        }
        
        return os;
    }
}