force-app/main/default/objects/Account/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo utilizado na conta CT para a identificação dos clientes.</description>
    <label>Clientes Key Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CORP.recordType-meta.xml
<RecordType>
    <fullName>CORP</fullName>
    <active>true</active>
    <description>Contas relacionadas ao CORP</description>
    <label>CORP</label>
</RecordType>

force-app/main/default/objects/Direcionamento_os__c/Direcionamento_os__c.object-meta.xml
<CustomObject>
    <label>Direcionamento de OS</label>
    <nameField>
        <label>Descrição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Direcionamentos de OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Direcionamento_os__c/fields/Agendamento_proximo_contato__c.field-meta.xml
<CustomField>
    <fullName>Agendamento_proximo_contato__c</fullName>
    <label>Agendamento próximo contato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Aging_final__c.field-meta.xml
<CustomField>
    <fullName>Aging_final__c</fullName>
    <description>Quantidade de dias do Aging final</description>
    <label>Aging final</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Aging_inicial__c.field-meta.xml
<CustomField>
    <fullName>Aging_inicial__c</fullName>
    <description>Quantidade de dias do Aging inicial</description>
    <label>Aging inicial</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Classe__c.field-meta.xml
<CustomField>
    <fullName>Classe__c</fullName>
    <label>Classe</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACESSÓRIOS CARRETA</fullName>
            </value>
            <value>
                <fullName>BT AEROPORTOS</fullName>
            </value>
            <value>
                <fullName>BT CONSTRUCAO CIVIL</fullName>
            </value>
            <value>
                <fullName>BT Industria - Avançado</fullName>
            </value>
            <value>
                <fullName>BT Industria - Basico</fullName>
            </value>
            <value>
                <fullName>BT Industria - Rental</fullName>
            </value>
            <value>
                <fullName>BT MINA JORNADA</fullName>
            </value>
            <value>
                <fullName>BT MINA PRODUTIVIDADE</fullName>
            </value>
            <value>
                <fullName>BT MINA SEGURANÇA</fullName>
            </value>
            <value>
                <fullName>BT MINERACAO GSM</fullName>
            </value>
            <value>
                <fullName>BT PORTO AVANÇADO</fullName>
            </value>
            <value>
                <fullName>BT PORTO BASICO</fullName>
            </value>
            <value>
                <fullName>CARRETA LOG</fullName>
            </value>
            <value>
                <fullName>CARRETA SOLAR</fullName>
            </value>
            <value>
                <fullName>CCO - GESTÃO AVANÇADA</fullName>
            </value>
            <value>
                <fullName>CCO - GESTÃO AVANÇADA IDENTIFICAÇÃO CAVALO</fullName>
            </value>
            <value>
                <fullName>CCO - GESTAO AVANÇADA (POSICIONAMENTO FREQUENTE)</fullName>
            </value>
            <value>
                <fullName>CCO - GESTÃO AVANÇADA REPETIDORA</fullName>
            </value>
            <value>
                <fullName>CCO - GESTÃO DA PRODUTIVIDADE</fullName>
            </value>
            <value>
                <fullName>CCO - GESTAO DA PRODUTIVIDADE (POSICIONAMENTO FREQUENTE)</fullName>
            </value>
            <value>
                <fullName>CCO - MONITORAMENTO LOGÍSTICO</fullName>
            </value>
            <value>
                <fullName>CCO - MONITORAMENTO LOGÍSTICO (POSICIONAMENTO FREQUENTE)</fullName>
            </value>
            <value>
                <fullName>CELULAR/GSM</fullName>
            </value>
            <value>
                <fullName>EUROPA CARRETA CONECTADA - FRIDGE</fullName>
            </value>
            <value>
                <fullName>EUROPA CARRETA CONECTADA - GEOLOC AND USAGE</fullName>
            </value>
            <value>
                <fullName>EUROPA CARRETA CONECTADA - MAINTENANCE AND SAFETY</fullName>
            </value>
            <value>
                <fullName>EXCLUSIVE LIGHT</fullName>
            </value>
            <value>
                <fullName>FAMILIA GSM</fullName>
            </value>
            <value>
                <fullName>FAMILIA SASMOTO</fullName>
            </value>
            <value>
                <fullName>GESTÃO DE FROTAS - INDONÉSIA</fullName>
            </value>
            <value>
                <fullName>SASCARGA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <description>Nome do cliente</description>
    <inlineHelpText>Nome do cliente</inlineHelpText>
    <label>Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Cliente_KA__c.field-meta.xml
<CustomField>
    <fullName>Cliente_KA__c</fullName>
    <label>Cliente KA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
            <value>
                <fullName>Todos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Data_agendamento_final__c.field-meta.xml
<CustomField>
    <fullName>Data_agendamento_final__c</fullName>
    <label>Data de agendamento final</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Data_agendamento_inicial__c.field-meta.xml
<CustomField>
    <fullName>Data_agendamento_inicial__c</fullName>
    <label>Data de agendamento inicial</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Acessório</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Equipamento</label>
            </value>
            <value>
                <fullName>K</fullName>
                <label>Kit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Motivo__c.field-meta.xml
<CustomField>
    <fullName>Motivo__c</fullName>
    <description>ID&#39;s de Tipo do Item da OS</description>
    <label>Motivo</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Motivo_noshow__c.field-meta.xml
<CustomField>
    <fullName>Motivo_noshow__c</fullName>
    <label>Motivo de noshow</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NOSHOW_CLIENTE</fullName>
            </value>
            <value>
                <fullName>ERRO_AGENDAMENTO</fullName>
            </value>
            <value>
                <fullName>NOSHOW_TECNICO</fullName>
            </value>
            <value>
                <fullName>FALTA_EQUIPAMENTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Numero_OS__c.field-meta.xml
<CustomField>
    <fullName>Numero_OS__c</fullName>
    <description>Número da OS</description>
    <label>Número da OS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/OS_com_agendamento__c.field-meta.xml
<CustomField>
    <fullName>OS_com_agendamento__c</fullName>
    <defaultValue>false</defaultValue>
    <description>OS com agendamento válido</description>
    <label>OS com agendamento</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/OS_sem_acao__c.field-meta.xml
<CustomField>
    <fullName>OS_sem_acao__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OS sem ação</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/OS_sem_agendamento__c.field-meta.xml
<CustomField>
    <fullName>OS_sem_agendamento__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OS sem agendamento</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/OS_sem_agendamento_aging_85_dias__c.field-meta.xml
<CustomField>
    <fullName>OS_sem_agendamento_aging_85_dias__c</fullName>
    <defaultValue>false</defaultValue>
    <description>OS sem agendamento com Aging de 85 dias</description>
    <label>OS sem agendamento Aging 85 dias</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/OS_sem_direcionamento__c.field-meta.xml
<CustomField>
    <fullName>OS_sem_direcionamento__c</fullName>
    <defaultValue>false</defaultValue>
    <description>OS não direcionada para nenhum atendente</description>
    <label>OS sem direcionamento</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/OS_sem_servico__c.field-meta.xml
<CustomField>
    <fullName>OS_sem_servico__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OS sem serviço</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Quantidade_OS__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_OS__c</fullName>
    <label>Quantidade de OS</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Status_OS__c.field-meta.xml
<CustomField>
    <fullName>Status_OS__c</fullName>
    <description>ID&#39;s dos Status da OS</description>
    <label>Status da OS</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Tipo_contrato__c.field-meta.xml
<CustomField>
    <fullName>Tipo_contrato__c</fullName>
    <description>ID&#39;s dos tipos de contrato</description>
    <label>Tipo de contrato</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Direcionamento_os__c/fields/Tipo_OS__c.field-meta.xml
<CustomField>
    <fullName>Tipo_OS__c</fullName>
    <label>Tipo de OS</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Item_ordem_servico__c/Item_ordem_servico__c.object-meta.xml
<CustomObject>
    <label>Item da ordem de serviço</label>
    <nameField>
        <label>Nome do Item da ordem de serviço</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da ordem de serviço</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_ordem_servico__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Acessórios</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Equipamento</label>
            </value>
            <value>
                <fullName>K</fullName>
                <label>Kit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item_ordem_servico__c/fields/Tipo_OS__c.field-meta.xml
<CustomField>
    <fullName>Tipo_OS__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tipo de OS</label>
    <referenceTo>Tipo_OS__c</referenceTo>
    <relationshipLabel>Itens da ordem de serviço</relationshipLabel>
    <relationshipName>Itens_ordem_servico</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Teste_Backlog_OS.cls
/*
    Classe de teste: Teste_Backlog_OS
    Descrição: Classe de Teste para cobertura de:
        Backlog_OS

    Modificado por: Diego Araújo
    Modificado em: 01/06/2018
    Coverage: 71%
*/
@isTest
public class Teste_Backlog_OS {

    @testSetup
    private static void setDataMass(){
        Profile profTest = [Select Id from Profile where Name='Atendimento'][0];

        User uTest = new User(
            FirstName = 'Teste Nome 1',
            LastName = 'Teste Sobrenome 1',            
            Email = 'teste_user_direcionamento@sascar.com.br',
            Username = 'teste_user_direcionamento@sascar.com.br.devprod',
            Alias = 'tnome01',
            CommunityNickname ='tnome01',
            EmailEncodingKey='UTF-8', 
            LanguageLocaleKey='pt_BR',
            LocaleSidKey='pt_BR', 
            ProfileId = profTest.Id,
            TimeZoneSidKey='America/Sao_Paulo',
            IdUsuarioPreCadastro__c = 9998,
            IsActive = true
        );   
        insert uTest;

        Direcionamento_os__c dirOsTest1 = new Direcionamento_os__c(
            Name = 'Teste Direcionamento OS 1', 
            Aging_inicial__c = 12,
            Aging_final__c = 14,
            Numero_OS__c = '01062018',
            Cliente__c = 'Teste Cliente OS 01',
            Classe__c = 'SASCARGA',
            Cliente_KA__c = 'Sim',
            Item__c = 'Equipamento',
            Motivo__c = 'Teste Motivo 01',
            Motivo_noshow__c = 'FALTA_EQUIPAMENTO',
            OS_sem_servico__c = true,
            Quantidade_OS__c = 2,
            OS_sem_direcionamento__c = true,
            OS_com_agendamento__c = true,
            OS_sem_agendamento_aging_85_dias__c = true,
            Agendamento_proximo_contato__c = Date.valueOf(System.today()+7),
            Data_agendamento_inicial__c = Date.valueOf(System.today()),
            Data_agendamento_final__c = Date.valueOf(System.today()+3),
            OS_sem_agendamento__c = true,
            OS_sem_acao__c = true,
            Status_OS__c = 'Teste Status OS 01',
            Tipo_contrato__c = 'Teste Tipo Contrato 01',
            Tipo_OS__c = 'Teste Tipo OS 01',
            Ultima_acao_OS__c = 'Autorizado Instalação',
            Contato_fora_faixa__c = true
        );
        insert dirOsTest1;

        Id rtConta = Schema.SobjectType.Account.getRecordTypeInfosByName().get('CORP').getRecordTypeId();
        Account contaTest1 = new Account(
            Name = 'Teste Cliente 01',
            RecordTypeId = rtConta
        );
        insert contaTest1;

        Contact contatoTest1 = new Contact(
            FirstName = 'Teste Nome Contato 1',
            LastName = 'Teste SobreNome Contato 1',
            Email = 'teste_contato_direcionamento@sascar.com.br',
            AccountId = contaTest1.Id
        );
        insert contatoTest1;

        Status_OS__c statusOsTest1 = new Status_OS__c(
            Codigo_Externo__c = '999998',
            Ativo__c = true,
            Pais_Referencia__c = 'BRA'
        );
        insert statusOsTest1;

        WorkOrder osTest1 = new WorkOrder(
            AccountId = contaTest1.Id,
            ContactId = contatoTest1.Id,
            Codigo_Externo__c = 999998, 
            Cliente__c = 'Cliente Final Teste 01', 
            Status_OS__c = statusOsTest1.Id          
        );
        insert osTest1;

        Item_ordem_servico__c osItem1Test = new Item_ordem_servico__c(
            Ordem_servico__c = osTest1.Id
        );
        insert osItem1Test;
    }

    static testmethod void teste_Backlog_OS() {

        Profile profTest2 = [Select Id from Profile where Name='Atendimento'][0];

        User uTest2 = new User(
            FirstName = 'Teste Nome 2',
            LastName = 'Teste Sobrenome 2',            
            Email = 'teste_user_direcionamento2@sascar.com.br',
            Username = 'teste_user_direcionamento2@sascar.com.br.devprod',
            Alias = 'tnome02',
            CommunityNickname ='tnome02',
            EmailEncodingKey='UTF-8', 
            LanguageLocaleKey='pt_BR',
            LocaleSidKey='pt_BR', 
            ProfileId = profTest2.Id,
            TimeZoneSidKey='America/Sao_Paulo',
            IdUsuarioPreCadastro__c = 9997,
            IsActive = true
        );   
        insert uTest2;

        Direcionamento_os__c dirOsTest2 = new Direcionamento_os__c(
            Name = 'Teste Direcionamento OS 2', 
            Aging_inicial__c = 12,
            Aging_final__c = 14,
            Numero_OS__c = '01062018.2',
            Cliente__c = 'Teste Cliente OS 02',
            Classe__c = 'SASCARGA',
            Cliente_KA__c = 'Sim',
            Item__c = 'Equipamento',
            Motivo__c = 'Teste Motivo 02',
            Motivo_noshow__c = 'FALTA_EQUIPAMENTO',
            OS_sem_servico__c = true,
            Quantidade_OS__c = 2,
            OS_sem_direcionamento__c = true,
            OS_com_agendamento__c = true,
            OS_sem_agendamento_aging_85_dias__c = true,
            Agendamento_proximo_contato__c = Date.valueOf(System.today()+7),
            Data_agendamento_inicial__c = Date.valueOf(System.today()),
            Data_agendamento_final__c = Date.valueOf(System.today()+3),
            OS_sem_agendamento__c = true,
            OS_sem_acao__c = true,
            Status_OS__c = 'Teste Status OS 02',
            Tipo_contrato__c = 'Teste Tipo Contrato 02',
            Tipo_OS__c = 'Teste Tipo OS 02',
            Ultima_acao_OS__c = 'Autorizado Instalação',
            Contato_fora_faixa__c = true
        );
        insert dirOsTest2;
                        
        Backlog_OS.pesquisarOS(JSON.serialize(dirOsTest2));
        Backlog_OS.getListaOS(dirOsTest2);
    }
}