force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Jurídica. Especifique o CNPJ da empresa cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJ_CPF__c.field-meta.xml
<CustomField>
    <fullName>CNPJ_CPF__c</fullName>
    <label>CNPJ/CPF</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Física. Especifique o CPF do cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Cobranca_UF__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Cobranca_UF__c</fullName>
    <label>UF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Entrega_UF__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Entrega_UF__c</fullName>
    <label>UF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_UF__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_UF__c</fullName>
    <label>UF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FormaCobranca__c.field-meta.xml
<CustomField>
    <fullName>FormaCobranca__c</fullName>
    <inlineHelpText>Especifique a forma como será realizada a cobrança do serviço de monitoramento.</inlineHelpText>
    <label>Forma de Cobrança</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1-Boleto Bancário</fullName>
            </value>
            <value>
                <fullName>24-Cartão Visa</fullName>
            </value>
            <value>
                <fullName>25-Cartão Mastercard</fullName>
            </value>
            <value>
                <fullName>82-Cartão Hipercard</fullName>
            </value>
            <value>
                <fullName>3-Débito Automático HSBC</fullName>
            </value>
            <value>
                <fullName>4-Débito Automático Itaú</fullName>
            </value>
            <value>
                <fullName>12-Débito Automático Bradesco</fullName>
            </value>
            <value>
                <fullName>13-Débito Automático Banco do Brasil</fullName>
            </value>
            <value>
                <fullName>81-Débito Automático Santander</fullName>
            </value>
            <value>
                <fullName>1- Transferência Bancaria</fullName>
            </value>
            <value>
                <fullName>2 - Débito Automático</fullName>
            </value>
            <value>
                <fullName>3 – Cheque</fullName>
            </value>
            <value>
                <fullName>4 – Pago Fácil</fullName>
            </value>
            <value>
                <fullName>10- Cartãode Crédito Visa</fullName>
            </value>
            <value>
                <fullName>11- Cartão de Crédito American Express</fullName>
            </value>
            <value>
                <fullName>12- Cartão de Crédito MasterCard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_pessoa__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_pessoa__c</fullName>
    <description>Indica se a conta é uma pessoa física ou jurídica.</description>
    <inlineHelpText>Especifique se a conta descreve uma Pessoa Jurídica (empresa) ou uma Pessoa Física.</inlineHelpText>
    <label>Tipo de pessoa</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>F-Física</fullName>
            </value>
            <value>
                <fullName>J-Jurídica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CORP.recordType-meta.xml
<RecordType>
    <fullName>CORP</fullName>
    <active>true</active>
    <description>Contas relacionadas ao CORP</description>
    <label>CORP</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/FRETEIRO.recordType-meta.xml
<RecordType>
    <fullName>FRETEIRO</fullName>
    <active>true</active>
    <description>Contas relacionadas a FRETEIROS</description>
    <label>FRETEIRO</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/SIGGO.recordType-meta.xml
<RecordType>
    <fullName>SIGGO</fullName>
    <active>true</active>
    <description>Contas relacionadas a SIGGO</description>
    <label>SIGGO</label>
</RecordType>

force-app/main/default/classes/VerificaDuplicidadeTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class VerificaDuplicidadeTest {

    static testMethod void myUnitTestSiggo() {
        //Recuperando o record type name do objeto Conta
	    String recordType = 'Siggo';
	    recordType = recordType.touppercase();
	    
	    Account acct = new Account();	    
	    acct.Name = 'Teste Siggo';
	    acct.Tipo_de_pessoa__c = 'F-Física';
	    acct.CPF__c = '143.759.017-99';
	    acct.RecordTypeId = '01240000000YbfrAAC'; //Siggo desenv
	    acct.Phone = '(41) 3299-6159';
	    acct.FormaCobranca__c = '1-Boleto Bancário';
	    acct.Enderecos_Principal_UF__c = 'PR';
	    acct.Enderecos_Entrega_UF__c = 'PR';
	    acct.Enderecos_Cobranca_UF__c = 'PR';
	    
	    insert acct;
	    
	    Account acct2 = new Account();
	    acct2.Name = 'Teste Siggo';
	    acct2.Tipo_de_pessoa__c = 'F-Física';
	    acct2.CPF__c = '143.759.017-99';
	    acct2.RecordTypeId = '01240000000YbfrAAC'; //Siggo desenv
	    acct2.Phone = '(41) 3299-6159';
	    acct2.FormaCobranca__c = '1-Boleto Bancário';
	    acct2.Enderecos_Principal_UF__c = 'PR';
	    acct2.Enderecos_Entrega_UF__c = 'PR';
	    acct2.Enderecos_Cobranca_UF__c = 'PR';
	    
	    List<Account> TriggerAcc = new List<Account>();
	    TriggerAcc.add(acct2);
	    
	    List<Account> acc = new List<Account>();
	    
	    if(recordType == 'CORP' && TriggerAcc.get(0).CNPJ__c != null){
			//CNPJ__c
			acc = [SELECT
							Id, Name
						FROM
							Account
						WHERE
							CNPJ__c =:TriggerAcc.get(0).CNPJ__c
						AND
							RecordTypeId =:TriggerAcc.get(0).RecordTypeId
						limit 1];
			
			system.debug('VerificaDuplicidade on Account - CORP - acc: '+acc);
			
			if(acc.size() > 0){
				acct2.addError('Duplicidade - Já existe uma conta CORP com o CNPJ informado. Utilize a Conta existente: '+acc[0].Name);
			}
		} else if(recordType == 'FRETEIRO' && TriggerAcc.get(0).CNPJ_CPF__c != null){
			//CNPJ_CPF__c
			acc = [SELECT
							Id, Name
						FROM
							Account
						WHERE
							CNPJ_CPF__c =:TriggerAcc.get(0).CNPJ_CPF__c
						AND
							RecordTypeId =:TriggerAcc.get(0).RecordTypeId
						limit 1];
						
			system.debug('VerificaDuplicidade on Account - FRETEIRO - acc: '+acc);
			
			if(acc.size() > 0){
				acct2.addError('Duplicidade - Já existe uma conta FRETEIRO com o CPF informado. Utilize a Conta existente: '+acc[0].Name);
			}
		} else if(recordType == 'SIGGO' && TriggerAcc.get(0).CPF__c != null){
			//CPF__c
			acc = [SELECT
							Id, Name
						FROM
							Account
						WHERE
							CPF__c =: TriggerAcc.get(0).CPF__c
						AND
							RecordTypeId =:TriggerAcc.get(0).RecordTypeId
						limit 1];
			
			system.debug('VerificaDuplicidade on Account - SIGGO - acc: '+acc);
			
			if(acc.size() > 0){
				acct2.addError('Duplicidade - Já existe uma conta SIGGO com o CPF informado. Utilize a Conta existente: '+acc[0].Name);
			}
		}
        
    }
    
    static testMethod void myUnitTestFreteiro() {
        //Recuperando o record type name do objeto Conta
	    String recordType = 'Freteiro';
	    recordType = recordType.touppercase();
	    
	    Account acct = new Account();	    
	    acct.Name = 'Teste Freteiro';
	    acct.Tipo_de_pessoa__c = 'F-Física';
	    acct.CNPJ_CPF__c = '584.464.342-96';
	    acct.RecordTypeId = '01240000000YbfqAAC'; //Freteiro desenv
	    acct.Phone = '(41) 3299-6159';
	    acct.FormaCobranca__c = '1-Boleto Bancário';
	    acct.Enderecos_Principal_UF__c = 'PR';
	    acct.Enderecos_Entrega_UF__c = 'PR';
	    acct.Enderecos_Cobranca_UF__c = 'PR';
	    
	    insert acct;
	    
	    Account acct2 = new Account();
	    acct2.Name = 'Teste Siggo';
	    acct2.Tipo_de_pessoa__c = 'F-Física';
	    acct2.CNPJ_CPF__c = '584.464.342-96';
	    acct2.RecordTypeId = '01240000000YbfrAAC'; //Freteiro desenv
	    acct2.Phone = '(41) 3299-6159';
	    acct2.FormaCobranca__c = '1-Boleto Bancário';
	    acct2.Enderecos_Principal_UF__c = 'PR';
	    acct2.Enderecos_Entrega_UF__c = 'PR';
	    acct2.Enderecos_Cobranca_UF__c = 'PR';
	    
	    List<Account> TriggerAcc = new List<Account>();
	    TriggerAcc.add(acct2);
	    
	    List<Account> acc = new List<Account>();
	    
	    if(recordType == 'CORP' && TriggerAcc.get(0).CNPJ__c != null){
			//CNPJ__c
			acc = [SELECT
							Id, Name
						FROM
							Account
						WHERE
							CNPJ__c =:TriggerAcc.get(0).CNPJ__c
						AND
							RecordTypeId =:TriggerAcc.get(0).RecordTypeId
						limit 1];
			
			system.debug('VerificaDuplicidade on Account - CORP - acc: '+acc);
			
			if(acc.size() > 0){
				acct2.addError('Duplicidade - Já existe uma conta CORP com o CNPJ informado. Utilize a Conta existente: '+acc[0].Name);
			}
		} else if(recordType == 'FRETEIRO' && TriggerAcc.get(0).CNPJ_CPF__c != null){
			//CNPJ_CPF__c
			acc = [SELECT
							Id, Name
						FROM
							Account
						WHERE
							CNPJ_CPF__c =:TriggerAcc.get(0).CNPJ_CPF__c
						AND
							RecordTypeId =:TriggerAcc.get(0).RecordTypeId
						limit 1];
						
			system.debug('VerificaDuplicidade on Account - FRETEIRO - acc: '+acc);
			
			if(acc.size() > 0){
				acct2.addError('Duplicidade - Já existe uma conta FRETEIRO com o CPF informado. Utilize a Conta existente: '+acc[0].Name);
			}
		} else if(recordType == 'SIGGO' && TriggerAcc.get(0).CPF__c != null){
			//CPF__c
			acc = [SELECT
							Id, Name
						FROM
							Account
						WHERE
							CPF__c =: TriggerAcc.get(0).CPF__c
						AND
							RecordTypeId =:TriggerAcc.get(0).RecordTypeId
						limit 1];
			
			system.debug('VerificaDuplicidade on Account - SIGGO - acc: '+acc);
			
			if(acc.size() > 0){
				acct2.addError('Duplicidade - Já existe uma conta SIGGO com o CPF informado. Utilize a Conta existente: '+acc[0].Name);
			}
		}
        
    }
}