force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Jurídica. Especifique o CNPJ da empresa cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJ_CPF__c.field-meta.xml
<CustomField>
    <fullName>CNPJ_CPF__c</fullName>
    <label>CNPJ/CPF</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Argentina.recordType-meta.xml
<RecordType>
    <fullName>Argentina</fullName>
    <active>true</active>
    <label>Argentina</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/FRETEIRO.recordType-meta.xml
<RecordType>
    <fullName>FRETEIRO</fullName>
    <active>true</active>
    <description>Contas relacionadas a FRETEIROS</description>
    <label>FRETEIRO</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Mercosul.recordType-meta.xml
<RecordType>
    <fullName>Mercosul</fullName>
    <active>true</active>
    <description>Tipo de registro para países do Mercosul, menos Brasil</description>
    <label>Mercosul</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Michelin.recordType-meta.xml
<RecordType>
    <fullName>Michelin</fullName>
    <active>true</active>
    <label>Michelin</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/SIGGO.recordType-meta.xml
<RecordType>
    <fullName>SIGGO</fullName>
    <active>true</active>
    <description>Contas relacionadas a SIGGO</description>
    <label>SIGGO</label>
</RecordType>

force-app/main/default/classes/OpportunityCheckCpfCnpjIsNotEmpty.cls
/**
 * [STI 85949] - [PRJ - SALESFORCE] - VALIDAR CPF/CNPJ OBJETO CONTA E OPORTUNIDADE
 * @author Bruno B. Affonso <bruno.bonfim@sascar.com.br>
 * @sinze 03/09/2015
 */
public class OpportunityCheckCpfCnpjIsNotEmpty{
	
	/**
	 * Verifica se o CPF/CNPJ vinculado a Oportunidade não está em branco.
	 * @author Bruno B. Affonso <bruno.bonfim@sascar.com.br>
	 */
	public static void opportunityCheckCpfCnpjIsNotEmpty(Opportunity oppty, String recordTypeName){
		//Fase
		String fase = oppty.StageName.touppercase();
		
		//Verifica se a Fase foi alterado pra Fechado
		if(fase == 'FECHADO' || fase == 'VENDA FECHADA'){
			//Verificando se existe uma conta vinculada na Oportunidade
			if(oppty.AccountId != null){				
				if(recordTypeName != 'SIGGO' && recordTypeName != 'MICHELIN' 
				&& recordTypeName != 'MEXICO' && recordTypeName != 'MERCOSUL'
				&& recordTypeName != 'ARGENTINA - DEMONSTRAÇÃO'
				&& recordTypeName != 'ARGENTINA'){ //rbsilva 19-06-2018: Essa alteração é necessária por que estão exigindo CPF/CNPJ de quem não tem, as triggers de oportunidades precisam ser revistas. Essa alteração foi feita direto em QA, por que esse tipo de registro (MEXICO) não existe em DEVPROD.
					//Variaveis
					String msg, valor;
					Account accnt = [SELECT CNPJ_CPF__c, CNPJ__c FROM Account WHERE Id =:oppty.AccountId];
				
					if(recordTypeName == 'FRETEIRO'){
						msg = 'Por favor, preencha o CPF na CONTA.';
						valor = accnt.CNPJ_CPF__c;
					} else{
						msg = 'Por favor, preencha o CNPJ na CONTA.';
						valor = accnt.CNPJ__c;
					}
									
					//Verificando se o campo CPF/CNPJ está vazio
					if(valor == null){
						oppty.AccountId.addError(msg);
					}
				}			
			}
		}
	}
}