force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Jurídica. Especifique o CNPJ da empresa cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_municipio_principal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_municipio_principal__c</fullName>
    <label>Código municipio</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_Bairro__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_Bairro__c</fullName>
    <label>Bairro</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_CEP__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_CEP__c</fullName>
    <label>CEP</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_Cidade__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_Cidade__c</fullName>
    <label>Cidade</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_Complemento__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_Complemento__c</fullName>
    <label>Complemento</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_Logradouro__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_Logradouro__c</fullName>
    <label>Logradouro</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_Numero__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_Numero__c</fullName>
    <label>Número</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_UF__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_UF__c</fullName>
    <label>UF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountDAO.cls
public with sharing class AccountDAO {
	
	public AccountDAO() {}
	
    public static Account getAccountByCNPJ(String cnpj) {
		
		String query = 'SELECT ' + allFields() +
			' FROM Account ' + 
			' WHERE CNPJ__c = \'' + cnpj + '\'' +
			' LIMIT 1';
			
		System.debug('***QUERY: '+query);
		
		List<Account> accList = Database.Query(query);
		
		if(accList.isEmpty()){
			return null;
		}
        
        return accList[0];
		
	}
	
	public static String allFields(){
		
		String allFields = 'Enderecos_Principal_CEP__c, Enderecos_Principal_Logradouro__c, Name, ' + 
		'Enderecos_Principal_Cidade__c, Enderecos_Principal_Numero__c, Enderecos_Principal_UF__c, ' + 
		'Enderecos_Principal_Complemento__c, Codigo_municipio_principal__c, Enderecos_Principal_Bairro__c, ' +
		'Description, CNPJ__c';
		
		return allFields;
	}
	
}