force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Jurídica. Especifique o CNPJ da empresa cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cobranca_Cartao_Numero_Cript__c.field-meta.xml
<CustomField>
    <fullName>Cobranca_Cartao_Numero_Cript__c</fullName>
    <description>Campo com o número do Cartão de Crédito na forma Criptografada.</description>
    <label>Número do cartão</label>
    <length>19</length>
    <maskChar>X</maskChar>
    <maskType>creditCard</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Dia_de_vencimento__c.field-meta.xml
<CustomField>
    <fullName>Dia_de_vencimento__c</fullName>
    <description>Campo dependente da forma de pagamento.</description>
    <inlineHelpText>Selecione o dia de vencimento para o monitoramento.</inlineHelpText>
    <label>Dia de vencimento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FormaCobranca__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FormaCobranca__c.field-meta.xml
<CustomField>
    <fullName>FormaCobranca__c</fullName>
    <inlineHelpText>Especifique a forma como será realizada a cobrança do serviço de monitoramento.</inlineHelpText>
    <label>Forma de Cobrança</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1-Boleto Bancário</fullName>
            </value>
            <value>
                <fullName>24-Cartão Visa</fullName>
            </value>
            <value>
                <fullName>25-Cartão Mastercard</fullName>
            </value>
            <value>
                <fullName>82-Cartão Hipercard</fullName>
            </value>
            <value>
                <fullName>3-Débito Automático HSBC</fullName>
            </value>
            <value>
                <fullName>4-Débito Automático Itaú</fullName>
            </value>
            <value>
                <fullName>12-Débito Automático Bradesco</fullName>
            </value>
            <value>
                <fullName>13-Débito Automático Banco do Brasil</fullName>
            </value>
            <value>
                <fullName>81-Débito Automático Santander</fullName>
            </value>
            <value>
                <fullName>1- Transferência Bancaria</fullName>
            </value>
            <value>
                <fullName>2 - Débito Automático</fullName>
            </value>
            <value>
                <fullName>3 – Cheque</fullName>
            </value>
            <value>
                <fullName>4 – Pago Fácil</fullName>
            </value>
            <value>
                <fullName>10- Cartãode Crédito Visa</fullName>
            </value>
            <value>
                <fullName>11- Cartão de Crédito American Express</fullName>
            </value>
            <value>
                <fullName>12- Cartão de Crédito MasterCard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Regional__c.field-meta.xml
<CustomField>
    <fullName>Regional__c</fullName>
    <label>Regional</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>MG-RJ-ES</fullName>
            </value>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>SPC</fullName>
            </value>
            <value>
                <fullName>SPI</fullName>
            </value>
            <value>
                <fullName>Freteiros</fullName>
            </value>
            <value>
                <fullName>KA</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>TELEVENDAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Telefone_2__c.field-meta.xml
<CustomField>
    <fullName>Telefone_2__c</fullName>
    <label>Telefone 2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_cartao__c.field-meta.xml
<CustomField>
    <fullName>Tipo_cartao__c</fullName>
    <label>Tipo do cartão</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Visa</fullName>
            </value>
            <value>
                <fullName>Mastercard</fullName>
            </value>
            <value>
                <fullName>Hipercard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_pessoa__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_pessoa__c</fullName>
    <description>Indica se a conta é uma pessoa física ou jurídica.</description>
    <inlineHelpText>Especifique se a conta descreve uma Pessoa Jurídica (empresa) ou uma Pessoa Física.</inlineHelpText>
    <label>Tipo de pessoa</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>F-Física</fullName>
            </value>
            <value>
                <fullName>J-Jurídica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountBandeiraCartaoTest.cls
@isTest
private class AccountBandeiraCartaoTest {
	//Cartao Visa
	static testMethod void setBandeiraCartaoVisa(){
		test.startTest();
		
		Account acc = new Account();
		acc.Name = 'Cartao Visa';
		acc.Type = 'Novo Cliente';
		acc.CNPJ__c = '08.754.507/0001-42';
		acc.Phone = '(41) 3299-6159';
		acc.Telefone_2__c = '(41) 3299-6159';
		acc.Telefone_2__c = '(41) 3299-6159';
		acc.Regional__c = 'SUL';
		acc.Tipo_de_pessoa__c = 'J-Jurídica';
		acc.Cobranca_Cartao_Numero_Cript__c = '4929221255069033'; //Visa
		
		//Visa
		Pattern pVisa = Pattern.compile('(4[0-9]{12}(?:[0-9]{3}))');
		//Mastercard
		Pattern pMastercard = Pattern.compile('(5[1-5][0-9]{14})');
		//Hipercard
		Pattern pHipercard = Pattern.compile('(606282[0-9]{7,13}|3841[0-9]{9,15})');
	
		if(acc.Cobranca_Cartao_Numero_Cript__c != null){
			//Numero do cartao
			String card = (String) acc.Cobranca_Cartao_Numero_Cript__c;
			
			//Valida no pattern
			Matcher mVisa = pVisa.matcher(card);		
			Matcher mMastercard = pMastercard.matcher(card);		
			Matcher mHipercard = pHipercard.matcher(card);
			
			if(mVisa.matches()){
				acc.Tipo_cartao__c = 'Visa';
				acc.FormaCobranca__c = '24-Cartão Visa';
				acc.Dia_de_vencimento__c = '16';
			} else if(mMastercard.matches()){
				acc.Tipo_cartao__c = 'Mastercard';
				acc.FormaCobranca__c = '25-Cartão Mastercard';
				acc.Dia_de_vencimento__c = '16';
			} else if(mHipercard.matches()){
				acc.Tipo_cartao__c = 'Hipercard';
				acc.FormaCobranca__c = '82-Cartão Hipercard';
				acc.Dia_de_vencimento__c = '16';
			}
		}
		
		insert acc;
		test.stopTest();
	}
	
	//Cartao Mastercard
	static testMethod void setBandeiraCartaoMastercard(){
		test.startTest();
		
		Account acc = new Account();
		acc.Name = 'Cartao Mastercard';
		acc.Type = 'Novo Cliente';
		acc.CNPJ__c = '66.470.705/0001-80';
		acc.Phone = '(41) 3299-6159';
		acc.Telefone_2__c = '(41) 3299-6159';
		acc.Telefone_2__c = '(41) 3299-6159';
		acc.Regional__c = 'SUL';
		acc.Tipo_de_pessoa__c = 'J-Jurídica';
		acc.Cobranca_Cartao_Numero_Cript__c = '5520069124934485'; //Mastercard
		
		//Visa
		Pattern pVisa = Pattern.compile('(4[0-9]{12}(?:[0-9]{3}))');
		//Mastercard
		Pattern pMastercard = Pattern.compile('(5[1-5][0-9]{14})');
		//Hipercard
		Pattern pHipercard = Pattern.compile('(606282[0-9]{7,13}|3841[0-9]{9,15})');
	
		if(acc.Cobranca_Cartao_Numero_Cript__c != null){
			//Numero do cartao
			String card = (String) acc.Cobranca_Cartao_Numero_Cript__c;
			
			//Valida no pattern
			Matcher mVisa = pVisa.matcher(card);		
			Matcher mMastercard = pMastercard.matcher(card);		
			Matcher mHipercard = pHipercard.matcher(card);
			
			if(mVisa.matches()){
				acc.Tipo_cartao__c = 'Visa';
				acc.FormaCobranca__c = '24-Cartão Visa';
				acc.Dia_de_vencimento__c = '16';
			} else if(mMastercard.matches()){
				acc.Tipo_cartao__c = 'Mastercard';
				acc.FormaCobranca__c = '25-Cartão Mastercard';
				acc.Dia_de_vencimento__c = '16';
			} else if(mHipercard.matches()){
				acc.Tipo_cartao__c = 'Hipercard';
				acc.FormaCobranca__c = '82-Cartão Hipercard';
				acc.Dia_de_vencimento__c = '16';
			}
		}
		
		insert acc;
		test.stopTest();
	}
	
	//Cartao Hipercard
	static testMethod void setBandeiraCartaoHipercard(){
		test.startTest();
		
		Account acc = new Account();
		acc.Name = 'Cartao Hipercard';
		acc.Type = 'Novo Cliente';
		acc.CNPJ__c = '36.107.535/0001-03';
		acc.Phone = '(41) 3299-6159';
		acc.Telefone_2__c = '(41) 3299-6159';
		acc.Telefone_2__c = '(41) 3299-6159';
		acc.Regional__c = 'SUL';
		acc.Tipo_de_pessoa__c = 'J-Jurídica';
		//acc.Cobranca_Cartao_Numero_Cript__c = '6062824055364306'; //Hipercard
		acc.Cobranca_Cartao_Numero_Cript__c = '3841001111222233334'; //Hipercard
		
		//Visa
		Pattern pVisa = Pattern.compile('(4[0-9]{12}(?:[0-9]{3}))');
		//Mastercard
		Pattern pMastercard = Pattern.compile('(5[1-5][0-9]{14})');
		//Hipercard
		Pattern pHipercard = Pattern.compile('(606282[0-9]{7,13}|3841[0-9]{9,15})');
	
		if(acc.Cobranca_Cartao_Numero_Cript__c != null){
			//Numero do cartao
			String card = (String) acc.Cobranca_Cartao_Numero_Cript__c;
			
			//Valida no pattern
			Matcher mVisa = pVisa.matcher(card);		
			Matcher mMastercard = pMastercard.matcher(card);		
			Matcher mHipercard = pHipercard.matcher(card);
			
			if(mVisa.matches()){
				acc.Tipo_cartao__c = 'Visa';
				acc.FormaCobranca__c = '24-Cartão Visa';
				acc.Dia_de_vencimento__c = '16';
			} else if(mMastercard.matches()){
				acc.Tipo_cartao__c = 'Mastercard';
				acc.FormaCobranca__c = '25-Cartão Mastercard';
				acc.Dia_de_vencimento__c = '16';
			} else if(mHipercard.matches()){
				acc.Tipo_cartao__c = 'Hipercard';
				acc.FormaCobranca__c = '82-Cartão Hipercard';
				acc.Dia_de_vencimento__c = '16';
			}
		}
		
		insert acc;
		test.stopTest();
	}
}