force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Jurídica. Especifique o CNPJ da empresa cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_municipio_principal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_municipio_principal__c</fullName>
    <label>Código municipio</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Física. Especifique o CPF do cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_Bairro__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_Bairro__c</fullName>
    <label>Bairro</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_CEP__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_CEP__c</fullName>
    <label>CEP</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_Cidade__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_Cidade__c</fullName>
    <label>Cidade</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_Complemento__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_Complemento__c</fullName>
    <label>Complemento</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_Logradouro__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_Logradouro__c</fullName>
    <label>Logradouro</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_Numero__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_Numero__c</fullName>
    <label>Número</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_Pais__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_Pais__c</fullName>
    <label>País</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_UF__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_UF__c</fullName>
    <label>UF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Indicador__c.field-meta.xml
<CustomField>
    <fullName>Indicador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Indicador</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contas relacionadas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Bairro_endereco__c.field-meta.xml
<CustomField>
    <fullName>Bairro_endereco__c</fullName>
    <label>Bairro endereço</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Bairro_sg__c.field-meta.xml
<CustomField>
    <fullName>Bairro_sg__c</fullName>
    <description>Bairro Para integração portal Siggo</description>
    <label>Bairro</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CEP_sg__c.field-meta.xml
<CustomField>
    <fullName>CEP_sg__c</fullName>
    <description>CEP Para integração portal Siggo</description>
    <label>CEP</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Cidade_sg__c.field-meta.xml
<CustomField>
    <fullName>Cidade_sg__c</fullName>
    <description>Cidade Para integração portal Siggo</description>
    <label>Cidade</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Codigo_municipio__c.field-meta.xml
<CustomField>
    <fullName>Codigo_municipio__c</fullName>
    <label>Código municipio</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Complemento_endereco__c.field-meta.xml
<CustomField>
    <fullName>Complemento_endereco__c</fullName>
    <label>Complemento endereço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Complemento_sg__c.field-meta.xml
<CustomField>
    <fullName>Complemento_sg__c</fullName>
    <description>Complemento Para integração portal Siggo</description>
    <label>Complemento</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Indicador__c.field-meta.xml
<CustomField>
    <fullName>Indicador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Indicador</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Logradouro_sg__c.field-meta.xml
<CustomField>
    <fullName>Logradouro_sg__c</fullName>
    <description>Logradouro Para integração portal Siggo</description>
    <label>Logradouro</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Numero_endereco__c.field-meta.xml
<CustomField>
    <fullName>Numero_endereco__c</fullName>
    <label>Número endereço</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Numero_sg__c.field-meta.xml
<CustomField>
    <fullName>Numero_sg__c</fullName>
    <description>Numero Para integração portal Siggo</description>
    <label>Numero</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RG_sg__c.field-meta.xml
<CustomField>
    <fullName>RG_sg__c</fullName>
    <description>RG para Integração com portal Siggo</description>
    <label>RG</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/UF_sg__c.field-meta.xml
<CustomField>
    <fullName>UF_sg__c</fullName>
    <description>UF Para integração portal Siggo</description>
    <label>UF</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadAndAccountMapping.cls
public class LeadAndAccountMapping {
	
	private static final LeadAndAccountMapping instance = new LeadAndAccountMapping();
	
	private LeadAndAccountMapping(){}
	
	public static LeadAndAccountMapping getInstance(){
        return instance;
    }
		
    public Lead accountToLeadMapping(Account acc){
    	
        Lead lead = new Lead();
        
		lead.CEP_sg__c = acc.Enderecos_Principal_CEP__c;
		lead.Logradouro_sg__c = acc.Enderecos_Principal_Logradouro__c;
		lead.Cidade_sg__c = acc.Enderecos_Principal_Cidade__c;
		lead.Numero_sg__c = acc.Enderecos_Principal_Numero__c;
		lead.UF_sg__c = acc.Enderecos_Principal_UF__c;
		lead.Complemento_sg__c = acc.Enderecos_Principal_Complemento__c;
		lead.Codigo_municipio__c = acc.Codigo_municipio_principal__c;
		lead.Bairro_sg__c = acc.Enderecos_Principal_Bairro__c;
		lead.Description = acc.Description;
		lead.CNPJ__c = acc.CNPJ__c;

        return lead;
    }
    
    public Account leadToAccountMapping(Lead lead, Id accId){
    	
        Account acc = new Account(Id = accId);
        
		acc.Enderecos_Principal_CEP__c = lead.PostalCode;
		acc.Enderecos_Principal_Logradouro__c = lead.Street;
		acc.Enderecos_Principal_Cidade__c = lead.City;
		acc.Enderecos_Principal_Numero__c = lead.Numero_endereco__c;
		acc.Enderecos_Principal_UF__c = lead.State;
		acc.Enderecos_Principal_Complemento__c = lead.Complemento_endereco__c;
		acc.Codigo_municipio_principal__c = lead.Codigo_municipio__c;
		acc.Enderecos_Principal_Bairro__c = lead.Bairro_endereco__c;
		acc.Name = buildNameAccount(lead.FirstName, lead.LastName);
		acc.Description = lead.Description;
		acc.Enderecos_Principal_Pais__c = lead.Country;
		acc.CNPJ__c = lead.CNPJ__c;
		acc.Indicador__c = lead.Indicador__c;

        return acc;
    }

    private String buildNameAccount(String firstName, String lastName){
    	return !String.isEmpty(firstName) ? firstName + ' ' + lastName : lastName;
    }
    
    public Contact leadToContactMapping(Lead lead, Id contactId){
    	
    	Contact contato = new Contact(Id = contactId);
    	
    	contato.RG__c = lead.RG_sg__c;
    	contato.CPF__c = lead.CPF__c;
    	contato.FirstName = lead.FirstName;
    	contato.LastName = lead.LastName;
    	
    	return contato;
    }
}