force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Jurídica. Especifique o CNPJ da empresa cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJ_CPF__c.field-meta.xml
<CustomField>
    <fullName>CNPJ_CPF__c</fullName>
    <label>CNPJ/CPF</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Física. Especifique o CPF do cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FormaCobranca__c.field-meta.xml
<CustomField>
    <fullName>FormaCobranca__c</fullName>
    <inlineHelpText>Especifique a forma como será realizada a cobrança do serviço de monitoramento.</inlineHelpText>
    <label>Forma de Cobrança</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1-Boleto Bancário</fullName>
            </value>
            <value>
                <fullName>24-Cartão Visa</fullName>
            </value>
            <value>
                <fullName>25-Cartão Mastercard</fullName>
            </value>
            <value>
                <fullName>82-Cartão Hipercard</fullName>
            </value>
            <value>
                <fullName>3-Débito Automático HSBC</fullName>
            </value>
            <value>
                <fullName>4-Débito Automático Itaú</fullName>
            </value>
            <value>
                <fullName>12-Débito Automático Bradesco</fullName>
            </value>
            <value>
                <fullName>13-Débito Automático Banco do Brasil</fullName>
            </value>
            <value>
                <fullName>81-Débito Automático Santander</fullName>
            </value>
            <value>
                <fullName>1- Transferência Bancaria</fullName>
            </value>
            <value>
                <fullName>2 - Débito Automático</fullName>
            </value>
            <value>
                <fullName>3 – Cheque</fullName>
            </value>
            <value>
                <fullName>4 – Pago Fácil</fullName>
            </value>
            <value>
                <fullName>10- Cartãode Crédito Visa</fullName>
            </value>
            <value>
                <fullName>11- Cartão de Crédito American Express</fullName>
            </value>
            <value>
                <fullName>12- Cartão de Crédito MasterCard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Optante_Simples__c.field-meta.xml
<CustomField>
    <fullName>Optante_Simples__c</fullName>
    <label>Optante Simples</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Regional__c.field-meta.xml
<CustomField>
    <fullName>Regional__c</fullName>
    <label>Regional</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>MG-RJ-ES</fullName>
            </value>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>SPC</fullName>
            </value>
            <value>
                <fullName>SPI</fullName>
            </value>
            <value>
                <fullName>Freteiros</fullName>
            </value>
            <value>
                <fullName>KA</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>TELEVENDAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_pessoa__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_pessoa__c</fullName>
    <description>Indica se a conta é uma pessoa física ou jurídica.</description>
    <inlineHelpText>Especifique se a conta descreve uma Pessoa Jurídica (empresa) ou uma Pessoa Física.</inlineHelpText>
    <label>Tipo de pessoa</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>F-Física</fullName>
            </value>
            <value>
                <fullName>J-Jurídica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/VerificaDuplicidade_3__c.field-meta.xml
<CustomField>
    <fullName>VerificaDuplicidade_3__c</fullName>
    <label>VerificaDuplicidade 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CORP.recordType-meta.xml
<RecordType>
    <fullName>CORP</fullName>
    <active>true</active>
    <description>Contas relacionadas ao CORP</description>
    <label>CORP</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/FRETEIRO.recordType-meta.xml
<RecordType>
    <fullName>FRETEIRO</fullName>
    <active>true</active>
    <description>Contas relacionadas a FRETEIROS</description>
    <label>FRETEIRO</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Michelin.recordType-meta.xml
<RecordType>
    <fullName>Michelin</fullName>
    <active>true</active>
    <label>Michelin</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/SIGGO.recordType-meta.xml
<RecordType>
    <fullName>SIGGO</fullName>
    <active>true</active>
    <description>Contas relacionadas a SIGGO</description>
    <label>SIGGO</label>
</RecordType>

force-app/main/default/objects/Lead/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CNPJ_CPF__c.field-meta.xml
<CustomField>
    <fullName>CNPJ_CPF__c</fullName>
    <label>CNPJ/CPF</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Regional__c.field-meta.xml
<CustomField>
    <fullName>Regional__c</fullName>
    <label>Regional</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>FRETEIRO</fullName>
            </value>
            <value>
                <fullName>KA</fullName>
            </value>
            <value>
                <fullName>MG-RJ-ES</fullName>
            </value>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>SPC</fullName>
            </value>
            <value>
                <fullName>SPI</fullName>
            </value>
            <value>
                <fullName>TELEVENDAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Tipo_de_pessoa__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_pessoa__c</fullName>
    <label>Tipo de pessoa</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>J-Jurídica - MEI</fullName>
            </value>
            <value>
                <fullName>J-Jurídica - ME</fullName>
            </value>
            <value>
                <fullName>F-Física</fullName>
            </value>
            <value>
                <fullName>J-Jurídica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/CORP.recordType-meta.xml
<RecordType>
    <fullName>CORP</fullName>
    <active>true</active>
    <businessProcess>CORP</businessProcess>
    <label>CORP</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Freteiro.recordType-meta.xml
<RecordType>
    <fullName>Freteiro</fullName>
    <active>true</active>
    <businessProcess>Freteiro</businessProcess>
    <label>Freteiro</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Michelin.recordType-meta.xml
<RecordType>
    <fullName>Michelin</fullName>
    <active>true</active>
    <businessProcess>Michelin</businessProcess>
    <description>Piloto Michelin</description>
    <label>Michelin</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Siggo.recordType-meta.xml
<RecordType>
    <fullName>Siggo</fullName>
    <active>true</active>
    <businessProcess>Siggo</businessProcess>
    <label>Siggo</label>
</RecordType>

force-app/main/default/classes/PreencheCampoContaTest.cls
@isTest
private class PreencheCampoContaTest {
    
    static testMethod void Account(){
    
        //CORP
        Map<String, Schema.RecordTypeInfo> tiposRegistro = Account.sObjectType.getDescribe().getRecordTypeInfosByName();
        Account l = new Account();
        l.RecordTypeId = tiposRegistro.get('CORP').getRecordTypeId();
        l.Name = 'Lead';
        l.Phone = '00 0000 0000';
        L.Regional__c = 'Teste';
        insert l;
    
        l.CNPJ__c = '12.403.787/0001-11';
        update l;
    
    
        //SIGGO
        Account le = new Account();
        le.RecordTypeId = tiposRegistro.get('SIGGO').getRecordTypeId();
        le.Name = 'Teste';
        le.Regional__c = 'Teste';
        le.Phone = '00 0000 0000'; 
        le.Tipo_de_pessoa__c = 'F-Física';      
        le.FormaCobranca__c = 'Teste';
        insert le;
    
        le.CPF__c = '690.449.753-07';
        update le;
    
    
        //FRETEIRO
        Account lea = new Account();
        lea.RecordTypeId = tiposRegistro.get('FRETEIRO').getRecordTypeId();
        lea.Name = 'Teste';
        lea.Regional__c = 'Teste';
        lea.Phone = '00 0000 0000';
        lea.Optante_Simples__c = 'Sim';
        lea.Tipo_de_pessoa__c = 'F-Física';
        insert lea;
    
        lea.CNPJ_CPF__c = '313.967.706-58';
        update lea;
        
        
        //MICHELIN
        Account l1 = new Account();
        l1.RecordTypeId = tiposRegistro.get('Michelin').getRecordTypeId();
        l1.Name = 'Teste';
        l1.Regional__c = 'Teste';
        l1.Phone = '00 0000 0000';
        l1.Type = 'Teste';
        insert l1;
    
        l1.CNPJ_CPF__c = '411.333.228-24';
        update l1;
        
        //CARGO TRACCK
        Account ct = new Account();
        ct.RecordTypeId = tiposRegistro.get('Cargo Tracck').getRecordTypeId();
        ct.Name = 'Teste';
        ct.Regional__c = 'Teste';
        ct.Phone = '00 0000 0000';
        ct.Type = 'Teste';
        ct.Tipo_de_pessoa__c = 'J-Jurídica';
        ct.CNPJ__c = '51.040.153/0001-01';
        ct.VerificaDuplicidade_3__c = ct.CNPJ__c + 'Cargo Tracck';
        //ct.CPF__c = null;
        insert ct;
        
        Account ct1 = new Account();
        ct1.RecordTypeId = tiposRegistro.get('Cargo Tracck').getRecordTypeId();
        ct1.Name = 'Teste';
        ct1.Regional__c = 'Teste';
        ct1.Phone = '00 0000 0000';
        ct1.Type = 'Teste';
        ct1.Tipo_de_pessoa__c = 'F-Física';
        ct1.CPF__c = '527.816.515-40';
        ct1.VerificaDuplicidade_3__c = ct1.CPF__c + 'Cargo Tracck';
        ct1.CNPJ__c = null;        
        insert ct1;
    
    }
    
}