force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Jurídica. Especifique o CNPJ da empresa cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContatoEmergencia__c.field-meta.xml
<CustomField>
    <fullName>ContatoEmergencia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato de Emergencia</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contas (Contato de Emergencia)</relationshipLabel>
    <relationshipName>Conta_ContatoEmergencia</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContatoInstalacao__c.field-meta.xml
<CustomField>
    <fullName>ContatoInstalacao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato de Instalação/Assistência</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contas (Contato de Instalação/Assistência)</relationshipLabel>
    <relationshipName>ContaContatoInstalacao</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContatoPadrao__c.field-meta.xml
<CustomField>
    <fullName>ContatoPadrao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato Padrão</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contas (Contato Padrão)</relationshipLabel>
    <relationshipName>Conta_ContatoTodos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContatoPessoaAutorizada__c.field-meta.xml
<CustomField>
    <fullName>ContatoPessoaAutorizada__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pessoa Autorizada</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Física. Especifique o CPF do cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DadosPF_DataNascimento__c.field-meta.xml
<CustomField>
    <fullName>DadosPF_DataNascimento__c</fullName>
    <description>No caso de contas PF, esse campo armazena a data de nascimento do cliente.</description>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Física. Especifique a Data de Nascimento do cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>Data de Nascimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/DadosPF_EstadoCivil__c.field-meta.xml
<CustomField>
    <fullName>DadosPF_EstadoCivil__c</fullName>
    <description>No caso de conta PF, esse campo armazena o estado civil do cliente.</description>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Física. Especifique o Estado Civil (Casado, Solteiro, etc) do cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>Estado Civil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C-Casado</fullName>
            </value>
            <value>
                <fullName>S-Solteiro</fullName>
            </value>
            <value>
                <fullName>V-Viúvo</fullName>
            </value>
            <value>
                <fullName>D-Divorciado</fullName>
            </value>
            <value>
                <fullName>A-Amasiado</fullName>
            </value>
            <value>
                <fullName>O-Outro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DadosPF_NomeMae__c.field-meta.xml
<CustomField>
    <fullName>DadosPF_NomeMae__c</fullName>
    <description>Quando a conta for uma conta pessoa física, esse campo deve armazernar o nome da mão do cliente.</description>
    <label>Nome da Mãe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DadosPF_Sexo__c.field-meta.xml
<CustomField>
    <fullName>DadosPF_Sexo__c</fullName>
    <description>No caso de constas PF, esse campo armazena o sexo do cliente.</description>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Física. Especifique o Sexo do cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M-Masculino</fullName>
            </value>
            <value>
                <fullName>F-Feminino</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DadosPJ_InscricaoEstadual__c.field-meta.xml
<CustomField>
    <fullName>DadosPJ_InscricaoEstadual__c</fullName>
    <description>No caso de contas de cliente PJ, esse campo armazena o número da inscrição estadual.</description>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Jurídica. Especifique a Inscrição Estadual da empresa cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>Inscrição Estadual</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DadosPJ_InscricaoEstadualUF__c.field-meta.xml
<CustomField>
    <fullName>DadosPJ_InscricaoEstadualUF__c</fullName>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Jurídica. Especifique o Estado no qual da empresa cliente possui inscrição estadual.</inlineHelpText>
    <label>Inscrição Estadual UF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DadosPJ_InscricaoMunicipal__c.field-meta.xml
<CustomField>
    <fullName>DadosPJ_InscricaoMunicipal__c</fullName>
    <description>No caso de contas PJ, esse campo deve armazenar a inscrição municipal da empresa cliente.</description>
    <label>Inscrição Municipal</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DebAut_Agencia__c.field-meta.xml
<CustomField>
    <fullName>DebAut_Agencia__c</fullName>
    <label>Agencia</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DebAut_ContaCorrente__c.field-meta.xml
<CustomField>
    <fullName>DebAut_ContaCorrente__c</fullName>
    <label>Conta</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DebAut_NomeTitular__c.field-meta.xml
<CustomField>
    <fullName>DebAut_NomeTitular__c</fullName>
    <label>Nome do titular</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Cobranca_CEP__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Cobranca_CEP__c</fullName>
    <label>CEP</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Cobranca_Numero__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Cobranca_Numero__c</fullName>
    <label>Número</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Entrega_CEP__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Entrega_CEP__c</fullName>
    <label>CEP</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Entrega_Numero__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Entrega_Numero__c</fullName>
    <label>Número</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_CEP__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_CEP__c</fullName>
    <label>CEP</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Enderecos_Principal_Numero__c.field-meta.xml
<CustomField>
    <fullName>Enderecos_Principal_Numero__c</fullName>
    <label>Número</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/FormaCobranca__c.field-meta.xml
<CustomField>
    <fullName>FormaCobranca__c</fullName>
    <inlineHelpText>Especifique a forma como será realizada a cobrança do serviço de monitoramento.</inlineHelpText>
    <label>Forma de Cobrança</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1-Boleto Bancário</fullName>
            </value>
            <value>
                <fullName>24-Cartão Visa</fullName>
            </value>
            <value>
                <fullName>25-Cartão Mastercard</fullName>
            </value>
            <value>
                <fullName>82-Cartão Hipercard</fullName>
            </value>
            <value>
                <fullName>3-Débito Automático HSBC</fullName>
            </value>
            <value>
                <fullName>4-Débito Automático Itaú</fullName>
            </value>
            <value>
                <fullName>12-Débito Automático Bradesco</fullName>
            </value>
            <value>
                <fullName>13-Débito Automático Banco do Brasil</fullName>
            </value>
            <value>
                <fullName>81-Débito Automático Santander</fullName>
            </value>
            <value>
                <fullName>1- Transferência Bancaria</fullName>
            </value>
            <value>
                <fullName>2 - Débito Automático</fullName>
            </value>
            <value>
                <fullName>3 – Cheque</fullName>
            </value>
            <value>
                <fullName>4 – Pago Fácil</fullName>
            </value>
            <value>
                <fullName>10- Cartãode Crédito Visa</fullName>
            </value>
            <value>
                <fullName>11- Cartão de Crédito American Express</fullName>
            </value>
            <value>
                <fullName>12- Cartão de Crédito MasterCard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TelefoneCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefoneCelular__c</fullName>
    <inlineHelpText>Especifique o telefone celular da conta.</inlineHelpText>
    <label>Celular</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/TelefoneComercial__c.field-meta.xml
<CustomField>
    <fullName>TelefoneComercial__c</fullName>
    <label>Telefone Comercial</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_pessoa__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_pessoa__c</fullName>
    <description>Indica se a conta é uma pessoa física ou jurídica.</description>
    <inlineHelpText>Especifique se a conta descreve uma Pessoa Jurídica (empresa) ou uma Pessoa Física.</inlineHelpText>
    <label>Tipo de pessoa</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>F-Física</fullName>
            </value>
            <value>
                <fullName>J-Jurídica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/SIGGO.recordType-meta.xml
<RecordType>
    <fullName>SIGGO</fullName>
    <active>true</active>
    <description>Contas relacionadas a SIGGO</description>
    <label>SIGGO</label>
</RecordType>

force-app/main/default/classes/PCL_AccountProcessTest.cls
@isTest
private class PCL_AccountProcessTest {

    public static Account createAccount() {
        Account acc = new Account();
        acc.TelefoneCelular__c = '(11) 9876-5432';
        acc.Phone = '(11) 9876-5432';
        acc.Name = 'Teste';
        acc.TelefoneComercial__c = '(11) 6785-4567';
        return acc;
    }
    
    public static Contact createContact() {
        Contact contato = new Contact();
        contato.LastName = 'Teste';
        contato.RG__c = '123456789';
        //contato.CPF__c = '12345678909';
        contato.Phone = '(11) 9876-5432';
        contato.HomePhone = '(11) 9876-5432';
        contato.MobilePhone = '(11) 9876-5432';
        contato.Email = 'teste@teste.com.br';
        return contato;
    }
    
    static testMethod void myUnitTest() {
        //Conta e Contato PF
        Account accPF = createAccount();
        accPF.Tipo_de_pessoa__c = 'F-Física';
        //accPF.CPF__c = '66236667373';
        accPF.DadosPF_NomeMae__c = 'Mamãe';
        accPF.DadosPF_Sexo__c = 'M-Masculino';
        accPF.DadosPF_DataNascimento__c = date.today().addYears(-20);
        accPF.DadosPF_EstadoCivil__c = 'S-Solteiro';
        accPF.FormaCobranca__c = '4-Débito Automático Itaú';
        accPF.DebAut_Agencia__c = 1234;
        accPF.DebAut_ContaCorrente__c = 123451;
        accPF.DebAut_NomeTitular__c = 'New Account';
        //accPF.Enderecos_Principal_CEP__c = '12345999';
        accPF.Enderecos_Principal_Numero__c = 1000;
        //accPF.Enderecos_Cobranca_CEP__c = '12345999';
        accPF.Enderecos_Cobranca_Numero__c = 1000;
        //accPF.Enderecos_Entrega_CEP__c = '12345999';
        accPF.Enderecos_Entrega_Numero__c = 1000;
        insert accPF;
        
        Contact contatoPF = createContact();
        contatoPF.AccountId = accPF.Id;
        insert contatoPF;
        
        //Conta e Contato PJ
        Account accPJ = createAccount();
        accPJ.Tipo_de_pessoa__c = 'J-Jurídica';
        //accPJ.CNPJ__c = '80116451000128';
        accPJ.Nome_fantasia__c = 'New Account';
        accPJ.DadosPJ_InscricaoMunicipal__c = 'Isento';
        accPJ.DadosPJ_InscricaoEstadualUF__c = 'Isento';
        accPJ.DadosPJ_InscricaoEstadual__c = 'Isento';
        accPJ.FormaCobranca__c = '4-Débito Automático Itaú';
        accPJ.DebAut_Agencia__c = 1234;
        accPJ.DebAut_ContaCorrente__c = 123451;
        accPJ.DebAut_NomeTitular__c = 'New Account';
        //accPJ.Enderecos_Principal_CEP__c = '12345999';
        accPJ.Enderecos_Principal_Numero__c = 1000;
        //accPJ.Enderecos_Cobranca_CEP__c = '12345999';
        accPJ.Enderecos_Cobranca_Numero__c = 1000;
        //accPJ.Enderecos_Entrega_CEP__c = '12345999';
        accPJ.Enderecos_Entrega_Numero__c = 1000;
        insert accPJ;
        
        Contact contatoPJ = createContact();
        contatoPJ.AccountId = accPJ.Id;
        insert contatoPJ;
        
        accPJ.ContatoPessoaAutorizada__c = contatoPJ.Id;
        accPJ.ContatoPadrao__c = contatoPJ.Id;
        accPJ.ContatoInstalacao__c = contatoPJ.Id;
        accPJ.ContatoEmergencia__c = contatoPJ.Id;
        update accPJ;
        
        PCL_AccountProcess pcl = new PCL_AccountProcess();
        pcl.validationAccountToCore(accPF.Id);
        pcl.validationAccountToCore(accPJ.Id);
        
        accPJ.Tipo_de_pessoa__c = 'J-Jurídica';
        update accPJ;
        /* SEFO comentado para implantação das demandas da Siggo
        Operacao__c op1 = new Operacao__c();
        op1.Name = 'Teste';
        op1.ContaPai__c = accPJ.Id;
        op1.Conta_Entrega__c = accPJ.Id;
        op1.ID_Operacao_CT__c = 299;
        insert op1;
        
        Endereco__c e1 = new Endereco__c();
        e1.Operacao__c = op1.Id;
        e1.Endereco_Principal__c = true;
        e1.CEP__c = '12345-999';
        e1.UF__c = 'SP';
        e1.Cidade__c = 'Teste';
        e1.Bairro__c = 'Teste';
        e1.Logradouro__c = 'Teste';
        e1.Numero__c = 1000;
        e1.Complemento__c = 'Apto A';
        insert e1;
        
        Operacao__c op2 = new Operacao__c();
        op2.Name = 'Teste';
        op2.ContaPai__c = accPF.Id;
        op2.Conta_Entrega__c = accPF.Id;
        op2.ID_Operacao_CT__c = 299;
        insert op2;
        
        Endereco__c e2 = new Endereco__c();
        e2.Operacao__c = op2.Id;
        e2.Endereco_Principal__c = true;
        e2.CEP__c = '12345-999';
        e2.UF__c = 'SP';
        e2.Cidade__c = 'Teste';
        e2.Bairro__c = 'Teste';
        e2.Logradouro__c = 'Teste';
        e2.Numero__c = 1000;
        e2.Complemento__c = 'Apto A';
        insert e2;
        */
        pcl.validationAccountToCore(accPF.Id);
        pcl.validationAccountToCore(accPJ.Id);
        
        accPF.DadosPF_NomeMae__c = 'Mae Teste';
        accPF.DadosPF_Sexo__c = 'M-Masculino';
        accPF.DadosPF_DataNascimento__c = date.today().addYears(-20);
        accPF.DadosPF_EstadoCivil__c = 'S-Solteiro';
        accPF.DadosPF_RG__c = '432996781';
        update accPF;
        
        pcl.sendAccountToCore(accPF.Id);
        pcl.sendAccountToCore(accPJ.Id);
        
        
         PCL_AccountProcess.neverCallThisMethod();
        
    }
}