force-app/main/default/objects/Account/fields/Cobranca_Cartao_CodigoSeguranca_Cript__c.field-meta.xml
<CustomField>
    <fullName>Cobranca_Cartao_CodigoSeguranca_Cript__c</fullName>
    <label>Código de Segurança</label>
    <length>3</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cobranca_Cartao_Numero_Cript__c.field-meta.xml
<CustomField>
    <fullName>Cobranca_Cartao_Numero_Cript__c</fullName>
    <description>Campo com o número do Cartão de Crédito na forma Criptografada.</description>
    <label>Número do cartão</label>
    <length>19</length>
    <maskChar>X</maskChar>
    <maskType>creditCard</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cobranca_Cartao_Vcto__c.field-meta.xml
<CustomField>
    <fullName>Cobranca_Cartao_Vcto__c</fullName>
    <label>Vencimento do Cartão (MMAA)</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContatoEmergencia__c.field-meta.xml
<CustomField>
    <fullName>ContatoEmergencia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato de Emergencia</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contas (Contato de Emergencia)</relationshipLabel>
    <relationshipName>Conta_ContatoEmergencia</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContatoInstalacao__c.field-meta.xml
<CustomField>
    <fullName>ContatoInstalacao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato de Instalação/Assistência</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contas (Contato de Instalação/Assistência)</relationshipLabel>
    <relationshipName>ContaContatoInstalacao</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContatoPadrao__c.field-meta.xml
<CustomField>
    <fullName>ContatoPadrao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato Padrão</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contas (Contato Padrão)</relationshipLabel>
    <relationshipName>Conta_ContatoTodos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContatoPessoaAutorizada__c.field-meta.xml
<CustomField>
    <fullName>ContatoPessoaAutorizada__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pessoa Autorizada</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Física. Especifique o CPF do cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DadosPF_DataNascimento__c.field-meta.xml
<CustomField>
    <fullName>DadosPF_DataNascimento__c</fullName>
    <description>No caso de contas PF, esse campo armazena a data de nascimento do cliente.</description>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Física. Especifique a Data de Nascimento do cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>Data de Nascimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/DadosPF_EstadoCivil__c.field-meta.xml
<CustomField>
    <fullName>DadosPF_EstadoCivil__c</fullName>
    <description>No caso de conta PF, esse campo armazena o estado civil do cliente.</description>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Física. Especifique o Estado Civil (Casado, Solteiro, etc) do cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>Estado Civil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C-Casado</fullName>
            </value>
            <value>
                <fullName>S-Solteiro</fullName>
            </value>
            <value>
                <fullName>V-Viúvo</fullName>
            </value>
            <value>
                <fullName>D-Divorciado</fullName>
            </value>
            <value>
                <fullName>A-Amasiado</fullName>
            </value>
            <value>
                <fullName>O-Outro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DadosPF_NomeMae__c.field-meta.xml
<CustomField>
    <fullName>DadosPF_NomeMae__c</fullName>
    <description>Quando a conta for uma conta pessoa física, esse campo deve armazernar o nome da mão do cliente.</description>
    <label>Nome da Mãe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DadosPF_RG__c.field-meta.xml
<CustomField>
    <fullName>DadosPF_RG__c</fullName>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Física. Especifique o RG do cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>RG</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DadosPF_Sexo__c.field-meta.xml
<CustomField>
    <fullName>DadosPF_Sexo__c</fullName>
    <description>No caso de constas PF, esse campo armazena o sexo do cliente.</description>
    <inlineHelpText>Obrigatório somente para contas do tipo Pessoa Física. Especifique o Sexo do cliente para que ele possa ser cadastrado na intranet.</inlineHelpText>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M-Masculino</fullName>
            </value>
            <value>
                <fullName>F-Feminino</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DebAut_Agencia__c.field-meta.xml
<CustomField>
    <fullName>DebAut_Agencia__c</fullName>
    <label>Agencia</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DebAut_ContaCorrente__c.field-meta.xml
<CustomField>
    <fullName>DebAut_ContaCorrente__c</fullName>
    <label>Conta</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DebAut_NomeTitular__c.field-meta.xml
<CustomField>
    <fullName>DebAut_NomeTitular__c</fullName>
    <label>Nome do titular</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FormaCobranca__c.field-meta.xml
<CustomField>
    <fullName>FormaCobranca__c</fullName>
    <inlineHelpText>Especifique a forma como será realizada a cobrança do serviço de monitoramento.</inlineHelpText>
    <label>Forma de Cobrança</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1-Boleto Bancário</fullName>
            </value>
            <value>
                <fullName>24-Cartão Visa</fullName>
            </value>
            <value>
                <fullName>25-Cartão Mastercard</fullName>
            </value>
            <value>
                <fullName>82-Cartão Hipercard</fullName>
            </value>
            <value>
                <fullName>3-Débito Automático HSBC</fullName>
            </value>
            <value>
                <fullName>4-Débito Automático Itaú</fullName>
            </value>
            <value>
                <fullName>12-Débito Automático Bradesco</fullName>
            </value>
            <value>
                <fullName>13-Débito Automático Banco do Brasil</fullName>
            </value>
            <value>
                <fullName>81-Débito Automático Santander</fullName>
            </value>
            <value>
                <fullName>1- Transferência Bancaria</fullName>
            </value>
            <value>
                <fullName>2 - Débito Automático</fullName>
            </value>
            <value>
                <fullName>3 – Cheque</fullName>
            </value>
            <value>
                <fullName>4 – Pago Fácil</fullName>
            </value>
            <value>
                <fullName>10- Cartãode Crédito Visa</fullName>
            </value>
            <value>
                <fullName>11- Cartão de Crédito American Express</fullName>
            </value>
            <value>
                <fullName>12- Cartão de Crédito MasterCard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TelefoneCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefoneCelular__c</fullName>
    <inlineHelpText>Especifique o telefone celular da conta.</inlineHelpText>
    <label>Celular</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/TelefoneComercial__c.field-meta.xml
<CustomField>
    <fullName>TelefoneComercial__c</fullName>
    <label>Telefone Comercial</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_pessoa__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_pessoa__c</fullName>
    <description>Indica se a conta é uma pessoa física ou jurídica.</description>
    <inlineHelpText>Especifique se a conta descreve uma Pessoa Jurídica (empresa) ou uma Pessoa Física.</inlineHelpText>
    <label>Tipo de pessoa</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>F-Física</fullName>
            </value>
            <value>
                <fullName>J-Jurídica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/SIGGO.recordType-meta.xml
<RecordType>
    <fullName>SIGGO</fullName>
    <active>true</active>
    <description>Contas relacionadas a SIGGO</description>
    <label>SIGGO</label>
</RecordType>

force-app/main/default/classes/PCL_AccountParserTest.cls
@isTest
private class PCL_AccountParserTest {

    public static Account createAccount() {
        Account acc = new Account();
        acc.TelefoneCelular__c = '1198765432';
        acc.Phone = '1198765432';
        acc.Name = 'Teste';
        acc.TelefoneComercial__c = '1167854567';
        return acc;
    }
    
    public static Contact createContact() {
        Contact contato = new Contact();
        contato.LastName = 'Teste';
        contato.RG__c = '123456789';
        contato.CPF__c = '12345678909';
        contato.Phone = '1167854567';
        contato.HomePhone = '1167854567';
        contato.MobilePhone = '1198765432';
        contato.Email = 'teste@teste.com.br';
        return contato;
    }
    
    static testMethod void myUnitTest() {
        //Conta e Contato PF
        Account accPF = createAccount();
        accPF.Tipo_de_pessoa__c = 'F-Física';
        accPF.DadosPF_NomeMae__c = 'Mae Teste';
        accPF.DadosPF_Sexo__c = 'M-Masculino';
        accPF.DadosPF_DataNascimento__c = date.today().addYears(-20);
        accPF.DadosPF_EstadoCivil__c = 'S-Solteiro';
        accPF.DadosPF_RG__c = '432996781';
        insert accPF;
        
        Contact contatoPF = createContact();
        contatoPF.AccountId = accPF.Id;
        insert contatoPF;
        
        //Conta e Contato PJ
        Account accPJ = createAccount();
        accPJ.Tipo_de_pessoa__c = 'J-Jurídica';
        insert accPJ;
        
        Contact contatoPJ = createContact();
        contatoPJ.AccountId = accPJ.Id;
        insert contatoPJ;
        
        accPJ.ContatoPessoaAutorizada__c = contatoPJ.Id;
        accPJ.ContatoPadrao__c = contatoPJ.Id;
        accPJ.ContatoInstalacao__c = contatoPJ.Id;
        accPJ.ContatoEmergencia__c = contatoPJ.Id;
        update accPJ;
        /*SEFO Comentado para implantação das demandas da Siggo
        Operacao__c op = new Operacao__c();
        op.Name = 'Teste';
        op.ContaPai__c = accPJ.Id;
        op.Conta_Entrega__c = accPJ.Id;
        insert op;
        
        Endereco__c e = new Endereco__c();
        e.Operacao__c = op.Id;
        e.Endereco_Principal__c = true;
        e.CEP__c = '12345-999';
        e.UF__c = 'SP';
        e.Cidade__c = 'Teste';
        e.Bairro__c = 'Teste';
        e.Logradouro__c = 'Teste';
        e.Numero__c = 1000;
        e.Complemento__c = 'Apto A';
        insert e;
        */
        PCL_AccountParser pcl = new PCL_AccountParser();
        pcl.toExternalObject(accPF);
        pcl.toExternalObject(accPJ);
        
        accPJ.FormaCobranca__c = '3-Débito Automático HSBC';
        accPJ.DebAut_Agencia__c = 1234;
        accPJ.DebAut_ContaCorrente__c = 123456;
        accPJ.DebAut_NomeTitular__c = 'Teste';
        update accPJ;
        pcl.toExternalObject(accPJ);
        
        accPJ.FormaCobranca__c = '4-Débito Automático Itaú';
        update accPJ;
        pcl.toExternalObject(accPJ);
        
        accPJ.FormaCobranca__c = '12-Débito Automático Bradesco';
        update accPJ;
        pcl.toExternalObject(accPJ);
        
        accPJ.FormaCobranca__c = '13-Débito Automático Banco do Brasil';
        update accPJ;
        pcl.toExternalObject(accPJ);
        
        accPJ.FormaCobranca__c = '80-Débito Automático Santander';
        update accPJ;
        pcl.toExternalObject(accPJ);
        
        accPJ.FormaCobranca__c = '24-Cartão Visa';
        accPJ.Cobranca_Cartao_Numero_Cript__c = '1111222233334444';
        accPJ.Cobranca_Cartao_CodigoSeguranca_Cript__c = '123';
        accPJ.Cobranca_Cartao_Vcto__c = '0150';
        update accPJ;
        pcl.toExternalObject(accPJ);
        
        accPJ.FormaCobranca__c = '25-Cartão Mastercard';
        update accPJ;
        pcl.toExternalObject(accPJ);
        
        accPJ.FormaCobranca__c = '82-Cartão Hipercard';
        update accPJ;
        pcl.toExternalObject(accPJ);
        
        //PCL_AccountParser.neverCallThisMethod();
    }
}