force-app/main/default/objects/Account/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Faturamento_medio_trimestral__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_medio_trimestral__c</fullName>
    <label>Faturamento médio trimestral</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Frota_Sascar__c.field-meta.xml
<CustomField>
    <fullName>Frota_Sascar__c</fullName>
    <formula>Frota_total_Sascar__c / Tamanho_da_Frota__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>% Frota Sascar</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rentabilidade_mensal__c.field-meta.xml
<CustomField>
    <fullName>Rentabilidade_mensal__c</fullName>
    <label>Rentabilidade mensal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Situacao_financeira__c.field-meta.xml
<CustomField>
    <fullName>Situacao_financeira__c</fullName>
    <label>Situação financeira</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CORP.recordType-meta.xml
<RecordType>
    <fullName>CORP</fullName>
    <active>true</active>
    <description>Contas relacionadas ao CORP</description>
    <label>CORP</label>
</RecordType>

force-app/main/default/objects/Frota_Potencial__c/Frota_Potencial__c.object-meta.xml
<CustomObject>
    <label>Frota total do cliente</label>
    <nameField>
        <displayFormat>FP-{0000000000}</displayFormat>
        <label>Frota Potencial</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Frota total do cliente</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Frota_Potencial__c/fields/Concorrente__c.field-meta.xml
<CustomField>
    <fullName>Concorrente__c</fullName>
    <label>Fornecedor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AUTOTRAC</fullName>
            </value>
            <value>
                <fullName>BRIDGESTONE</fullName>
                <isActive>false</isActive>
                <label>BRIDGESTONE</label>
            </value>
            <value>
                <fullName>BYSAT</fullName>
            </value>
            <value>
                <fullName>CARSYSTEM</fullName>
            </value>
            <value>
                <fullName>CEABS</fullName>
            </value>
            <value>
                <fullName>CIELO</fullName>
            </value>
            <value>
                <fullName>CONFORCE</fullName>
            </value>
            <value>
                <fullName>CONTINENTAL</fullName>
                <isActive>false</isActive>
                <label>CONTINENTAL</label>
            </value>
            <value>
                <fullName>CORPVS</fullName>
            </value>
            <value>
                <fullName>FIRESTONE</fullName>
                <isActive>false</isActive>
                <label>FIRESTONE</label>
            </value>
            <value>
                <fullName>GABRER</fullName>
            </value>
            <value>
                <fullName>GOLSAT</fullName>
            </value>
            <value>
                <fullName>GOODYEAR</fullName>
                <isActive>false</isActive>
                <label>GOODYEAR</label>
            </value>
            <value>
                <fullName>ITURAN</fullName>
            </value>
            <value>
                <fullName>LINK</fullName>
            </value>
            <value>
                <fullName>LO JACK</fullName>
            </value>
            <value>
                <fullName>MEGATRANS</fullName>
            </value>
            <value>
                <fullName>MICROTRACK</fullName>
            </value>
            <value>
                <fullName>MINIMAX</fullName>
            </value>
            <value>
                <fullName>MIX</fullName>
            </value>
            <value>
                <fullName>Mix telematics</fullName>
                <isActive>false</isActive>
                <label>Mix telematics</label>
            </value>
            <value>
                <fullName>NÃO POSSUI</fullName>
            </value>
            <value>
                <fullName>Ningun</fullName>
                <isActive>false</isActive>
                <label>Ningun</label>
            </value>
            <value>
                <fullName>Ninguno</fullName>
            </value>
            <value>
                <fullName>OMNILINK</fullName>
            </value>
            <value>
                <fullName>ONIXSAT</fullName>
            </value>
            <value>
                <fullName>OUTROS</fullName>
            </value>
            <value>
                <fullName>PIRELLI</fullName>
                <isActive>false</isActive>
                <label>PIRELLI</label>
            </value>
            <value>
                <fullName>POINTER</fullName>
            </value>
            <value>
                <fullName>PORTO SEGURO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Frota_Potencial__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Frota_Potencial</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Frota_Potencial__c/fields/Nivel_de_relacionamento__c.field-meta.xml
<CustomField>
    <fullName>Nivel_de_relacionamento__c</fullName>
    <label>Relacionamento com concorrente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Excelente</fullName>
            </value>
            <value>
                <fullName>Ótimo</fullName>
            </value>
            <value>
                <fullName>Muito bom</fullName>
            </value>
            <value>
                <fullName>Bom</fullName>
            </value>
            <value>
                <fullName>Razoável</fullName>
            </value>
            <value>
                <fullName>Ruim</fullName>
            </value>
            <value>
                <fullName>Péssimo</fullName>
            </value>
            <value>
                <fullName>Sem relacionamento</fullName>
            </value>
            <value>
                <fullName>Não tem relação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Frota_Potencial__c/fields/Quantidade_de_veiculos__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_de_veiculos__c</fullName>
    <inlineHelpText>Quantidade de veículos</inlineHelpText>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Frota_Potencial__c/fields/Tipo_de_ve_culo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_ve_culo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_veiculo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Frota_Potencial__c/recordTypes/CORP.recordType-meta.xml
<RecordType>
    <fullName>CORP</fullName>
    <active>true</active>
    <label>CORP</label>
</RecordType>

force-app/main/default/objects/Frota_Sascar__c/Frota_Sascar__c.object-meta.xml
<CustomObject>
    <label>Frota Sascar</label>
    <nameField>
        <displayFormat>PS-{0000000000}</displayFormat>
        <label>Frota Sascar</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Frota Sascar</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Frota_Sascar__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Frota Sascar</relationshipLabel>
    <relationshipName>Frota_Sascar</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Frota_Sascar__c/fields/Quantidade_de_veiculos__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_de_veiculos__c</fullName>
    <label>Quantidade de veículos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Frota_Sascar__c/fields/Tipo_de_veiculo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_veiculo__c</fullName>
    <label>Tipo de veículo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Frota_Total__c/Frota_Total__c.object-meta.xml
<CustomObject>
    <label>Frota Total</label>
    <nameField>
        <displayFormat>FT-{0000000000}</displayFormat>
        <label>Frota Total</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Frota Total</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Frota_Total__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Frota Total</relationshipLabel>
    <relationshipName>Frota_Total</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Frota_Total__c/fields/Id_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Id_Cliente__c</fullName>
    <label>Id Cliente</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Frota_Total__c/fields/Quantidade_Potencial__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_Potencial__c</fullName>
    <label>Quantidade &quot;Potencial&quot;</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Frota_Total__c/fields/Tipo_de_veiculo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_veiculo__c</fullName>
    <label>Tipo de veículo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interacoes__c/Interacoes__c.object-meta.xml
<CustomObject>
    <label>Interação</label>
    <nameField>
        <displayFormat>INT-{000000000}</displayFormat>
        <label>Nome de Interacoes</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interacoes__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Interações</relationshipLabel>
    <relationshipName>Interacoes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Interacoes__c/fields/Id_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Id_Cliente__c</fullName>
    <label>Id Cliente</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Situacao_do_Termo__c/Situacao_do_Termo__c.object-meta.xml
<CustomObject>
    <label>Situação do Termo</label>
    <nameField>
        <displayFormat>ST-{000000000}</displayFormat>
        <label>Nome de Situação do Termo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Situações dos Termos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Situacao_do_Termo__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Situações dos Termos</relationshipLabel>
    <relationshipName>Situacoes_do_Termo</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Situacao_do_Termo__c/fields/Id_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Id_Cliente__c</fullName>
    <description>ID da conta no CRM</description>
    <label>Id Cliente</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Situacao_Financeira__c/Situacao_Financeira__c.object-meta.xml
<CustomObject>
    <label>Situação Financeira</label>
    <nameField>
        <displayFormat>SF-{0000000000}</displayFormat>
        <label>Nome de Situação Financeira</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Situação Financeira</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Situacao_Financeira__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Situação Financeira</relationshipLabel>
    <relationshipName>Situacao_Financeira</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Situacao_Financeira__c/fields/Faturamento_medio_trimestral__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_medio_trimestral__c</fullName>
    <description>Faturamento médio trimestral do cliente</description>
    <label>Faturamento médio trimestral</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Situacao_Financeira__c/fields/Situacao_Financeira__c.field-meta.xml
<CustomField>
    <fullName>Situacao_Financeira__c</fullName>
    <label>Situação Financeira</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Veiculos_e_placas__c/Veiculos_e_placas__c.object-meta.xml
<CustomObject>
    <label>Veículos e placas</label>
    <nameField>
        <displayFormat>VP-{0000000000}</displayFormat>
        <label>Nome de Veículos e placas</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Veículos e placas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Veiculos_e_placas__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Veículos e placas</relationshipLabel>
    <relationshipName>Veiculos_e_placas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Veiculos_e_placas__c/fields/Tipo_de_veiculo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_veiculo__c</fullName>
    <label>Tipo de veículo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Tipo_de_veiculo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AUTO-ELEVAÇÃO</fullName>
    </customValue>
    <customValue>
        <fullName>AUTOMÓVEL</fullName>
    </customValue>
    <customValue>
        <fullName>CAMINHAO</fullName>
    </customValue>
    <customValue>
        <fullName>CAMINHONETE</fullName>
    </customValue>
    <customValue>
        <fullName>CARRETA</fullName>
    </customValue>
    <customValue>
        <fullName>COLHEITADEIRA</fullName>
    </customValue>
    <customValue>
        <fullName>DESCARTÁVEL</fullName>
    </customValue>
    <customValue>
        <fullName>DESCARTÁVEL E RETORNÁVEL</fullName>
    </customValue>
    <customValue>
        <fullName>EMPILHADEIRA</fullName>
    </customValue>
    <customValue>
        <fullName>EQUIPAMENTO MÓVEL.</fullName>
    </customValue>
    <customValue>
        <fullName>ESCAVADEIRA</fullName>
    </customValue>
    <customValue>
        <fullName>GUINDASTE</fullName>
    </customValue>
    <customValue>
        <fullName>MAQUINA</fullName>
    </customValue>
    <customValue>
        <fullName>MICROONIBUS</fullName>
    </customValue>
    <customValue>
        <fullName>MOTO</fullName>
    </customValue>
    <customValue>
        <fullName>MOTO NIVELADORA</fullName>
    </customValue>
    <customValue>
        <fullName>ONIBUS</fullName>
    </customValue>
    <customValue>
        <fullName>PÁ CARREGADEIRA</fullName>
    </customValue>
    <customValue>
        <fullName>PICKUP</fullName>
    </customValue>
    <customValue>
        <fullName>PLATAFORMA ELEVATÓRIA</fullName>
    </customValue>
    <customValue>
        <fullName>PONTE ROLANTE</fullName>
    </customValue>
    <customValue>
        <fullName>RETORNÁVEL</fullName>
    </customValue>
    <customValue>
        <fullName>RETROESCAVADEIRA</fullName>
    </customValue>
    <customValue>
        <fullName>SEMI-REBOQUE</fullName>
    </customValue>
    <customValue>
        <fullName>SIDER</fullName>
    </customValue>
    <customValue>
        <fullName>TRATOR</fullName>
    </customValue>
    <customValue>
        <fullName>TRATOR DE ESTEIRA</fullName>
    </customValue>
    <customValue>
        <fullName>VAN</fullName>
    </customValue>
    <customValue>
        <fullName>VEÍCULOS LEVES</fullName>
    </customValue>
    <customValue>
        <fullName>Chasi</fullName>
        <label>CHASI</label>
    </customValue>
    <description>Tipos de veículo do ERP - tabela: tipo_veiculo</description>
    <masterLabel>Tipo de veículo</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjetoCRMTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ProjetoCRMTest {
	
	static testMethod void deleteTypesVehiclesFP(){
        Account acc = new Account();
        acc.Name = 'Teste';
        acc.RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'CORP'].Id;
        insert acc;
        
        Id accId = acc.Id;
        
        Frota_Potencial__c frotaP = new Frota_Potencial__c();
        frotaP.Conta__c = accId;
        frotaP.Tipo_de_ve_culo__c = 'VAN';
        frotaP.Quantidade_de_veiculos__c = 2;
        frotaP.Concorrente__c = 'AUTOTRAC';
        frotaP.Nivel_de_relacionamento__c = 'Bom';
        insert frotaP;
        
		test.startTest();
			delete frotaP;
		test.StopTest();
	}
	
	static testMethod void setPotencialInFrotaTotal(){		
		Account acc = new Account();
        acc.Name = 'Teste';
        acc.RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'CORP'].Id;
        insert acc;
        
        Id accId = acc.Id;
        
        Frota_Potencial__c frotaP = new Frota_Potencial__c();
        frotaP.Conta__c = accId;
        frotaP.Tipo_de_ve_culo__c = 'VAN';
        frotaP.Quantidade_de_veiculos__c = 2;
        frotaP.Concorrente__c = 'AUTOTRAC';
        frotaP.Nivel_de_relacionamento__c = 'Bom';
        insert frotaP;
        
        
        List<AggregateResult> frotaPotencial = [SELECT
                                                        Tipo_de_ve_culo__c, SUM(Quantidade_de_veiculos__c)
                                                    FROM
                                                        Frota_Potencial__c
                                                    WHERE
                                                        Conta__c =: accId
                                                    GROUP BY
                                                        Tipo_de_ve_culo__c
                                                    ORDER BY
                                                        Tipo_de_ve_culo__c ASC];
                                                                
        List<Frota_Total__c> frtotal = [Select Id, Tipo_de_Veiculo__c FROM Frota_Total__c WHERE Conta__c=:accId];        
        Map<String, Id> mapFrotaTotal = new Map<String, Id>();
        
        for(Frota_Total__c a: frtotal){
            mapFrotaTotal.put(String.valueOf(a.Tipo_de_Veiculo__c), a.Id);
        }
                                                                     
        for(AggregateResult fp: frotaPotencial){
            String tipo_veiculo = String.valueOf(fp.get('Tipo_de_ve_culo__c'));
                        
            if(mapFrotaTotal.containsKey(tipo_veiculo)){
                //update
                Frota_Total__c newFrotaTotal = new Frota_Total__c();
                newFrotaTotal.Id = mapFrotaTotal.get(tipo_veiculo);
                newFrotaTotal.Tipo_de_veiculo__c = String.valueOf(fp.get('Tipo_de_ve_culo__c')); //Tipo_de_ve_culo__c;
                newFrotaTotal.Quantidade_Potencial__c = Integer.valueOf(fp.get('expr0')); //Quantidade_de_veiculos__c;
                update newFrotaTotal;
                
                system.debug('setPotencialInFrotaTotal - update FrotaTotal: ' +newFrotaTotal);
            } else{
                //insert
                Frota_Total__c newFrotaTotal = new Frota_Total__c();
                newFrotaTotal.Tipo_de_veiculo__c = String.valueOf(fp.get('Tipo_de_ve_culo__c')); //Tipo_de_ve_culo__c;
                newFrotaTotal.Conta__c = acc.Id;
                newFrotaTotal.Quantidade_Potencial__c = Integer.valueOf(fp.get('expr0')); //Quantidade_de_veiculos__c;
                insert newFrotaTotal;
                
                system.debug('setPotencialInFrotaTotal  - insert newFrotaTotal: ' +newFrotaTotal);
            }
        
        }
	}
	
	static testMethod void acc(){
		Account acc1 = new Account();
        acc1.Name = 'Teste';
        acc1.RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'CORP'].Id;
        insert acc1;
        
        Account acc = new Account();
        acc.Id = acc1.Id;
	}
	
	static testMethod void pentahoUpsertSituacaoFinanceira(){
		Boolean bln = true;
        Account accnt = new Account();
        accnt.Name = 'Teste';
        accnt.RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'CORP'].Id;
        insert accnt;
        
        Situacao_Financeira__c vep = new Situacao_Financeira__c();
        vep.Id_Cliente__c = accnt.Id;
        vep.Conta__c = accnt.Id;
        
        insert vep;
        
        List<Situacao_Financeira__c> frota = new List<Situacao_Financeira__c>();
        frota.add(vep);
        
		if(bln){
            for(Situacao_Financeira__c sf : frota){
                String Id_Cliente = sf.Id_Cliente__c;
                
                if(sf.Id_Cliente__c != ''){                
                    Account acc = [SELECT Id, Name FROM Account WHERE Id=:Id_Cliente];                
                    sf.Conta__c = accnt.Id;    
                }
            }
        }
	}
	
	static testMethod void pentahoUpsertVeiculosPlacas(){
		Boolean bln = true;
        Account accnt = new Account();
        accnt.Name = 'Teste';
        accnt.RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'CORP'].Id;
        insert accnt;
        
        Veiculos_e_placas__c vep = new Veiculos_e_placas__c();
        vep.Id_Cliente__c = accnt.Id;
        vep.Conta__c = accnt.Id;
        
        insert vep;
        
        List<Veiculos_e_placas__c> frota = new List<Veiculos_e_placas__c>();
        frota.add(vep);
        
        if(bln){               
            for(Veiculos_e_placas__c vp : frota){
                String Id_Cliente = vp.Id_Cliente__c;
                
                if(vp.Id_Cliente__c != ''){
                    Account acc = [SELECT Id, Name FROM Account WHERE Id=:Id_Cliente];                
                    vp.Conta__c = accnt.Id;    
                }
            }     
        }
    }
	
	static testMethod void pentahoUpsertSituacaoTermo(){
		Boolean bln = true;
        Account accnt = new Account();
        accnt.Name = 'Teste';
        accnt.RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'CORP'].Id;
        insert accnt;
        
        Situacao_do_Termo__c sdt = new Situacao_do_Termo__c();
        sdt.Id_Cliente__c = accnt.Id;
        sdt.Conta__c = accnt.Id;
        
        insert sdt;
        
        List<Situacao_do_Termo__c> frota = new List<Situacao_do_Termo__c>();
        frota.add(sdt);
        
        if(bln){
            for(Situacao_do_Termo__c st : frota){
                String Id_Cliente = st.Id_Cliente__c;
                
                if(st.Id_Cliente__c != ''){                     
                    system.debug('Pentaho: '+Id_Cliente );
                
                    Account acc = [SELECT Id, Name FROM Account WHERE Id=:Id_Cliente];
                    system.debug('Pentaho: '+acc);
                
                    st.Conta__c = accnt.Id;    
                }
            }
        }
    }
	
	static testMethod void pentahoUpsertInteracoes(){
		Boolean bln = true;
        Account accnt = new Account();
        accnt.Name = 'Teste';
        accnt.RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'CORP'].Id;
        insert accnt;
        
        Interacoes__c intr = new Interacoes__c();
        intr.Id_Cliente__c = accnt.Id;
        intr.Conta__c = accnt.Id;
        
        insert intr;
        
        List<Interacoes__c> frota = new List<Interacoes__c>();
        frota.add(intr);
        
        if(bln){
            for(Interacoes__c itc : frota){
                String Id_Cliente = itc.Id_Cliente__c;
                
                if(itc.Id_Cliente__c != ''){
                    Account acc = [SELECT Id, Name FROM Account WHERE Id=:Id_Cliente];                
                    itc.Conta__c = accnt.Id;    
                }
            }
        }
    }
	
	static testMethod void pentahoUpsertInFrotaSascar(){        
        //before insert - isInsert
        /*Boolean bln = true;
        Account accnt = new Account();
        accnt.Name = 'Teste';
        accnt.RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'CORP'].Id;
        insert accnt;
        
        Frota_Sascar__c frt = new Frota_Sascar__c();
        frt.Id_Cliente__c = accnt.Id;
        frt.Conta__c = accnt.Id;
        
        insert frt;
        
        List<Frota_Sascar__c> frota = new List<Frota_Sascar__c>();
        frota.add(frt);
        
        if(bln){
            for(Frota_Sascar__c fs : frota){
                String Id_Cliente = fs.Id_Cliente__c;
                
                if(fs.Id_Cliente__c != ''){                
                    Account acc = [SELECT Id, Name FROM Account WHERE Id=:Id_Cliente];                
                    fs.Conta__c = accnt.Id;    
                }
            }     
        }*/
	}
		
	static testMethod void setInformacoesFinanceirasInAccount(){
		Account acc1 = new Account();
        acc1.Name = 'Teste';
        acc1.RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'CORP'].Id;
        insert acc1;
        
        Account acc = new Account();
        acc.Id = acc1.Id;
        
        Id accId = acc.Id;
        
        Situacao_Financeira__c situacao = new Situacao_Financeira__c();
        situacao.Conta__c = accId;
        situacao.Faturamento_medio_trimestral__c = 36000.10;
        situacao.Situacao_Financeira__c = 'Adimplente';
        situacao.Rentabilidade_Mensal__c = 21160.74;
        situacao.Situacao_sinal__c = 'Normal';
        situacao.Acao_judicial__c = 'NÃO';
        situacao.Rentabilidade_YTD__c = 210160.74;
        //insert situacao;
        
        /*List<Situacao_Financeira__c> sf = [SELECT
                                                Faturamento_medio_trimestral__c,
                                                Situacao_Financeira__c,
                                                Rentabilidade_Mensal__c,
                                                Situacao_sinal__c,
                                                Acao_judicial__c,
                                                Rentabilidade_YTD__c
                                            FROM
                                                Situacao_Financeira__c
                                            WHERE
                                                Conta__c=:accId];*/
        List<Situacao_Financeira__c> sf = new List<Situacao_Financeira__c>();
        sf.add(situacao);                                               
        
        if(sf.size() > 0){
            acc.Faturamento_medio_trimestral__c = sf[0].Faturamento_medio_trimestral__c;
            acc.Situacao_financeira__c = sf[0].Situacao_Financeira__c;
            acc.Rentabilidade_mensal__c = sf[0].Rentabilidade_Mensal__c;
            acc.Situacao_sinal__c = sf[0].Situacao_sinal__c;
            acc.A_o_judicial__c = sf[0].Acao_judicial__c;
            acc.Rentabilidade_YTD__c = sf[0].Rentabilidade_YTD__c;
            update acc;
        }
	}

    static testMethod void neverCallThisMethod() {
        ProjetoCRM.neverCallThisMethod();
	}
	
	static testMethod void neverCallThisMethod1() {
        ConsultaFrotaPotencial.neverCallThisMethod();
	}
	
	static testMethod void neverCallThisMethod2() {
        ConsultaFrotaSascar.neverCallThisMethod();
	}
	
	static testMethod void neverCallThisMethod3() {
        ConsultaFrotaTotal.neverCallThisMethod();
	}
	
	static testMethod void neverCallThisMethod4() {
        ConsultaSituacaoFinanceira.neverCallThisMethod();
	}
	
	static testMethod void neverCallThisMethod5() {
        VeiculosPlacas.neverCallThisMethod();
	}
}