force-app/main/default/objects/Item_ordem_servico__c/Item_ordem_servico__c.object-meta.xml
<CustomObject>
    <label>Item da ordem de serviço</label>
    <nameField>
        <label>Nome do Item da ordem de serviço</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da ordem de serviço</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_ordem_servico__c/fields/Codigo_externo__c.field-meta.xml
<CustomField>
    <fullName>Codigo_externo__c</fullName>
    <externalId>true</externalId>
    <label>Código externo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Item_ordem_servico__c/fields/Tipo_item_OS__c.field-meta.xml
<CustomField>
    <fullName>Tipo_item_OS__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Motivo</label>
    <referenceTo>Tipo_item_OS__c</referenceTo>
    <relationshipLabel>Itens da ordem de serviço</relationshipLabel>
    <relationshipName>Itens_ordem_servico</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item_ordem_servico__c/fields/Tipo_OS__c.field-meta.xml
<CustomField>
    <fullName>Tipo_OS__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tipo de OS</label>
    <referenceTo>Tipo_OS__c</referenceTo>
    <relationshipLabel>Itens da ordem de serviço</relationshipLabel>
    <relationshipName>Itens_ordem_servico</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Status_OS__c/Status_OS__c.object-meta.xml
<CustomObject>
    <description>Status das ordens de serviço</description>
    <label>Status da OS</label>
    <nameField>
        <label>Nome do Status da OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Status da OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Status_OS__c/fields/Codigo_Externo__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Externo__c</fullName>
    <description>ID do Status da OS no ERP</description>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Status_OS__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tipo_item_OS__c/Tipo_item_OS__c.object-meta.xml
<CustomObject>
    <label>Tipo do item da OS</label>
    <nameField>
        <label>Nome do tipo do item da OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos dos itens da OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_item_OS__c/fields/Codigo_Externo__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Externo__c</fullName>
    <description>ID do Tipo do item da os no ERP</description>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tipo_item_OS__c/fields/Tipo_OS__c.field-meta.xml
<CustomField>
    <fullName>Tipo_OS__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Tipo de OS</description>
    <label>Tipo de OS</label>
    <referenceTo>Tipo_OS__c</referenceTo>
    <relationshipLabel>Tipos dos itens da OS</relationshipLabel>
    <relationshipName>Tipos_dos_itens_da_OS</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tipo_OS__c/Tipo_OS__c.object-meta.xml
<CustomObject>
    <description>Registra os tipos de OS disponíveis para uso</description>
    <label>Tipo de OS</label>
    <nameField>
        <label>Nome do Tipo de OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_OS__c/fields/Codigo_Externo__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Externo__c</fullName>
    <description>ID do tipo de OS do ERP</description>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Util_Servicos_OS.cls
/*
    Classe de teste: Util_Servicos_OS
    Criado por: Mario Reis <mario.pereira.ext@sascar.com.br>
    Data de criação: 23/06/2018
    Descrição: Classe Util para informações da OS
    ----------------------------------------------------------------------
*/
public class Util_Servicos_OS {

    public static List<WorkOrder> verificarTipoMacroMicro(List<WorkOrder> listaOS){

        System.debug(LoggingLevel.ERROR, '__ [cls Util_Servicos_OS - verificarTipoMacroMicro()] - Inicio...');
        System.debug(LoggingLevel.ERROR,  '__ [cls Util_Servicos_OS - verificarTipoMacroMicro()] - listaOS: '+listaOS);

        try {

            List<WorkOrder> listaAtualizar = new List<WorkOrder>();

            if(listaOS != null && listaOS.size() > 0){

                for(WorkOrder os : listaOS){

                    System.debug(LoggingLevel.ERROR, '__ [cls Util_Servicos_OS - verificarTipoMacroMicro()] - os.Status_OS__c: '+os.Status_OS__c);
                    System.debug(LoggingLevel.ERROR, '__ [cls Util_Servicos_OS - verificarTipoMacroMicro()] - os.Status_OS__r.Tipo__c: '+os.Status_OS__r.Tipo__c);

                    if(os.Itens_ordem_servico__r.size() == 0){
                        os.Tipo_macro_OS__c = 'Sem motivo cadastrado';
						os.Tipo_micro_OS__c = 'Sem item cadastrado';
                    }

                    Decimal menorPrioridade = 0;

                    for(Item_ordem_servico__c item : os.Itens_ordem_servico__r){
                        
                        System.debug(LoggingLevel.ERROR, '__ [cls Util_Servicos_OS - atualizarInformacoesHistorico()] - os.Id: '+os.Id);
                        System.debug(LoggingLevel.ERROR, '__ [cls Util_Servicos_OS - atualizarInformacoesHistorico()] - item.Tipo_Item_OS__r.Codigo_externo__c: '+item.Tipo_Item_OS__r.Codigo_externo__c);

						if(item.Tipo_Item_OS__r.Codigo_externo__c == '3'){

                            //motivo_macro = 'INSTALAÇÃO';
                            os.Tipo_macro_OS__c = 'Instalação';
                            //motivo_micro = 'INSTALAÇÃO DE EQUIPAMENTO';
                            os.Tipo_micro_OS__c = 'Instalação de Equipamento';
                            break;

						} else if(item.Tipo_Item_OS__r.Codigo_externo__c == '77' || 
                                  item.Tipo_Item_OS__r.Codigo_externo__c == '932'){

							//motivo_macro = 'INSTALAÇÃO';
							os.Tipo_macro_OS__c = 'Instalação';
                            //motivo_micro = 'INSTALAÇÃO - UPGRADE';
                            os.Tipo_micro_OS__c = 'Instalação – Upgrade';
							break;

						} else if(item.Tipo_Item_OS__r.Codigo_externo__c == '1128' || 
                                  item.Tipo_Item_OS__r.Codigo_externo__c == '1287'){

							//motivo_macro = 'INSTALAÇÃO';
							os.Tipo_macro_OS__c = 'Instalação';
                            //motivo_micro = 'INSTALAÇÃO - DOWNGRADE';
                            os.Tipo_micro_OS__c = 'Instalação – Downgrade';
                            break;

                        } else if(item.Tipo_Item_OS__r.Codigo_externo__c == '1229' || 
                                  item.Tipo_Item_OS__r.Codigo_externo__c == '98' || 
                                  item.Tipo_Item_OS__r.Codigo_externo__c == '891' || 
                                  item.Tipo_Item_OS__r.Codigo_externo__c == '892'){

							//motivo_macro = 'Reinstalação';
                            os.Tipo_macro_OS__c = 'Reinstalação';
							//motivo_micro = 'REINSTALAÇÃO - TRC';
                            os.Tipo_micro_OS__c = 'Reinstalação – TRC';
                            break;

                        } else if (item.Tipo_Item_OS__r.Codigo_externo__c == '11' || 
                                   item.Tipo_Item_OS__r.Codigo_externo__c == '870'){

							//motivo_macro = 'RETIRADA';
                            os.Tipo_macro_OS__c = 'Retirada';
							//motivo_micro = 'RETIRADA - TRC';
                            os.Tipo_micro_OS__c = 'Retirada - TRC';
                            break;

                        } else {

                            menorPrioridade = menorPrioridade == 0 || menorPrioridade >  Integer.valueOf(item.Tipo_OS__r.Codigo_externo__c) ? 
                                				Integer.valueOf(item.Tipo_OS__r.Codigo_externo__c) : menorPrioridade;

                            if(menorPrioridade == Integer.valueOf(item.Tipo_OS__r.Codigo_externo__c)){

                                if(menorPrioridade == 1){
                                    os.Tipo_macro_OS__c = 'Instalação';
									os.Tipo_micro_OS__c = 'Instalação';
                                } else if(menorPrioridade == 2){
                                    os.Tipo_macro_OS__c = 'Reinstalação';
									os.Tipo_micro_OS__c = 'Reinstalação';
                                } else if(menorPrioridade == 3){
                                    os.Tipo_macro_OS__c = 'Retirada';
									os.Tipo_micro_OS__c = 'Retirada';
                                } else if(menorPrioridade == 4){
                                    os.Tipo_macro_OS__c = 'Assistência';
									os.Tipo_micro_OS__c = 'Assistência';
                                } else if(menorPrioridade == 9){
                                    os.Tipo_macro_OS__c = 'Reinstalação não cobrar';
									os.Tipo_micro_OS__c = 'Reinstalação não cobrar';
                                }  else {
                                    os.Tipo_macro_OS__c = 'Sem motivo cadastrado';
									os.Tipo_micro_OS__c = 'Sem item cadastrado';
                                }

                            } // Fim if(menorPrioridade == item.Tipo_OS__r.Codigo_externo__c)

                            System.debug(LoggingLevel.ERROR, '__ [cls Util_Servicos_OS - atualizarInformacoesHistorico()] - menorPrioridade: '+menorPrioridade);

                        } // Fim if(item.Tipo_Item_OS__r.Codigo_externo__c == 3)

                    } // Fim for(Item_ordem_servico__c item : os.Itens_ordem_servico__r)

					listaAtualizar.add(os);

                } // Fim for(WorkOrder os : listaOS)
				//listaAtualizar = retornaTipoMacroMicroOSLista(listaAtualizar);
            } // Fim if(listaOS != null && listaOS.size() > 0)

            return listaAtualizar;

        } catch (Exception e){
            System.debug(LoggingLevel.ERROR, '__ [cls Util_Servicos_OS - atualizarInformacoesOS()] - ERRO: '+e.getMessage());
            return new List<WorkOrder>();
        } // Fim try/catch

    } // Fim verificarTipoMacroMicro

}