force-app/main/default/objects/Tipo_item_OS__c/Tipo_item_OS__c.object-meta.xml
<CustomObject>
    <label>Tipo do item da OS</label>
    <nameField>
        <label>Nome do tipo do item da OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos dos itens da OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_item_OS__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>campo para identificar se um registro está ativo ou não</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tipo_item_OS__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <description>Classificação do Item da OS (A=Acessório, E= Equipamento e K= Kit)</description>
    <inlineHelpText>A = Acessório
E = Equipamento
K = Kit</inlineHelpText>
    <label>Item</label>
    <length>1</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tipo_item_OS__c/fields/Tipo_OS__c.field-meta.xml
<CustomField>
    <fullName>Tipo_OS__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Tipo de OS</description>
    <label>Tipo de OS</label>
    <referenceTo>Tipo_OS__c</referenceTo>
    <relationshipLabel>Tipos dos itens da OS</relationshipLabel>
    <relationshipName>Tipos_dos_itens_da_OS</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tipo_OS__c/Tipo_OS__c.object-meta.xml
<CustomObject>
    <description>Registra os tipos de OS disponíveis para uso</description>
    <label>Tipo de OS</label>
    <nameField>
        <label>Nome do Tipo de OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_OS__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se um registro está ativo ou não</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DAO_Tipo_Item_OS.cls
/*
	@testClass Teste_DAO_Tipo_Item_OS
	
	@description Classe para o Objeto: Tipo_item_os__c
	
	@author Renan Rocha
	@date 07/01/2019
	@JIRA KCA-59
*/

public class DAO_Tipo_Item_OS{
	private static String CLASS_NAME = 'DAO_Tipo_Item_OS';
	
    // Método que retorna todos os motivos conforme tipo e item
    public static List<Tipo_item_OS__c> getListaTipoItemOS(String tipo, String item){
        String METHOD_NAME = 'getListaTipoItemOS';

        System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - tipo: '+ tipo);
        System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - item: '+ item);

        String[] arrTipo = tipo.split(',');
        String[] arrItem = item.split(',');

        System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - arrTipo: '+ arrTipo);
        System.debug(LoggingLevel.ERROR, '___ [cls '+ CLASS_NAME +' - '+ METHOD_NAME +'()] - arrItem: '+ arrItem);

        return
            [SELECT Id
                  , Ativo__c
                  , Item__c
                  , Name
                  , Tipo_OS__c
            FROM Tipo_item_OS__c 
            WHERE Ativo__c = true 
            AND Tipo_OS__c IN: arrTipo 
            AND Item__c IN: arrItem
            ORDER BY Name];
    } // Fim método getListaTipoItemOS
}