force-app/main/default/objects/Tipo_item_OS__c/Tipo_item_OS__c.object-meta.xml
<CustomObject>
    <label>Tipo do item da OS</label>
    <nameField>
        <label>Nome do tipo do item da OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos dos itens da OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_item_OS__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <description>Classificação do Item da OS (A=Acessório, E= Equipamento e K= Kit)</description>
    <inlineHelpText>A = Acessório
E = Equipamento
K = Kit</inlineHelpText>
    <label>Item</label>
    <length>1</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tipo_item_OS__c/fields/Tipo_OS__c.field-meta.xml
<CustomField>
    <fullName>Tipo_OS__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Tipo de OS</description>
    <label>Tipo de OS</label>
    <referenceTo>Tipo_OS__c</referenceTo>
    <relationshipLabel>Tipos dos itens da OS</relationshipLabel>
    <relationshipName>Tipos_dos_itens_da_OS</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tipo_OS__c/Tipo_OS__c.object-meta.xml
<CustomObject>
    <description>Registra os tipos de OS disponíveis para uso</description>
    <label>Tipo de OS</label>
    <nameField>
        <label>Nome do Tipo de OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Teste_DAO_Tipo_Item_OS.cls
/*
	@testClass DAO_Tipo_Item_OS
	
	@author Renan Rocha
	@date 07/01/2019
*/

@isTest
public class Teste_DAO_Tipo_Item_OS{
	
	/*
		@author Renan Rocha
		@date 08/01/2019
	*/
	static testMethod void getListaTipoItemOS(){
		Map<String, sObject> mapBase = Teste_Util.createMapBase();
		Tipo_item_OS__c tipoItemOS = (Tipo_item_OS__c) mapBase.get('Tipo_item_OS__c');

		System.assertEquals(1, DAO_Tipo_Item_OS.getListaTipoItemOS(tipoItemOS.Tipo_OS__c, tipoItemOS.Item__c).size());
	}
}