force-app/main/default/objects/Status_OS__c/Status_OS__c.object-meta.xml
<CustomObject>
    <description>Status das ordens de serviço</description>
    <label>Status da OS</label>
    <nameField>
        <label>Nome do Status da OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Status da OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Status_OS__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Define se um registro está ativo ou não</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Status_OS__c/fields/Pais_Referencia__c.field-meta.xml
<CustomField>
    <fullName>Pais_Referencia__c</fullName>
    <description>Iso no padrão Alpha-3 do país</description>
    <inlineHelpText>Insira a sigla com 3 letras no padrão ISO do país que relativo a este registro</inlineHelpText>
    <label>País de Referência</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DAO_Status_OS.cls
/*
	@testClass Teste_DAO_Status_OS
	
	@description Classe para o Objeto: Status_OS__c
	
	@author Renan Rocha
	@date 07/01/2019
	@JIRA KCA-59
*/

public class DAO_Status_OS{
	private static String CLASS_NAME = 'DAO_Status_OS';
	
	// Método que retorna todos os Status de OS Ativos
    public static List<Status_OS__c> getListaStatusOS(){
        String METHOD_NAME = 'getListaStatusOS';

        return
            [SELECT Id
                  , Ativo__c
                  , Name
            FROM Status_OS__c 
            WHERE Ativo__c = true AND Pais_referencia__c = 'BRA'
            ORDER BY Name];
    } // Fim método getListaStatusOS
}