force-app/main/default/objects/Status_OS__c/Status_OS__c.object-meta.xml
<CustomObject>
    <description>Status das ordens de serviço</description>
    <label>Status da OS</label>
    <nameField>
        <label>Nome do Status da OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Status da OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Status_OS__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Define se um registro está ativo ou não</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Status_OS__c/fields/Codigo_Externo__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Externo__c</fullName>
    <description>ID do Status da OS no ERP</description>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Status_OS__c/fields/Pais_Referencia__c.field-meta.xml
<CustomField>
    <fullName>Pais_Referencia__c</fullName>
    <description>Iso no padrão Alpha-3 do país</description>
    <inlineHelpText>Insira a sigla com 3 letras no padrão ISO do país que relativo a este registro</inlineHelpText>
    <label>País de Referência</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Status_OS__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Teste_Util_Status_OS.cls
/*
    Classe de testes para cadastro do objeto Status OS
    Criado por: Mario Reis
    Data: 12/06/2018
*/
@isTest
public class Teste_Util_Status_OS {


    //Método para criar Status Autorizado Pendente
    public static Status_OS__c criarStatusAutorizadoPendente(){

        Status_OS__c statusOS = new Status_OS__c();
        statusOS.Name = 'Autorizado';
        statusOS.Codigo_Externo__c = '4';
        statusOS.Ativo__c = true;
        statusOS.Pais_Referencia__c = 'BRA';
        statusOS.Tipo__c = 'Pendente';

        insert statusOS;
        return statusOS;
    }// Fim criarStatusAutorizadoPendente


    //Método para criar Status Concluido Finalizado
    public static Status_OS__c criarStatusConcluidoFinalizado(){

        Status_OS__c statusOS = new Status_OS__c();
        statusOS.Name = 'Concluído';
        statusOS.Codigo_Externo__c = '3';
        statusOS.Ativo__c = true;
        statusOS.Pais_Referencia__c = 'BRA';
        statusOS.Tipo__c = 'Finalizado';

        insert statusOS;
        return statusOS;
    }// Fim criarStatusConcluidoFinalizado


}