force-app/main/default/objects/Triggers__c/Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuração para ativação/desativação da trigger</description>
    <label>Triggers</label>
</CustomObject>

force-app/main/default/objects/Triggers__c/fields/Trigger_conta__c.field-meta.xml
<CustomField>
    <fullName>Trigger_conta__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Validação para rodar a Trigger_conta</description>
    <label>Trigger conta</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Teste_Trigger_Conta.cls
/*
    Classe de testes para a Trigger "Trigger_Conta"

    Criado por: Mario Reis
    Data: 25/08/2017

*/
@isTest
public class Teste_Trigger_Conta {

    /*
        @author Renan Rocha
        @date 11/01/2019
    */
    static testMethod void teste(){
        Triggers__c trigg = new Triggers__c();
        trigg.Trigger_conta__c = true;
        insert trigg;
        
        Map<String, sObject> mapBase = Teste_Util.createMapBase();   
    }
}