force-app/main/default/objects/Triggers__c/Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuração para ativação/desativação da trigger</description>
    <label>Triggers</label>
</CustomObject>

force-app/main/default/objects/Triggers__c/fields/Trigger_item_ordem_servico__c.field-meta.xml
<CustomField>
    <fullName>Trigger_item_ordem_servico__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trigger item ordem serviço</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Teste_Trigger_Item_Ordem_Servico.cls
/*
    Classe de testes para a Trigger "Trigger_Item_Ordem_Servico"
    Criado por: Juliano Szlachta
    Data: 26/06/2018
*/
@isTest
public class Teste_Trigger_Item_Ordem_Servico {

	static testmethod void teste()  {
		Triggers__c confTriggers = new Triggers__c();
        confTriggers.Trigger_item_ordem_servico__c = true;
    	insert confTriggers;
        
        Map<String, sObject> mapBase = Teste_Util.createMapBase();
	}	
}