force-app/main/default/objects/Triggers__c/Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuração para ativação/desativação da trigger</description>
    <label>Triggers</label>
</CustomObject>

force-app/main/default/objects/Triggers__c/fields/Trigger_contato__c.field-meta.xml
<CustomField>
    <fullName>Trigger_contato__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Validação para rodar a Trigger_contato</description>
    <label>Trigger contato</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Teste_Trigger_Contato.cls
/*
    Classe de testes para a Trigger "Trigger_Contato"

    Criado por: Mario Reis
    Data: 08/12/2017

*/
@isTest
public class Teste_Trigger_Contato {

    static testmethod void testeTriggerContato() {

        Test.startTest();

        Util_Conta.carregarTipoRegistro();

        Triggers__c confTriggers = Teste_Util_Configuracao.criarConfiguracaoTriggers();
        confTriggers.Trigger_contato__c = true;
        update confTriggers;

        Account conta = Teste_Util_Conta.criaContaBluetecF(Util_Conta.bluetec, '843.163.290-90');
        Contact contato = Teste_Util_Contato.criaContato(conta.Id, '83045200', 'rua', 'estado', 'cidade', 'Brasil');

        Test.stopTest();

    } // Fim testeTriggerContato

}