force-app/main/default/objects/Lead/fields/agregado__c.field-meta.xml
<CustomField>
    <fullName>agregado__c</fullName>
    <label>É agregado ?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Não</fullName>
            </value>
            <value>
                <fullName>Sim</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Qual_empresa_esta_agregando__c.field-meta.xml
<CustomField>
    <fullName>Qual_empresa_esta_agregando__c</fullName>
    <label>Qual empresa está agregando ?</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/LeadBOTest.cls
@isTest
private class LeadBOTest {

    private static testMethod void createLead() {
        Map<String, sObject> mapBase = Teste_Util.createMapBase();
		Lead lead = (Lead) mapBase.get('Lead');
		lead.agregado__c = 'Não';
		lead.CNPJ__c = '65.398.444/0001-72';
		lead.Qual_empresa_esta_agregando__c = 'Empresa teste';
		update lead;

        Test.startTest();
			Database.LeadConvert lc = new Database.LeadConvert();
			lc.setLeadId(lead.Id);

			LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted = true LIMIT 1];
			lc.setConvertedStatus(convertStatus.MasterLabel);

			Database.LeadConvertResult lcr = Database.convertLead(lc);
			System.assert(lcr.isSuccess());  
        Test.stopTest();
	}
}