force-app/main/default/objects/Lead/fields/agregado__c.field-meta.xml
<CustomField>
    <fullName>agregado__c</fullName>
    <label>É agregado ?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Não</fullName>
            </value>
            <value>
                <fullName>Sim</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Canal_de_entrada__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_entrada__c</fullName>
    <label>Canal de entrada</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Receptivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CNPJ_CPF__c.field-meta.xml
<CustomField>
    <fullName>CNPJ_CPF__c</fullName>
    <label>CNPJ/CPF</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CUIT__c.field-meta.xml
<CustomField>
    <fullName>CUIT__c</fullName>
    <description>Chave Única de Identificação Tributária</description>
    <externalId>true</externalId>
    <inlineHelpText>Chave Única de Identificação Tributária. Formato: 00-00000000-0</inlineHelpText>
    <label>CUIT</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <description>Documento Nacional de Identificação</description>
    <externalId>true</externalId>
    <inlineHelpText>Documento Nacional de Identificação. Formato: 00.000.000</inlineHelpText>
    <label>DNI</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/Qual_empresa_esta_agregando__c.field-meta.xml
<CustomField>
    <fullName>Qual_empresa_esta_agregando__c</fullName>
    <label>Qual empresa está agregando ?</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Telefone_3__c.field-meta.xml
<CustomField>
    <fullName>Telefone_3__c</fullName>
    <label>Telefone 3</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Tipo_de_pessoa__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_pessoa__c</fullName>
    <label>Tipo de pessoa</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>J-Jurídica - MEI</fullName>
            </value>
            <value>
                <fullName>J-Jurídica - ME</fullName>
            </value>
            <value>
                <fullName>F-Física</fullName>
            </value>
            <value>
                <fullName>J-Jurídica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Argentina.recordType-meta.xml
<RecordType>
    <fullName>Argentina</fullName>
    <active>true</active>
    <businessProcess>CORP</businessProcess>
    <label>Argentina</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/CORP.recordType-meta.xml
<RecordType>
    <fullName>CORP</fullName>
    <active>true</active>
    <businessProcess>CORP</businessProcess>
    <label>CORP</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Freteiro.recordType-meta.xml
<RecordType>
    <fullName>Freteiro</fullName>
    <active>true</active>
    <businessProcess>Freteiro</businessProcess>
    <label>Freteiro</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Mercosul.recordType-meta.xml
<RecordType>
    <fullName>Mercosul</fullName>
    <active>true</active>
    <businessProcess>CORP</businessProcess>
    <label>Mercosul</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Michelin.recordType-meta.xml
<RecordType>
    <fullName>Michelin</fullName>
    <active>true</active>
    <businessProcess>Michelin</businessProcess>
    <description>Piloto Michelin</description>
    <label>Michelin</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Siggo.recordType-meta.xml
<RecordType>
    <fullName>Siggo</fullName>
    <active>true</active>
    <businessProcess>Siggo</businessProcess>
    <label>Siggo</label>
</RecordType>

force-app/main/default/classes/Teste_Util_Lead.cls
/*
	Criado por: Mario Reis
	Data de criação: 02/10/2017
	Descrição: Classe com métodos para criar registros relacionados ao Lead
					para apoio as classes de teste
*/

@isTest
public class Teste_Util_Lead {

    // Método para retornar o lead do tipo Mercosul Pessoa Fisica
    public static Lead criaLeadMercosulDNI(String idTipoRegistro, String DNI){

        Lead lead = new Lead();
		lead.RecordTypeId = idTipoRegistro;
        lead.FirstName = 'Nome Mercosul';
        lead.LastName = 'Sobrenome Mercosul';
        lead.Status = 'Em aberto';
        lead.Company = 'Empresa';
        lead.DNI__c = DNI;
        lead.Tipo_de_pessoa__c = 'F-Física';
        lead.Canal_de_entrada__c = 'Ativo';
        lead.LeadSource = 'Facebook';

        insert lead;
        return lead;

    } // Fim método criaLeadMercosulDNI

    
    // Método para retornar a lead do tipo Mercosul Pessoa Juridca
    public static Lead criaLeadMercosulCUIT(String idTipoRegistro, String CUIT){

        Lead lead = new Lead();
		lead.RecordTypeId = idTipoRegistro;
        lead.FirstName = 'Nome Mercosul';
        lead.LastName = 'Sobrenome Mercosul';
        lead.Status = 'Em aberto';
        lead.Company = 'Empresa';
        lead.CUIT__c = CUIT;
        lead.Tipo_de_pessoa__c = 'J-Jurídica';
        lead.Canal_de_entrada__c = 'Ativo';
        lead.LeadSource = 'Facebook';
        lead.Country = 'Argentina';
        lead.agregado__c = 'Não';
        lead.Qual_empresa_esta_agregando__c = 'Empresa teste';

        insert lead;
        return lead;

    } // Fim método criaLeadMercosulCUIT


    // Método para retornar a lead do tipo Cargo Tracck Pessoa Fisica
    public static Lead criaLeadCargoTracckF(String idTipoRegistro, String CPF){

        Lead lead = new Lead();
		lead.RecordTypeId = idTipoRegistro;
        lead.FirstName = 'Nome Cargo Tracck';
        lead.LastName = 'Sobrenome Cargo Tracck';
        lead.Status = 'Em aberto';
        lead.Company = 'Empresa';
        lead.CPF__c = CPF;
        lead.Tipo_de_pessoa__c = 'F-Física';
        lead.Canal_de_entrada__c = 'Ativo';
        lead.LeadSource = 'Facebook';
        lead.Country = 'Brasil';

        insert lead;
        return lead;

    } // Fim método criaLeadCargoTracckF



    // Método para retornar a lead do tipo Cargo Tracck Pessoa Juridica
    public static Lead criaLeadCargoTracckJ(String idTipoRegistro, String CNPJ){

        Lead lead = new Lead();
		lead.RecordTypeId = idTipoRegistro;
        lead.FirstName = 'Nome Cargo Tracck';
        lead.LastName = 'Sobrenome Cargo Tracck';
        lead.Status = 'Em aberto';
        lead.Company = 'Empresa';
        lead.CNPJ__c = CNPJ;
        lead.Tipo_de_pessoa__c = 'J-Jurídica';
        lead.Canal_de_entrada__c = 'Ativo';
        lead.LeadSource = 'Facebook';
        lead.Country = 'Brasil';

        insert lead;
        return lead;

    } // Fim método criaLeadCargoTracckJ



    // Método para retornar a lead do tipo CORP
    public static Lead criaLeadCORP(String idTipoRegistro, String CNPJ){

        Lead lead = new Lead();
		lead.RecordTypeId = idTipoRegistro;
        lead.FirstName = 'Nome CORP';
        lead.LastName = 'Sobrenome Car';
        lead.Status = 'Em aberto';
        lead.Company = 'Empresa';
        lead.CNPJ__c = CNPJ;
        lead.Tipo_de_pessoa__c = 'J-Jurídica';
        lead.Canal_de_entrada__c = 'Ativo';
        lead.LeadSource = 'Facebook';
        lead.Country = 'Brasil';

        insert lead;
        return lead;

    } // Fim método criaLeadCargoTracckJ



    // Método para retornar a lead do tipo Bluetec Pessoa Fisica
    public static Lead criaLeadBluetecF(String idTipoRegistro, String CPF){

        Lead lead = new Lead();
		lead.RecordTypeId = idTipoRegistro;
        lead.FirstName = 'Nome Bluetec';
        lead.LastName = 'Sobrenome Bluetec';
        lead.Status = 'Em aberto';
        lead.Company = 'Empresa';
        lead.CPF__c = CPF;
        lead.Tipo_de_pessoa__c = 'F-Física';
        lead.Canal_de_entrada__c = 'Ativo';
        lead.LeadSource = 'Facebook';
        lead.Country = 'Brasil';

        insert lead;
        return lead;

    } // Fim método criaLeadBluetecF



    // Método para retornar a lead do tipo Bluetec Pessoa Juridica
    public static Lead criaLeadBluetecJ(String idTipoRegistro, String CNPJ){

        Lead lead = new Lead();
		lead.RecordTypeId = idTipoRegistro;
        lead.FirstName = 'Nome Bluetec';
        lead.LastName = 'Sobrenome Bluetec';
        lead.Status = 'Em aberto';
        lead.Company = 'Empresa';
        lead.CNPJ__c = CNPJ;
        lead.Tipo_de_pessoa__c = 'J-Jurídica';
        lead.Canal_de_entrada__c = 'Ativo';
        lead.LeadSource = 'Facebook';
        lead.Country = 'Brasil';

        insert lead;
        return lead;

    } // Fim método criaLeadBluetecJ



    // Método para retornar a lead do tipo Bluetec Pessoa Fisica
    public static Lead criaLeadSiggo(String idTipoRegistro, String CPF){

        Lead lead = new Lead();
		lead.RecordTypeId = idTipoRegistro;
        lead.FirstName = 'Nome Siggo';
        lead.LastName = 'Sobrenome Siggo';
        lead.Status = 'Em aberto';
        lead.Company = 'Empresa';
        lead.CPF__c = CPF;
        lead.Tipo_de_pessoa__c = 'F-Física';
        lead.Canal_de_entrada__c = 'Ativo';
        lead.LeadSource = 'Facebook';
        lead.Country = 'Brasil';

        insert lead;
        return lead;

    } // Fim método Siggo



    // Método para retornar o lead do tipo FRETEIRO Pessoa Fisica
    public static Lead criaLeadFreteiroF(String idTipoRegistro, String CPF){

        Lead lead = new Lead();
		lead.RecordTypeId = idTipoRegistro;
        lead.FirstName = 'Nome Freteiro';
        lead.LastName = 'Sobrenome Freteiro';
        lead.Status = 'Em aberto';
        lead.Company = 'Empresa';
        lead.Tipo_de_pessoa__c = 'F-Física';
        lead.CNPJ_CPF__c = CPF;
        lead.Phone = '(41) 9999-9999';
        lead.Telefone_2__c = '(41) 9999-9999';
        lead.Telefone_3__c = '(41) 9999-9999';
        lead.Canal_de_entrada__c = 'Ativo';
        lead.LeadSource = 'Facebook';
        lead.Country = 'Brasil';

        insert lead;
        return lead;

    } // Fim método criaLeadFreteiroF



    // Método para retornar o lead do tipo Michelin Pessoa Fisica
    public static Lead criaLeadMichelin(String idTipoRegistro, String CNPJ){

        Lead lead = new Lead();
		lead.RecordTypeId = idTipoRegistro;
        lead.FirstName = 'Nome Michelin';
        lead.LastName = 'Sobrenome Michelin';
        lead.Status = 'Em aberto';
        lead.Company = 'Empresa';
        lead.CNPJ_CPF__c = CNPJ;
        lead.Phone = '(41) 9999-9999';
        lead.Telefone_2__c = '(41) 9999-9999';
        lead.Telefone_3__c = '(41) 9999-9999';
        lead.Canal_de_entrada__c = 'Ativo';
        lead.LeadSource = 'Facebook';
        lead.Country = 'Brasil';

        insert lead;
        return lead;

    } // Fim método criaLeadMichelin
    

}