force-app/main/default/objects/Lead/fields/Atualizacao_manual_de_motivo__c.field-meta.xml
<CustomField>
    <fullName>Atualizacao_manual_de_motivo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Permite que o registro com status marcado como &quot;Desqualificado&quot; seja salvo sem um motivo de desqualificação. (Criado para execução automática da padronização dos membros de campanha).</description>
    <label>Atualização manual de motivo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Campanha__c.field-meta.xml
<CustomField>
    <fullName>Campanha__c</fullName>
    <label>Campanha Atual</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Historico_Atualizacao_manual_de_motivo__c.field-meta.xml
<CustomField>
    <fullName>Historico_Atualizacao_manual_de_motivo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que mantém histórico que registro teve o campo motivo atualizado manualmente. Usado na regra de validação para seleção do motivo correto. (Campo criado para execução automática de padronização dos membros de campanha).</description>
    <label>Historico Atualização manual de motivo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Motivo_da_desqualifica_o_do_lead__c.field-meta.xml
<CustomField>
    <fullName>Motivo_da_desqualifica_o_do_lead__c</fullName>
    <label>Motivo da desqualificação do lead</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1ª Tentativa</fullName>
            </value>
            <value>
                <fullName>2ª Tentativa</fullName>
            </value>
            <value>
                <fullName>3 Tentativas sem sucesso</fullName>
            </value>
            <value>
                <fullName>3ª Tentativa</fullName>
            </value>
            <value>
                <fullName>4ª Tentativa</fullName>
            </value>
            <value>
                <fullName>6 tentativas sem sucesso</fullName>
            </value>
            <value>
                <fullName>Abandono Chat</fullName>
            </value>
            <value>
                <fullName>Baixo IRC</fullName>
            </value>
            <value>
                <fullName>Cliente de Base</fullName>
            </value>
            <value>
                <fullName>Cliente já efetuou a compra</fullName>
            </value>
            <value>
                <fullName>Cliente sem sinistro</fullName>
            </value>
            <value>
                <fullName>Condição Fiscal não atende</fullName>
            </value>
            <value>
                <fullName>Contato Impossível</fullName>
            </value>
            <value>
                <fullName>Contato Impossível - 5 tentativas sem sucesso</fullName>
            </value>
            <value>
                <fullName>Decisor ausente</fullName>
            </value>
            <value>
                <fullName>Destinatário errado (tel/mail)</fullName>
            </value>
            <value>
                <fullName>E-mail inválido</fullName>
            </value>
            <value>
                <fullName>E-mail não correspondido</fullName>
            </value>
            <value>
                <fullName>Empresa deixou de ser responsável pela compra da isca</fullName>
            </value>
            <value>
                <fullName>Empresa sem atividade</fullName>
            </value>
            <value>
                <fullName>Estoque elevado</fullName>
            </value>
            <value>
                <fullName>Falta de Pronta Resposta na região</fullName>
            </value>
            <value>
                <fullName>Fechado em pessoa jurídica</fullName>
            </value>
            <value>
                <fullName>Financeiro Sascar - Crédito</fullName>
            </value>
            <value>
                <fullName>Fora do perfil</fullName>
            </value>
            <value>
                <fullName>Implantação inviável</fullName>
            </value>
            <value>
                <fullName>Interessado em ouvir em Proposta</fullName>
            </value>
            <value>
                <fullName>Interesse Futuro</fullName>
            </value>
            <value>
                <fullName>Lead Duplicado</fullName>
            </value>
            <value>
                <fullName>Linha Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membro_da_Campanha_vs_Lead__c/Membro_da_Campanha_vs_Lead__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Descreve a relação entre um status de membro de campanha e os devidos valores para os campos Status e Motivo de Desqualificação no objeto Lead.</description>
    <label>Membro da Campanha vs Lead</label>
</CustomObject>

force-app/main/default/objects/Membro_da_Campanha_vs_Lead__c/fields/Motivo_da_Desqualificacao__c.field-meta.xml
<CustomField>
    <fullName>Motivo_da_Desqualificacao__c</fullName>
    <description>Refere-se ao valor do campo lista de opções Motivo da desqualificação do lead (API: Motivo_da_desqualifica_o_do_lead__c) do objeto Lead.</description>
    <inlineHelpText>Refere-se ao valor do campo lista de opções Motivo da desqualificação do lead (API: Motivo_da_desqualifica_o_do_lead__c) do objeto Lead.</inlineHelpText>
    <label>Motivo da Desqualificação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Membro_da_Campanha_vs_Lead__c/fields/Status_do_Lead__c.field-meta.xml
<CustomField>
    <fullName>Status_do_Lead__c</fullName>
    <description>Refere-se ao valor do campo lista de opções Status do Lead (API: Status) do objeto Lead.</description>
    <inlineHelpText>Refere-se ao valor do campo lista de opções Status do Lead (API: Status) do objeto Lead.</inlineHelpText>
    <label>Status do Lead</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Membro_da_Campanha_vs_Lead__c/fields/Status_do_membro_da_campanha__c.field-meta.xml
<CustomField>
    <fullName>Status_do_membro_da_campanha__c</fullName>
    <description>Refere-se ao valor do campo lista de opções Status (API: Status) do objeto Membro da Campanha.</description>
    <inlineHelpText>Refere-se ao valor do campo lista de opções Status (API: Status) do objeto Membro da Campanha.</inlineHelpText>
    <label>Status do membro da campanha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Membro_da_Campanha_vs_Lead__c/fields/Tipo_da_Campanha__c.field-meta.xml
<CustomField>
    <fullName>Tipo_da_Campanha__c</fullName>
    <description>Refere-se ao valor do campo lista de Opções Tipo (API: Type) do objeto Campanha.</description>
    <inlineHelpText>Refere-se ao valor do campo lista de Opções Tipo (API: Type) do objeto Campanha.</inlineHelpText>
    <label>Tipo da Campanha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CampaignMemberTriggers.cls
public class CampaignMemberTriggers{

    public static void AtualizaLead(List<CampaignMember> TriggerList, Boolean isDelete){
        Set<String> campanhaIds = new Set<String>();
        Set<String> leadIds = new Set<String>();
        Map<String,String> mapCM = new Map<String,String>();
  
        if(!isDelete){
            for(CampaignMember cm :TriggerList){
                if(cm.CampaignId != null) campanhaIds.add(cm.CampaignId);
                if(cm.LeadId != null) leadIds.add(cm.LeadId);
            }
            Map<Id, Campaign> campanhaMap = new Map<Id, Campaign>([SELECT Id, Name FROM Campaign WHERE Id IN :campanhaIds]);
            for(CampaignMember cm :TriggerList){
                mapCM.put(cm.LeadId, campanhaMap.get(cm.CampaignId).Name);
            }
            List<Lead> lstLead = [SELECT Id, Campanha__c FROM Lead WHERE Id IN :leadIds];
            for(Lead l : lstLead){
                if(mapCM.get(l.Id) != null) l.Campanha__c = mapCM.get(l.Id);
            }
            if(lstLead.size() > 0) update lstLead;
        }else{
            for(CampaignMember cm :TriggerList){
                if(cm.CampaignId != null) campanhaIds.add(cm.CampaignId);
                if(cm.LeadId != null) leadIds.add(cm.LeadId);
            }
            Map<Id, Campaign> campanhaMap = new Map<Id, Campaign>([SELECT Id, Name FROM Campaign WHERE Id IN :campanhaIds]);
            for(CampaignMember cm :TriggerList){
                if(campanhaMap.get(cm.CampaignId).Name != null) mapCM.put(cm.LeadId, campanhaMap.get(cm.CampaignId).Name);
            }
            List<Lead> lstLead = [SELECT Id, Campanha__c FROM Lead WHERE Id IN :leadIds];
            for(Lead l : lstLead){
                if(mapCM.get(l.Id) != null && l.Campanha__c == mapCM.get(l.Id)) l.Campanha__c = '';
            }
            if(lstLead.size() > 0) update lstLead;
        }
    }
    
    public static void UpdateCampaignMember(List<CampaignMember> lstCM){
        Map<String,List<Membro_da_Campanha_vs_Lead__c>> mapCMvsLead = new Map<String,List<Membro_da_Campanha_vs_Lead__c>>();
        for(Membro_da_Campanha_vs_Lead__c cmStatus :[SELECT Id, Name, Tipo_da_Campanha__c, Status_do_membro_da_campanha__c, Status_do_Lead__c, Motivo_da_Desqualificacao__c FROM Membro_da_Campanha_vs_Lead__c]){
            if(!mapCMvsLead.containsKey(cmStatus.Tipo_da_Campanha__c)){
                mapCMvsLead.put(cmStatus.Tipo_da_Campanha__c, new List<Membro_da_Campanha_vs_Lead__c>());
            }
            mapCMvsLead.get(cmStatus.Tipo_da_Campanha__c).add(cmStatus);
        }
        
        Set<Id> campaignIds = new Set<Id>();
        Set<Id> leadIds = new Set<Id>();
        for(CampaignMember cm :lstCM){
            if(cm.CampaignId != null) campaignIds.add(cm.CampaignId);
            if(cm.LeadId != null) leadIds.add(cm.LeadId);
        }
        
        Map<Id, String> mapCampaignType = new Map<Id, String>(); 
        Map<Id, String> mapCampaignOwnerEmail = new Map<Id, String>(); 
        Map<Id, String> mapCampaignOwnerName = new Map<Id, String>(); 
        Map<Id, String> mapCampaignName = new Map<Id, String>();
        Set<String> setCampaignTypes = new set<String>();
        for(Campaign c :[SELECT Id, Type, RecordType.DeveloperName, Owner.Email, Owner.Name, Name FROM Campaign WHERE Id IN :campaignIds AND RecordType.DeveloperName IN :mapCMvsLead.keySet()]){
            //system.debug('CP Campanha: ' + c);
            if(c.RecordType.DeveloperName != null) mapCampaignType.put(c.Id, c.RecordType.DeveloperName);
            if(c.Owner.Email != null) mapCampaignOwnerEmail.put(c.Id,c.Owner.Email);
            if(c.Owner.Name != null) mapCampaignOwnerName.put(c.Id,c.Owner.Name);
            if(c.Name != null) mapCampaignName.put(c.Id,c.Name);
        }
    	
        Map<Id, Lead> mapLead = new Map<Id, Lead>([SELECT Id, Name, Status, Motivo_da_desqualifica_o_do_lead__c, Atualizacao_manual_de_motivo__c, Historico_Atualizacao_manual_de_motivo__c
                                 FROM Lead WHERE Id IN :leadIds]); 
        
        for(CampaignMember cm :lstCM){
            system.debug('CP mapCampaignType: ' + mapCampaignType);
            system.debug('CP mapCMvsLead: ' + mapCMvsLead);
            if(mapCampaignType.containsKey(cm.CampaignId)){
                if(mapCMvsLead.containsKey(mapCampaignType.get(cm.CampaignId)) && cm.LeadId != null){
                    Boolean containStatus = false;
                    for(Membro_da_Campanha_vs_Lead__c cmStatus :mapCMvsLead.get(mapCampaignType.get(cm.CampaignId))){
                        if(cm.Status == cmStatus.Status_do_membro_da_campanha__c){
                            if(mapLead.containsKey(cm.LeadId)){
                                Lead l = mapLead.get(cm.LeadId);
                                l.Status = cmStatus.Status_do_Lead__c;
                                l.Motivo_da_desqualifica_o_do_lead__c = cmStatus.Motivo_da_Desqualificacao__c;
                                //if(cm.Status == 'Não interessado em ouvir proposta'){
                                //    l.Atualizacao_manual_de_motivo__c = true;
                                //    l.Historico_Atualizacao_manual_de_motivo__c = true;
                                //}else{
                                //    l.Atualizacao_manual_de_motivo__c = false;
                                //    l.Historico_Atualizacao_manual_de_motivo__c = false;
                                //}
                                mapLead.put(l.Id,l);
                            }
                            containStatus = true;
                    	}
                    }
                    if(!containStatus){
                        if(mapCampaignOwnerEmail.containsKey(cm.CampaignId)){
                            String result = sendEmailAlert(mapCampaignOwnerEmail.get(cm.CampaignId), mapCampaignOwnerName.get(cm.CampaignId), mapLead.get(cm.LeadId).Name, mapCampaignName.get(cm.CampaignId));
                            if(result != '0') cm.addError(result);
                        }
                    }
                }
            }
        }
        if(mapLead.size() > 0) update mapLead.values();
    }
    
    private static String sendEmailAlert(String ownerEmail, String ownerName, String memberName, String campaignName) {
        //Value for return
        String result = '0';
        
        // Define the email
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        String addresses;
        addresses = ownerEmail;
        String[] toAddresses = addresses.split(':', 0);
        
        // Sets the paramaters of the email
        email.setSubject( 'Status de membro da campanha não definido no objeto "Membro da Campanha vs Lead".' );
        email.settoAddresses( toAddresses );
        email.setHtmlBody( 'Prezado '+ ownerName +',<br><br>O Membro da Campanha abaixo não possui o Status de Lead relacionado ao status de membro da campanha atual.<br><br>Membro: <b>'+ memberName +'</b><br>Campanha: <b>'+ campaignName +'</b>.<br><br>Solicite ao Administrador do Sistema que configure a relação deste Status de Membro da Campanha a um Status de Lead.<br><br>Atenciosamente' );
        
        // Sends the email
        try{
            Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});   
        }catch(Exception e){
            result = 'Erro no processo de envio: \n' + e;
        }
        return result;
    }
}