force-app/main/default/objects/Lead/fields/Bairro_endereco__c.field-meta.xml
<CustomField>
    <fullName>Bairro_endereco__c</fullName>
    <label>Bairro endereço</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Cadencia__c.field-meta.xml
<CustomField>
    <fullName>Cadencia__c</fullName>
    <label>Cadência</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A planejar</fullName>
                <default>true</default>
                <label>À planejar</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>-- Nenhum --</fullName>
                <isActive>false</isActive>
                <label>-- Nenhum --</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Circuito__c.field-meta.xml
<CustomField>
    <fullName>Circuito__c</fullName>
    <label>Circuito</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A planejar</fullName>
                <default>true</default>
                <label>À planejar</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>-- Nenhum --</fullName>
                <isActive>false</isActive>
                <label>-- Nenhum --</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CNPJ_CPF__c.field-meta.xml
<CustomField>
    <fullName>CNPJ_CPF__c</fullName>
    <label>CNPJ/CPF</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Consultor_indicacao__c.field-meta.xml
<CustomField>
    <fullName>Consultor_indicacao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultor de indicação</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Consultor_indicacao__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CUIT__c.field-meta.xml
<CustomField>
    <fullName>CUIT__c</fullName>
    <description>Chave Única de Identificação Tributária</description>
    <externalId>true</externalId>
    <inlineHelpText>Chave Única de Identificação Tributária. Formato: 00-00000000-0</inlineHelpText>
    <label>CUIT</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/DNI__c.field-meta.xml
<CustomField>
    <fullName>DNI__c</fullName>
    <description>Documento Nacional de Identificação</description>
    <externalId>true</externalId>
    <inlineHelpText>Documento Nacional de Identificação. Formato: 00.000.000</inlineHelpText>
    <label>DNI</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/Gerenciador_de_risco__c.field-meta.xml
<CustomField>
    <fullName>Gerenciador_de_risco__c</fullName>
    <label>Gerenciador de risco</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Angelira</fullName>
            </value>
            <value>
                <fullName>APISUL Multisat</fullName>
            </value>
            <value>
                <fullName>Brasil Risk</fullName>
            </value>
            <value>
                <fullName>Buonny</fullName>
            </value>
            <value>
                <fullName>GV</fullName>
            </value>
            <value>
                <fullName>Opentech</fullName>
            </value>
            <value>
                <fullName>Raster</fullName>
            </value>
            <value>
                <fullName>Outro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Indicador__c.field-meta.xml
<CustomField>
    <fullName>Indicador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Indicador</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/J_utilizou_rastreador__c.field-meta.xml
<CustomField>
    <fullName>J_utilizou_rastreador__c</fullName>
    <label>Já utilizou rastreador</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Marca_do_concorrente__c.field-meta.xml
<CustomField>
    <fullName>Marca_do_concorrente__c</fullName>
    <label>Marca do concorrente</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AUTOTRAC</fullName>
            </value>
            <value>
                <fullName>Bridgestone</fullName>
            </value>
            <value>
                <fullName>BYSAT</fullName>
            </value>
            <value>
                <fullName>CARSYSTEM</fullName>
            </value>
            <value>
                <fullName>Continental</fullName>
            </value>
            <value>
                <fullName>Firestone</fullName>
            </value>
            <value>
                <fullName>GOLSAT</fullName>
            </value>
            <value>
                <fullName>Goodyear</fullName>
            </value>
            <value>
                <fullName>ITURAN</fullName>
            </value>
            <value>
                <fullName>LINK</fullName>
            </value>
            <value>
                <fullName>LO JACK</fullName>
            </value>
            <value>
                <fullName>MEGATRANS</fullName>
            </value>
            <value>
                <fullName>MICROTRACK</fullName>
            </value>
            <value>
                <fullName>ONIX</fullName>
            </value>
            <value>
                <fullName>OUTRA</fullName>
            </value>
            <value>
                <fullName>OUTROS</fullName>
            </value>
            <value>
                <fullName>Pirelli</fullName>
            </value>
            <value>
                <fullName>POINTER</fullName>
            </value>
            <value>
                <fullName>PORTO SEGURO</fullName>
            </value>
            <value>
                <fullName>POSITRON</fullName>
            </value>
            <value>
                <fullName>SITRACK</fullName>
            </value>
            <value>
                <fullName>TRACKER</fullName>
            </value>
            <value>
                <fullName>Truscom</fullName>
            </value>
            <value>
                <fullName>ZATIX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Nome_fantasia__c.field-meta.xml
<CustomField>
    <fullName>Nome_fantasia__c</fullName>
    <label>Nome fantasia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Origem_Lead_Agrupado__c.field-meta.xml
<CustomField>
    <fullName>Origem_Lead_Agrupado__c</fullName>
    <label>Origem do Lead Agrupado</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadSource</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Ações MKT</fullName>
            </value>
            <value>
                <fullName>Ataque à base</fullName>
            </value>
            <value>
                <fullName>Ativo - Prospecção do TV</fullName>
            </value>
            <value>
                <fullName>Busca Google</fullName>
            </value>
            <value>
                <fullName>Canal Exclusivo de Indicações</fullName>
            </value>
            <value>
                <fullName>Chat Siggo</fullName>
            </value>
            <value>
                <fullName>E-commerce</fullName>
            </value>
            <value>
                <fullName>Email MKT</fullName>
            </value>
            <value>
                <fullName>Evento Feira ou convenção</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Formulário Home Siggo</fullName>
            </value>
            <value>
                <fullName>Fornecedor de Leads</fullName>
            </value>
            <value>
                <fullName>Frota Circulante - Executivo</fullName>
            </value>
            <value>
                <fullName>Indicação</fullName>
            </value>
            <value>
                <fullName>Indicação de Cliente MGM</fullName>
            </value>
            <value>
                <fullName>Indicador</fullName>
            </value>
            <value>
                <fullName>Indicador de Negócio</fullName>
            </value>
            <value>
                <fullName>Loja Michelin</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Michelin</fullName>
            </value>
            <value>
                <fullName>Mídia TV</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
            <value>
                <fullName>Parcerias</fullName>
            </value>
            <value>
                <fullName>Site Sascar</fullName>
            </value>
            <value>
                <fullName>Site Siggo</fullName>
            </value>
            <value>
                <fullName>Site Siggo Receptivo</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Totem Michelin</fullName>
            </value>
            <value>
                <fullName>You Tube</fullName>
            </value>
            <value>
                <fullName>Site Sascar Integrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Possui_Escolta_Armada__c.field-meta.xml
<CustomField>
    <fullName>Possui_Escolta_Armada__c</fullName>
    <label>Possui Escolta Armada ?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NÃO</fullName>
            </value>
            <value>
                <fullName>SIM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Segmento__c.field-meta.xml
<CustomField>
    <fullName>Segmento__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AGRONEGÓCIOS / USINA</fullName>
            </value>
            <value>
                <fullName>ALIMENTÍCIA</fullName>
            </value>
            <value>
                <fullName>ALIMENTOS</fullName>
            </value>
            <value>
                <fullName>ASSOCIACAO</fullName>
            </value>
            <value>
                <fullName>AUTOMOTIVO</fullName>
            </value>
            <value>
                <fullName>AUTOPEÇAS E COMBUSTÍVEIS</fullName>
            </value>
            <value>
                <fullName>BEBIDAS</fullName>
            </value>
            <value>
                <fullName>BENS DE CONSUMO</fullName>
            </value>
            <value>
                <fullName>CALÇADOS</fullName>
            </value>
            <value>
                <fullName>CIGARRO</fullName>
            </value>
            <value>
                <fullName>COMÉRCIO</fullName>
            </value>
            <value>
                <fullName>CONSTRUÇÃO CIVIL</fullName>
            </value>
            <value>
                <fullName>DISTRIBUIDORA</fullName>
            </value>
            <value>
                <fullName>E-COMMERCE</fullName>
            </value>
            <value>
                <fullName>ELETROELETRÔNICOS</fullName>
            </value>
            <value>
                <fullName>ELETRÔNICO</fullName>
            </value>
            <value>
                <fullName>ESCOLAR</fullName>
            </value>
            <value>
                <fullName>EXTRAÇÃO DE MINÉRIO</fullName>
            </value>
            <value>
                <fullName>FARMACÊUTICOS</fullName>
            </value>
            <value>
                <fullName>FRACIONADO</fullName>
            </value>
            <value>
                <fullName>FRACIONADO ELETRÔNICO</fullName>
            </value>
            <value>
                <fullName>FRETEIRO</fullName>
            </value>
            <value>
                <fullName>FRIGORÍFICO</fullName>
            </value>
            <value>
                <fullName>FROTA</fullName>
            </value>
            <value>
                <fullName>GÁS</fullName>
            </value>
            <value>
                <fullName>INDÚSTRIA</fullName>
            </value>
            <value>
                <fullName>LINHA AMARELA</fullName>
            </value>
            <value>
                <fullName>LOCADORA</fullName>
            </value>
            <value>
                <fullName>MADEIREIRA</fullName>
            </value>
            <value>
                <fullName>MAQUINA/OUTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/VerificaDuplicidade__c.field-meta.xml
<CustomField>
    <fullName>VerificaDuplicidade__c</fullName>
    <label>VerificaDuplicidade</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DAO_Lead.cls
/*
	Classe de teste: Teste_DAO_Lead
	Criado por: Mario Reis
	Data de criação: 02/10/2017
	Descrição: Classe DAO para o objeto Lead
*/
public class DAO_Lead {


	// Método que retorna a lista de tipos de registro do Lead
	public static Map<String, String> getMapTipoRegistro(){

		System.debug(LoggingLevel.ERROR, '__ [cls DAO_Lead - getMapTipoRegistro()] - Inicio...');

		Map<String, String> mapRetorno = new Map<String, String>();

		try {

			for(RecordType rt : [SELECT Id
										, Name
										, DeveloperName 
									FROM RecordType 
								WHERE sObjectType = 'Lead']){
				mapRetorno.put(rt.DeveloperName, String.valueOf(rt.Id).substring(0,15) );
			}

			System.debug(LoggingLevel.ERROR, '__ [cls DAO_Lead - getMapTipoRegistro()] - mapRetorno: '+mapRetorno);

			return mapRetorno;

		} catch (Exception e){

			System.debug(LoggingLevel.ERROR, '__ [cls DAO_Lead - getMapTipoRegistro()] - ERRO: '+e.getMessage());
			throw new customException(Label.MSG_ERRO_0010);

		} // Fim try/catch

	} // Fim método getMapTipoRegistro


    // Método que retorna a lista de Leads para verificação da duplicidade
	public static List<Lead> getLeadVerificaoDuplicidadePorId(Set<Id> setIdLead, Set<String> setIdVerificaDuplicidade){

		System.debug(LoggingLevel.ERROR, '__ [cls DAO_Lead - getLeadVerificaoDuplicidadePorId()] - Inicio...');
		System.debug(LoggingLevel.ERROR, '__ [cls DAO_Lead - getLeadVerificaoDuplicidadePorId()] - setIdLead: '+setIdLead);
		System.debug(LoggingLevel.ERROR, '__ [cls DAO_Lead - getLeadVerificaoDuplicidadePorId()] - setIdVerificaDuplicidade: '+setIdVerificaDuplicidade);

		try {

			return [SELECT Id, Name, VerificaDuplicidade__c, CPF__c, CNPJ__c, CNPJ_CPF__c 
                        FROM Lead 
                    WHERE VerificaDuplicidade__c != ''
                    	AND VerificaDuplicidade__c IN: setIdVerificaDuplicidade
                    	AND Id NOT IN: setIdLead];

		} catch (Exception e){

			System.debug(LoggingLevel.ERROR, '__ [cls DAO_Lead - getLeadVerificaoDuplicidadePorId()] - ERRO: '+e.getMessage());
			throw new customException(Label.MSG_ERRO_0018);

		} // Fim try/catch

	} // Fim método getLeadVerificaoDuplicidadePorId


    // Método que retorna o Lead pelo ID da conta
	public static Lead getLeadPorContaId(String contaId){

        System.debug(LoggingLevel.ERROR, '__ [cls DAO_Lead - getLeadPorContaId()] - Inicio...');
		System.debug(LoggingLevel.ERROR, '__ [cls DAO_Lead - getLeadPorContaId()] - contaId: '+contaId);

		try {

            Lead leadRetorno = new Lead();

            for(Lead lead :[SELECT Id
                    		, RecordTypeId
							, Cadencia__c
                            , MobilePhone
                            , Circuito__c
                            , CNPJ__c
                            , Consultor_indicacao__c
                            , CPF__c
                            , CUIT__c
                            , Description
                            , DNI__c
                            , Email
                            , PostalCode
                            , Street
                            , State
                            , City
                            , Country
                            , Bairro_endereco__c
                            , Gerenciador_de_risco__c
                            , Indicador__c
                            , J_utilizou_rastreador__c
                            , Marca_do_concorrente__c
                            , Nome_fantasia__c
                            , Origem_Lead_Agrupado__c
                            , Outro_GR__c
                            , Outro_Segmento__c
                            , Possui_Escolta_Armada__c
                            , Qual_a_outra_marca__c
                            , Quantidade_de_ve_culos__c
                            , Quantidade_ve_culos_leves__c
                            , Quantidade_veiculos_pesados__c
                            , Segmento__c
                            , Website
                            , Tem_ve_culos_leves__c
                            , Tem_veiculos_pesados__c
                            , Tipo_de_cliente__c
                            , Tipo_de_pessoa__c
                            , Utiliza_concorrente__c
                            , Phone
                            , Telefone_2__c
                            , Telefone_3__c
                            , Telefone_4__c
					FROM Lead
				WHERE ConvertedAccountId =: contaId
                            AND isConverted = true]){

					leadRetorno = lead; 
				}

            if(leadRetorno.Id != null) return leadRetorno;
            else return null;

		} catch (Exception e){

			System.debug(LoggingLevel.ERROR, '__ [cls DAO_Lead - getLeadPorContaId()] - ERRO: '+e.getMessage());
			throw new customException(Label.MSG_ERRO_0024);

		} // Fim try/catch

    } // Fim getLeadPorContaId


}