force-app/main/default/objects/Lead/fields/Bairro_endereco__c.field-meta.xml
<CustomField>
    <fullName>Bairro_endereco__c</fullName>
    <label>Bairro endereço</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Bairro_sg__c.field-meta.xml
<CustomField>
    <fullName>Bairro_sg__c</fullName>
    <description>Bairro Para integração portal Siggo</description>
    <label>Bairro</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CEP_sg__c.field-meta.xml
<CustomField>
    <fullName>CEP_sg__c</fullName>
    <description>CEP Para integração portal Siggo</description>
    <label>CEP</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Cidade_sg__c.field-meta.xml
<CustomField>
    <fullName>Cidade_sg__c</fullName>
    <description>Cidade Para integração portal Siggo</description>
    <label>Cidade</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Codigo_municipio__c.field-meta.xml
<CustomField>
    <fullName>Codigo_municipio__c</fullName>
    <label>Código municipio</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Complemento_endereco__c.field-meta.xml
<CustomField>
    <fullName>Complemento_endereco__c</fullName>
    <label>Complemento endereço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Complemento_sg__c.field-meta.xml
<CustomField>
    <fullName>Complemento_sg__c</fullName>
    <description>Complemento Para integração portal Siggo</description>
    <label>Complemento</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Indicador__c.field-meta.xml
<CustomField>
    <fullName>Indicador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Indicador</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Logradouro_sg__c.field-meta.xml
<CustomField>
    <fullName>Logradouro_sg__c</fullName>
    <description>Logradouro Para integração portal Siggo</description>
    <label>Logradouro</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Numero_endereco__c.field-meta.xml
<CustomField>
    <fullName>Numero_endereco__c</fullName>
    <label>Número endereço</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Numero_sg__c.field-meta.xml
<CustomField>
    <fullName>Numero_sg__c</fullName>
    <description>Numero Para integração portal Siggo</description>
    <label>Numero</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RG_sg__c.field-meta.xml
<CustomField>
    <fullName>RG_sg__c</fullName>
    <description>RG para Integração com portal Siggo</description>
    <label>RG</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/UF_sg__c.field-meta.xml
<CustomField>
    <fullName>UF_sg__c</fullName>
    <description>UF Para integração portal Siggo</description>
    <label>UF</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadDAO.cls
public with sharing class LeadDAO {
	
	public static Lead getLeadByCNPJ(String cnpj){
		
        String query = 'SELECT ' + allFields() + 
			' FROM Lead' + 
			' WHERE CNPJ__c = \'' + cnpj + '\'' + 
			' LIMIT 1';

		System.debug('***QUERY: '+query);

		List<Lead> leadList = Database.Query(query);
		
		if(leadList.isEmpty()){
			return null;
		}
        
        return leadList[0];
		
	}

	public static Lead getLeadById(Id leadId){
		
        String query = 'SELECT ' + allFields() + 
			' FROM Lead' + 
			' WHERE Id = \'' + leadId + '\'' + 
			' LIMIT 1';

		System.debug('***QUERY: '+query);

		List<Lead> leadList = Database.Query(query);
		
		if(leadList.isEmpty()){
			return null;
		}
        
        return leadList[0];
		
	}
	
	public static String allFields(){
		
		String allFields = 'CEP_sg__c, Logradouro_sg__c, Cidade_sg__c, Numero_sg__c, UF_sg__c, ' + 
		'Complemento_sg__c, Codigo_municipio__c, Bairro_sg__c, Description, Name, Street, City, PostalCode, ' +
		'Numero_endereco__c, State, Complemento_endereco__c, Bairro_endereco__c, RG_sg__c, CPF__c, Country, ' +
		'FirstName, LastName, CNPJ__c, RecordType.DeveloperName, ' +
		'Indicador__c';
		
		return allFields;
	}

	
}