force-app/main/default/objects/Lead/fields/Canal_de_entrada__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_entrada__c</fullName>
    <label>Canal de entrada</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Receptivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CNPJ_CPF__c.field-meta.xml
<CustomField>
    <fullName>CNPJ_CPF__c</fullName>
    <label>CNPJ/CPF</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Segmento__c.field-meta.xml
<CustomField>
    <fullName>Segmento__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AGRONEGÓCIOS / USINA</fullName>
            </value>
            <value>
                <fullName>ALIMENTÍCIA</fullName>
            </value>
            <value>
                <fullName>ALIMENTOS</fullName>
            </value>
            <value>
                <fullName>ASSOCIACAO</fullName>
            </value>
            <value>
                <fullName>AUTOMOTIVO</fullName>
            </value>
            <value>
                <fullName>AUTOPEÇAS E COMBUSTÍVEIS</fullName>
            </value>
            <value>
                <fullName>BEBIDAS</fullName>
            </value>
            <value>
                <fullName>BENS DE CONSUMO</fullName>
            </value>
            <value>
                <fullName>CALÇADOS</fullName>
            </value>
            <value>
                <fullName>CIGARRO</fullName>
            </value>
            <value>
                <fullName>COMÉRCIO</fullName>
            </value>
            <value>
                <fullName>CONSTRUÇÃO CIVIL</fullName>
            </value>
            <value>
                <fullName>DISTRIBUIDORA</fullName>
            </value>
            <value>
                <fullName>E-COMMERCE</fullName>
            </value>
            <value>
                <fullName>ELETROELETRÔNICOS</fullName>
            </value>
            <value>
                <fullName>ELETRÔNICO</fullName>
            </value>
            <value>
                <fullName>ESCOLAR</fullName>
            </value>
            <value>
                <fullName>EXTRAÇÃO DE MINÉRIO</fullName>
            </value>
            <value>
                <fullName>FARMACÊUTICOS</fullName>
            </value>
            <value>
                <fullName>FRACIONADO</fullName>
            </value>
            <value>
                <fullName>FRACIONADO ELETRÔNICO</fullName>
            </value>
            <value>
                <fullName>FRETEIRO</fullName>
            </value>
            <value>
                <fullName>FRIGORÍFICO</fullName>
            </value>
            <value>
                <fullName>FROTA</fullName>
            </value>
            <value>
                <fullName>GÁS</fullName>
            </value>
            <value>
                <fullName>INDÚSTRIA</fullName>
            </value>
            <value>
                <fullName>LINHA AMARELA</fullName>
            </value>
            <value>
                <fullName>LOCADORA</fullName>
            </value>
            <value>
                <fullName>MADEIREIRA</fullName>
            </value>
            <value>
                <fullName>MAQUINA/OUTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Tipo_de_pessoa__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_pessoa__c</fullName>
    <label>Tipo de pessoa</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>J-Jurídica - MEI</fullName>
            </value>
            <value>
                <fullName>J-Jurídica - ME</fullName>
            </value>
            <value>
                <fullName>F-Física</fullName>
            </value>
            <value>
                <fullName>J-Jurídica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/VerificaDuplicidade__c.field-meta.xml
<CustomField>
    <fullName>VerificaDuplicidade__c</fullName>
    <label>VerificaDuplicidade</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/CORP.recordType-meta.xml
<RecordType>
    <fullName>CORP</fullName>
    <active>true</active>
    <businessProcess>CORP</businessProcess>
    <label>CORP</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Freteiro.recordType-meta.xml
<RecordType>
    <fullName>Freteiro</fullName>
    <active>true</active>
    <businessProcess>Freteiro</businessProcess>
    <label>Freteiro</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Michelin.recordType-meta.xml
<RecordType>
    <fullName>Michelin</fullName>
    <active>true</active>
    <businessProcess>Michelin</businessProcess>
    <description>Piloto Michelin</description>
    <label>Michelin</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Siggo.recordType-meta.xml
<RecordType>
    <fullName>Siggo</fullName>
    <active>true</active>
    <businessProcess>Siggo</businessProcess>
    <label>Siggo</label>
</RecordType>

force-app/main/default/classes/PreencheCampoLeadTest.cls
/*
 * Testes não estão corretos, comentado algumas linhas para implantar em produção, 
 * necessário melhorar e deixar nos padrões
*/
@isTest
private class PreencheCampoLeadTest {
    
    static testMethod void Lead(){
    
        //CORP
        Map<String, Schema.RecordTypeInfo> tiposRegistro = Lead.sObjectType.getDescribe().getRecordTypeInfosByName();
        Lead l = new Lead();
        l.RecordTypeId = tiposRegistro.get('CORP').getRecordTypeId();
        l.FirstName = 'Lead';
        l.LastName = 'Teste';
        l.Company = 'Empresa Teste';
        l.Status = 'Em aberto';
        l.Canal_de_entrada__c = 'Ativo';
        l.LeadSource = 'Internet';
        l.Segmento__c = 'Bebidas';
        insert l;
    
        l.CNPJ__c = '12.403.787/0001-11';
        l.Phone = '00 0000 0000';
        update l;
    

        //SIGGO
        Lead le = new Lead();
        le.RecordTypeId = tiposRegistro.get('Siggo').getRecordTypeId();
        le.FirstName = 'Lead';
        le.LastName = 'Teste';
        le.Company = 'Empresa Teste';
        le.Status = 'Em aberto';
        le.Canal_de_entrada__c = 'Ativo';
        le.LeadSource = 'Internet';
        le.Segmento__c = 'Bebidas';
               
        insert le;
    
        le.CPF__c = '690.449.753-07';
        le.Phone = '00 0000 0000';
        
        update le;
    
   
        //FRETEIRO
        Lead lea = new Lead();
        lea.RecordTypeId = tiposRegistro.get('Freteiro').getRecordTypeId();
        lea.FirstName = 'Lead';
        lea.LastName = 'Teste';
        lea.Company = 'Empresa Teste';
        lea.Status = 'Em aberto';
        lea.Canal_de_entrada__c = 'Ativo';
        lea.LeadSource = 'Internet';
        lea.Segmento__c = 'Bebidas';
               
        insert lea;
    
        lea.CNPJ_CPF__c = '313.967.706-58';
        lea.Phone = '00 0000 0000';
        
        update lea;
        
         
        //MICHELIN
        Lead l1 = new Lead();
        l1.RecordTypeId = tiposRegistro.get('Michelin').getRecordTypeId();
        l1.FirstName = 'Lead';
        l1.LastName = 'Teste';
        l1.Company = 'Empresa Teste';
        l1.Status = 'Em aberto';
        l1.Canal_de_entrada__c = 'Ativo';
        l1.LeadSource = 'Internet';
        l1.Segmento__c = 'Bebidas';
               
        insert l1;
    
        l1.CNPJ_CPF__c = '411.333.228-24';
        l1.Phone = '00 0000 0000';
        
        //update l1;
        
       
        //CARGO TRACCK
        Lead ct = new Lead();
        ct.RecordTypeId = tiposRegistro.get('Cargo Tracck').getRecordTypeId();
        ct.FirstName = 'Lead';
        ct.LastName = 'Teste';
        ct.Company = 'Empresa Teste';
        ct.Status = 'Em aberto';
        ct.Canal_de_entrada__c = 'Ativo';
        ct.LeadSource = 'Internet';
        ct.Segmento__c = 'Bebidas';
        ct.Tipo_de_pessoa__c = 'J-Jurídica';
        ct.CNPJ__c = '51.040.153/0001-01';
        ct.VerificaDuplicidade__c = ct.CNPJ__c + 'Cargo Tracck';
		//ct.CPF__c = null;               
        insert ct;
        
        ct.Phone = '00 0000 0000';
        //update ct;
   
        Lead ct1 = new Lead();
        ct1.RecordTypeId = tiposRegistro.get('Cargo Tracck').getRecordTypeId();
        ct1.FirstName = 'Lead';
        ct1.LastName = 'Teste';
        ct1.Company = 'Empresa Teste';
        ct1.Status = 'Em aberto';
        ct1.Canal_de_entrada__c = 'Ativo';
        ct1.LeadSource = 'Internet';
        ct1.Segmento__c = 'Bebidas';
        ct1.Tipo_de_pessoa__c = 'F-Física';
        ct1.CPF__c = '527.816.515-40';
        ct1.VerificaDuplicidade__c = ct1.CPF__c + 'Cargo Tracck';
	    ct1.CNPJ__c = null;               
        //insert ct1;
        
        ct1.Phone = '00 0000 0000';
        //update ct1;

    }
    
}