force-app/main/default/objects/Lead/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CNPJ_CPF__c.field-meta.xml
<CustomField>
    <fullName>CNPJ_CPF__c</fullName>
    <label>CNPJ/CPF</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CUIT__c.field-meta.xml
<CustomField>
    <fullName>CUIT__c</fullName>
    <description>Chave Única de Identificação Tributária</description>
    <externalId>true</externalId>
    <inlineHelpText>Chave Única de Identificação Tributária. Formato: 00-00000000-0</inlineHelpText>
    <label>CUIT</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/Telefone_celular__c.field-meta.xml
<CustomField>
    <fullName>Telefone_celular__c</fullName>
    <label>Telefone celular</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Telefone_gestor_responsavel__c.field-meta.xml
<CustomField>
    <fullName>Telefone_gestor_responsavel__c</fullName>
    <label>Telefone do gestor responsável</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Tipo_de_pessoa__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_pessoa__c</fullName>
    <label>Tipo de pessoa</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>J-Jurídica - MEI</fullName>
            </value>
            <value>
                <fullName>J-Jurídica - ME</fullName>
            </value>
            <value>
                <fullName>F-Física</fullName>
            </value>
            <value>
                <fullName>J-Jurídica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/VerificaDuplicidade__c.field-meta.xml
<CustomField>
    <fullName>VerificaDuplicidade__c</fullName>
    <label>VerificaDuplicidade</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Argentina.recordType-meta.xml
<RecordType>
    <fullName>Argentina</fullName>
    <active>true</active>
    <businessProcess>CORP</businessProcess>
    <label>Argentina</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/CORP.recordType-meta.xml
<RecordType>
    <fullName>CORP</fullName>
    <active>true</active>
    <businessProcess>CORP</businessProcess>
    <label>CORP</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Freteiro.recordType-meta.xml
<RecordType>
    <fullName>Freteiro</fullName>
    <active>true</active>
    <businessProcess>Freteiro</businessProcess>
    <label>Freteiro</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Mercosul.recordType-meta.xml
<RecordType>
    <fullName>Mercosul</fullName>
    <active>true</active>
    <businessProcess>CORP</businessProcess>
    <label>Mercosul</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Michelin.recordType-meta.xml
<RecordType>
    <fullName>Michelin</fullName>
    <active>true</active>
    <businessProcess>Michelin</businessProcess>
    <description>Piloto Michelin</description>
    <label>Michelin</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Siggo.recordType-meta.xml
<RecordType>
    <fullName>Siggo</fullName>
    <active>true</active>
    <businessProcess>Siggo</businessProcess>
    <label>Siggo</label>
</RecordType>

force-app/main/default/objects/Servicos__c/Servicos__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Serviços</label>
</CustomObject>

force-app/main/default/objects/Servicos__c/fields/Busca_CEP_Lead__c.field-meta.xml
<CustomField>
    <fullName>Busca_CEP_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Realizar busca de CEP para o Lead</description>
    <inlineHelpText>Realizar busca de CEP para o Lead</inlineHelpText>
    <label>Busca CEP Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Triggers__c/Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuração para ativação/desativação da trigger</description>
    <label>Triggers</label>
</CustomObject>

force-app/main/default/objects/Triggers__c/fields/Duplicidade_lead__c.field-meta.xml
<CustomField>
    <fullName>Duplicidade_lead__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Define se verificação de duplicidade de Lead será realizada</description>
    <inlineHelpText>Define se verificação de duplicidade de Lead será realizada</inlineHelpText>
    <label>Duplicidade lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Service_Lead.cls
/*
	Classe de teste: Teste_Service_Lead
	Criado por: Mario Reis
	Data de criação: 02/10/2017
	Descrição: Classe com métodos para as funcionalidades da Trigger do Objeto Lead
	=====================================
	Refatoração adicionada no projeto Argentina
	Atualizado por: Mario Reis
	Data da alteração: 26/10/2017
	Descrição: Adicionado demais métodos utilizados nas triggers dos Leads

*/
public class Service_Lead {

	// Método que verifica a validação da CUIT
	public static void validacaoCUIT(List<Lead> listaLead) {

		System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - validacaoCUIT()] - Inicio...');
		System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - validacaoCUIT()] - listaLead: '+listaLead);

		if(listaLead != null && listaLead.size() > 0) {

			for(Lead lead : listaLead){

                System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - validacaoCUIT()] - lead.CUIT__c: '+lead.CUIT__c);

                if(lead.CUIT__c != null && lead.CUIT__c != '' && 
                   !Util_Validacoes.validarCUIT(lead.CUIT__c)){

					throw new customException(Label.MSG_ERRO_0008);
				}
			} // Fim for(Lead lead : listaLead)

		} else {

			throw new customException(Label.MSG_ERRO_0009);
        } // if(listaLead != null && listaLead.size() > 0)

	} // Fim validacaoCUIT


    // Método que verifica a validação do CPF
	public static void validacaoCPF(List<Lead> listaLead) {

		System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - validacaoCPF()] - Inicio...');
		System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - validacaoCPF()] - listaLead: '+listaLead);

		if(listaLead != null && listaLead.size() > 0) {

			for(Lead lead : listaLead){

                System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - validacaoCPF()] - lead.CPF__c: '+lead.CPF__c);

                if(lead.CPF__c != null && lead.CPF__c != ''){

					String cpfRetorno = Util_Validacoes.validarCPF(lead.CPF__c);

                    if(cpfRetorno != null) lead.CPF__c = cpfRetorno;
                    else throw new customException(Label.MSG_ERRO_0011);
				} // Fim if(lead.CPF__c != null && lead.CPF__c != '')

			} // Fim for(Lead lead : listaLead)

		} else {

			throw new customException(Label.MSG_ERRO_0012);
        } // if(listaLead != null && listaLead.size() > 0)

	} // Fim validacaoCPF


    // Método que verifica a validação do CPF
	public static void validacaoCNPJ(List<Lead> listaLead) {

		System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - validacaoCNPJ()] - Inicio...');
		System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - validacaoCNPJ()] - listaLead: '+listaLead);

		if(listaLead != null && listaLead.size() > 0) {

			for(Lead lead : listaLead){

                System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - validacaoCNPJ()] - lead.CNPJ__c: '+lead.CNPJ__c);

                if(lead.CNPJ__c != null && lead.CNPJ__c != ''){

					String cnpjRetorno = Util_Validacoes.validarCNPJ(lead.CNPJ__c);

                    System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - validacaoCNPJ()] - cnpjRetorno: '+cnpjRetorno);

					if(cnpjRetorno != null) lead.CNPJ__c = cnpjRetorno;
                    else throw new customException(Label.MSG_ERRO_0013);
				}
			} // Fim for(Lead lead : listaLead)

		} else {

			throw new customException(Label.MSG_ERRO_0014);
        } // if(listaLead != null && listaLead.size() > 0)

	} // Fim validacaoCNPJ


	// Método que formata Telefone
	public static void formataTelefone(List<Lead> listaLead) {

		System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - formataTelefone()] - Inicio...');
		System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - formataTelefone()] - listaLead: '+listaLead);

        try {

			if(listaLead != null && listaLead.size() > 0) {

                Util_Lead.carregarTipoRegistro();

				for(Lead lead : listaLead){

                	System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - formataTelefone()] - lead.CNPJ__c: '+lead.CNPJ__c);
                    System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - formataTelefone()] - lead.RecordType.Name: '+lead.RecordType.Name);

                    // Só faz a formatação se o Lead não for do mercosul
                    if(lead.RecordTypeId != Util_Lead.mercosul){

	                	if(lead.Phone != null && lead.Phone != ''){

							lead.Phone = Util_Organizacao.formatarTelefoneBrasil(lead.Phone);
						}

                    	if(lead.Telefone_celular__c != null && lead.Telefone_celular__c != ''){

							lead.Telefone_celular__c = Util_Organizacao.formatarTelefoneBrasil(lead.Telefone_celular__c);
						}

                    	if(lead.MobilePhone != null && lead.MobilePhone != ''){

							lead.MobilePhone = Util_Organizacao.formatarTelefoneBrasil(lead.MobilePhone);
						}

                        if(lead.Telefone_gestor_responsavel__c != null && lead.Telefone_gestor_responsavel__c != ''){

							lead.Telefone_gestor_responsavel__c = Util_Organizacao.formatarTelefoneBrasil(lead.Telefone_gestor_responsavel__c);
						}

                    } // Fim if(lead.RecordTypeId != Util_Lead.mercosul)

				} // Fim for(Lead lead : listaLead)

			} else {

				throw new customException(Label.MSG_ERRO_0015);
        	} // if(listaLead != null && listaLead.size() > 0)

		} catch(Exception e){

        	System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - formataTelefone()] - ERRO: '+e.getMessage());
            throw new customException(e.getMessage());
        } // Fim try/catch

	} // Fim formataTelefone


    // Método que preenche os campos do lead
	public static void preencheCamposLead(List<Lead> listaLead) {
        
        System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - preencheCamposLead()] - Inicio...');
		System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - preencheCamposLead()] - listaLead: '+listaLead);

        Util_Lead.carregarTipoRegistro();

		if(listaLead != null && listaLead.size() > 0) {

        	for(Lead lead : listaLead){

    			if(lead.RecordTypeId != null){

                    System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - preencheCamposLead()] - lead.RecordTypeId: ' + lead.RecordTypeId);
	    			System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - preencheCamposLead()] - lead: ' + lead);

			        if(lead.CNPJ__c != null && 
                       	String.valueOf(lead.RecordTypeId).subString(0,15) == Util_Lead.CORP){
	            		lead.VerificaDuplicidade__c = lead.CNPJ__c + 'CORP';
	        		}

                    else if(lead.RecordTypeId != null &&
                            String.valueOf(lead.RecordTypeId).subString(0,15) == Util_Lead.bluetec){

                        if(lead.CNPJ__c != null && lead.Tipo_de_pessoa__c == 'J-Jurídica'){
                            lead.VerificaDuplicidade__c = lead.CNPJ__c + 'Blue tec';
                            lead.CPF__c = null;
                        } else if(lead.CPF__c != null && lead.Tipo_de_pessoa__c == 'F-Física'){
                            lead.VerificaDuplicidade__c = lead.CPF__c + 'Blue tec';
                            lead.CNPJ__c = null;
                        }
                    }

                    else if(lead.CPF__c != null && lead.RecordTypeId != null &&
                            	String.valueOf(lead.RecordTypeId).subString(0,15) == Util_Lead.SIGGO){
                        lead.VerificaDuplicidade__c = lead.CPF__c + 'SIGGO';
                    }

                    else if(lead.CNPJ_CPF__c != null && lead.RecordTypeId != null &&
                            	String.valueOf(lead.RecordTypeId).subString(0,15) == Util_Lead.FRETEIRO){
                        lead.VerificaDuplicidade__c = lead.CNPJ_CPF__c + 'FRETEIRO';
                    }

                    else if(lead.CNPJ_CPF__c != null && lead.RecordTypeId != null &&
                            	String.valueOf(lead.RecordTypeId).subString(0,15) == Util_Lead.michelin){
                        lead.VerificaDuplicidade__c = lead.CNPJ_CPF__c + 'Michelin';
                    }

                    else if(lead.RecordTypeId != null && 
                            String.valueOf(lead.RecordTypeId).subString(0,15) == Util_Lead.cargoTracck){
                        if(lead.CNPJ__c != null && lead.Tipo_de_pessoa__c == 'J-Jurídica'){
                            lead.VerificaDuplicidade__c = lead.CNPJ__c + 'Cargo Tracck';
                            lead.CPF__c = null;
                        } else if(lead.CPF__c != null && lead.Tipo_de_pessoa__c == 'F-Física'){
                            lead.VerificaDuplicidade__c = lead.CPF__c + 'Cargo Tracck';
                            lead.CNPJ__c = null;
                        }
        
                    } // Fim ifs

    			} // Fim if(lead.RecordTypeId != null)

            } // Fim for(Lead lead : listaLead)

            System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - preencheCamposLead()] - listaLead: ' + listaLead);
            //if(listaLead != null && listaLead.size() > 0) update listaLead;

        } // FIm if(listaLead != null && listaLead.size() > 0)

	} // Fim método preencheCamposLead


	// Método que verifica a duplicidade do lead pelo tipo de registro
	public static void verificaDuplicidadeLead(List<lead> listaLead) {

		System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - verificaDuplicidadeLead()] - Inicio...');
		System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - verificaDuplicidadeLead()] - listaLead: '+listaLead);

        if(!Triggers__c.getOrgDefaults().Duplicidade_lead__c) return;

		if(listaLead != null && listaLead.size() > 0) {

            // Carrega as informações do tipo de registro do lead
            Util_Lead.carregarTipoRegistro();

			Set<Id> setIdLead = new Set<Id>();
			Set<String> setIdVerificaDuplicidade = new Set<String>();

			for(Lead lead : listaLead){

                if(Util_Lead.bluetec == lead.RecordTypeId) {
                    setIdLead.add(lead.Id);
                    if(lead.VerificaDuplicidade__c != null && lead.VerificaDuplicidade__c != '') 
                        setIdVerificaDuplicidade.add(lead.VerificaDuplicidade__c);
                }

                if(Util_Lead.CORP == lead.RecordTypeId) {
                    setIdLead.add(lead.Id);
                    if(lead.VerificaDuplicidade__c != null && lead.VerificaDuplicidade__c != '') 
                        setIdVerificaDuplicidade.add(lead.VerificaDuplicidade__c);
                }

                if(Util_Lead.michelin == lead.RecordTypeId) {
                    setIdLead.add(lead.Id);
                    if(lead.VerificaDuplicidade__c != null && lead.VerificaDuplicidade__c != '') 
                        setIdVerificaDuplicidade.add(lead.VerificaDuplicidade__c);
                }

                if(Util_Lead.SIGGO == lead.RecordTypeId) {
                    setIdLead.add(lead.Id);
                    if(lead.VerificaDuplicidade__c != null && lead.VerificaDuplicidade__c != '') 
                        setIdVerificaDuplicidade.add(lead.VerificaDuplicidade__c);
                }

                if(Util_Lead.cargoTracck == lead.RecordTypeId) {
                    setIdLead.add(lead.Id);
                    if(lead.VerificaDuplicidade__c != null && lead.VerificaDuplicidade__c != '') 
                        setIdVerificaDuplicidade.add(lead.VerificaDuplicidade__c);
                }

                if(Util_Lead.freteiro == lead.RecordTypeId) {
                    setIdLead.add(lead.Id);
                    if(lead.VerificaDuplicidade__c != null && lead.VerificaDuplicidade__c != '') 
                        setIdVerificaDuplicidade.add(lead.VerificaDuplicidade__c);
                }

			} // Fim for(Lead lead : listaLead)

			System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - verificaDuplicidadeConta()] - setIdLead: '+setIdLead);
            System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - verificaDuplicidadeConta()] - setIdVerificaDuplicidade: '+setIdVerificaDuplicidade);

			if(setIdLead != null && setIdLead.size() > 0 ){

				for(Lead lead : DAO_Lead.getLeadVerificaoDuplicidadePorId(setIdLead, setIdVerificaDuplicidade)){

                    String urlBase = String.valueof(URL.getSalesforceBaseUrl().toExternalForm());

                    String cpfCNPJ = '';
                    if(lead.CNPJ__c != null && lead.CNPJ__c != '') cpfCNPJ = lead.CNPJ__c;
                    if(lead.CNPJ_CPF__c != null && lead.CNPJ_CPF__c != '') cpfCNPJ = lead.CNPJ_CPF__c;
                    if(lead.CPF__c != null && lead.CPF__c != '') cpfCNPJ = lead.CPF__c;
					throw new customException(Label.MSG_ERRO_0020 + ' Nome do Lead: <a target=\'_blank\' href=\''+urlBase+'/'+lead.Id+'\'>'+lead.Name+'</a>');
				}
			}

		} else {

			throw new customException(Label.MSG_ERRO_0021);

        } // if(listaLead != null && listaLead.size() > 0)

	} // Fim verificaDuplicidadeLead


	// Método que faz a busca do CEP
	public static void buscaCEP(List<lead> listaLead) {

		System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - buscaCEP()] - Inicio...');
		System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - buscaCEP()] - listaLead: '+listaLead);

        if(!Servicos__c.getOrgDefaults().Busca_CEP_lead__c) return;

		if(listaLead != null && listaLead.size() > 0) {

			for(Lead lead : listaLead){

                System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - buscaCEP()] - lead : '+lead );
                System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - buscaCEP()] - System.IsBatch(): '+System.IsBatch());
                System.debug(LoggingLevel.ERROR, '__ [cls Service_Lead - buscaCEP()] - System.isFuture(): '+System.isFuture());

				if(System.IsBatch() == false && System.isFuture() == false) {
 					if(lead.PostalCode != null ){
    					Util_Organizacao.buscaCEP(lead.Id, lead.PostalCode, 'lead', null);
    				}
				}

			} // Fim for(Lead lead : listaLead)

        } // Fim if(listaLead != null && listaLead.size() > 0) 

	} // Fim buscaCEP


}