force-app/main/default/objects/Historico_OS__c/Historico_OS__c.object-meta.xml
<CustomObject>
    <label>Histórico da OS</label>
    <nameField>
        <displayFormat>HO-{000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Históricos da OS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/Parametrizacao_faixa_aging__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para a parametrização das Faixas de Aging.</description>
    <label>Parametrização Faixa de Aging</label>
    <nameField>
        <displayFormat>FA-{0000}</displayFormat>
        <label>Nome de Parametrização Faixa de Aging</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parametrizações Faixas de Aging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/fields/Aging_ate__c.field-meta.xml
<CustomField>
    <fullName>Aging_ate__c</fullName>
    <label>Aging até</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/fields/Aging_de__c.field-meta.xml
<CustomField>
    <fullName>Aging_de__c</fullName>
    <description>Preencher esse campo.</description>
    <label>Aging de</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/fields/Contatos_dias_distintos__c.field-meta.xml
<CustomField>
    <fullName>Contatos_dias_distintos__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Contatos em dias distintos dentro da faixa.</description>
    <label>Contatos dias distintos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/fields/Nome_faixa__c.field-meta.xml
<CustomField>
    <fullName>Nome_faixa__c</fullName>
    <label>Nome da faixa</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/fields/Quantidade_contatos__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_contatos__c</fullName>
    <label>Quantidade de contatos</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/fields/Tipo_Macro_OS__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Macro_OS__c</fullName>
    <label>Tipo Macro da Os</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_macro_Os</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parametrizacao_faixa_aging__c/fields/Tipo_Micro_OS__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Micro_OS__c</fullName>
    <label>Tipo Micro da OS</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_micro_OS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Status_OS__c/Status_OS__c.object-meta.xml
<CustomObject>
    <description>Status das ordens de serviço</description>
    <label>Status da OS</label>
    <nameField>
        <label>Nome do Status da OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Status da OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Tipo_macro_Os.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Assistência</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação não cobrar</fullName>
    </customValue>
    <customValue>
        <fullName>Retirada</fullName>
    </customValue>
    <customValue>
        <fullName>Sem motivo cadastrado</fullName>
    </customValue>
    <description>Tipos macros da OS.</description>
    <masterLabel>Tipo Macro da Os</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tipo_micro_OS.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sem item cadastrado</fullName>
    </customValue>
    <customValue>
        <fullName>Assistência</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação – Downgrade</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação – Upgrade</fullName>
    </customValue>
    <customValue>
        <fullName>Instalação de Equipamento</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação – TRC</fullName>
    </customValue>
    <customValue>
        <fullName>Reinstalação não cobrar</fullName>
    </customValue>
    <customValue>
        <fullName>Retirada</fullName>
    </customValue>
    <customValue>
        <fullName>Retirada - TRC</fullName>
    </customValue>
    <masterLabel>Tipo Micro da OS</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Teste_OS_Atualizar_Informacoes.cls
/*
    Classe de testes para as classes: 
		- OS_Atualizar_Informacoes - Cobertura 100%
		- OS_Atualizar_Informacoes_Batch - Cobertura 94%

	Criado por: Mario Reis
    Data: 05/12/2017
*/
@isTest
public class Teste_OS_Atualizar_Informacoes {

    
    // Método para teste da classe
    static testmethod void teste() {

        Status_OS__c statusPendente = Teste_Util_Status_OS.criarStatusAutorizadoPendente();

        Parametrizacao_faixa_aging__c parametrizacao = new Parametrizacao_faixa_aging__c();
        parametrizacao.Nome_faixa__c = 'D0 a D7';
        parametrizacao.Aging_de__c = 0;
        parametrizacao.Aging_ate__c =7;
        parametrizacao.Contatos_dias_distintos__c = true;
        parametrizacao.Quantidade_contatos__c = 1;
        parametrizacao.Tipo_Macro_OS__c = 'Sem motivo cadastrado';
		parametrizacao.Tipo_Micro_OS__c = 'Sem item cadastrado';
        insert parametrizacao;

		Test.startTest();

        WorkOrder OS = Teste_Util_OS.criarOSPadrao(statusPendente.Id);
        Historico_OS__c ho = Teste_Util_Historico_OS.criarHistoricoEfetivo(OS.Id);

        OS_Atualizar_Informacoes_Agendada sh1 = new OS_Atualizar_Informacoes_Agendada();      
        sh1.scheduleIt();
        // String sch = '0 57 13 * * ?';
        // System.schedule('Test check', sch, sh1);


        Test.stopTest();

    } // Fim teste
	
    
    // Método para teste da classe
    static testmethod void teste2() {

        Status_OS__c statusFinalizado = Teste_Util_Status_OS.criarStatusConcluidoFinalizado();

		Parametrizacao_faixa_aging__c parametrizacao = new Parametrizacao_faixa_aging__c();
        parametrizacao.Nome_faixa__c = 'D0 a D7';
        parametrizacao.Aging_de__c = 0;
        parametrizacao.Aging_ate__c =7;
        parametrizacao.Contatos_dias_distintos__c = true;
        parametrizacao.Quantidade_contatos__c = 1;
        parametrizacao.Tipo_Macro_OS__c = 'Sem motivo cadastrado';
		parametrizacao.Tipo_Micro_OS__c = 'Sem item cadastrado';
        insert parametrizacao;

        Test.startTest();

        WorkOrder OS = Teste_Util_OS.criarOSPadrao(statusFinalizado.Id);
        Historico_OS__c ho = Teste_Util_Historico_OS.criarHistoricoEfetivo(OS.Id);

        OS_Atualizar_Informacoes_Agendada sh1 = new OS_Atualizar_Informacoes_Agendada();      
        sh1.scheduleIt();
        // String sch = '0 57 13 * * ?';
        // System.schedule('Test check', sch, sh1);


        Test.stopTest();

    } // Fim teste

    
    // Método para teste da classe
    static testmethod void teste3() {

        Status_OS__c statusFinalizado = Teste_Util_Status_OS.criarStatusConcluidoFinalizado();
        statusFinalizado.Name = 'Ordem de serviço cancelada';
        update statusFinalizado;

		Parametrizacao_faixa_aging__c parametrizacao = new Parametrizacao_faixa_aging__c();
        parametrizacao.Nome_faixa__c = 'D0 a D7';
        parametrizacao.Aging_de__c = 0;
        parametrizacao.Aging_ate__c =7;
        parametrizacao.Contatos_dias_distintos__c = true;
        parametrizacao.Quantidade_contatos__c = 1;
        parametrizacao.Tipo_Macro_OS__c = 'Sem motivo cadastrado';
		parametrizacao.Tipo_Micro_OS__c = 'Sem item cadastrado';
        insert parametrizacao;

        Test.startTest();

        WorkOrder OS = Teste_Util_OS.criarOSPadrao(statusFinalizado.Id);
        Historico_OS__c ho = Teste_Util_Historico_OS.criarHistoricoEfetivo(OS.Id);

        OS_Atualizar_Informacoes_Agendada sh1 = new OS_Atualizar_Informacoes_Agendada();      
        // sh1.scheduleIt();
        String sch = '0 57 13 * * ?';
        System.schedule('Test check', sch, sh1);


        Test.stopTest();

    } // Fim teste

    
    // Método para teste da classe
    static testmethod void teste4() {

        Status_OS__c statusFinalizado = Teste_Util_Status_OS.criarStatusConcluidoFinalizado();
        statusFinalizado.Name = 'Ordem de serviço cancelada';
        update statusFinalizado;

		Parametrizacao_faixa_aging__c parametrizacao = new Parametrizacao_faixa_aging__c();
        parametrizacao.Nome_faixa__c = 'D0 a D7';
        parametrizacao.Aging_de__c = 0;
        parametrizacao.Aging_ate__c =7;
        parametrizacao.Contatos_dias_distintos__c = true;
        parametrizacao.Quantidade_contatos__c = 1;
        parametrizacao.Tipo_Macro_OS__c = 'Sem motivo cadastrado';
		parametrizacao.Tipo_Micro_OS__c = 'Sem item cadastrado';
        insert parametrizacao;

        Test.startTest();

        WorkOrder OS = Teste_Util_OS.criarOSPadrao(statusFinalizado.Id);
        Historico_OS__c ho = Teste_Util_Historico_OS.criarHistoricoSemAcao(OS.Id);

        OS_Atualizar_Informacoes_Agendada sh1 = new OS_Atualizar_Informacoes_Agendada();      
        // sh1.scheduleIt();
        String sch = '0 59 12 * * ?';
        System.schedule('Test check', sch, sh1);


        Test.stopTest();

    } // Fim teste

}