force-app/main/default/objects/Historico_OS__c/Historico_OS__c.object-meta.xml
<CustomObject>
    <label>Histórico da OS</label>
    <nameField>
        <displayFormat>HO-{000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Históricos da OS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Historico_OS__c/fields/Observacao__c.field-meta.xml
<CustomField>
    <fullName>Observacao__c</fullName>
    <label>Observação</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Status_OS__c/Status_OS__c.object-meta.xml
<CustomObject>
    <description>Status das ordens de serviço</description>
    <label>Status da OS</label>
    <nameField>
        <label>Nome do Status da OS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Status da OS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Triggers__c/Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuração para ativação/desativação da trigger</description>
    <label>Triggers</label>
</CustomObject>

force-app/main/default/objects/Triggers__c/fields/Trigger_historico_OS__c.field-meta.xml
<CustomField>
    <fullName>Trigger_historico_OS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trigger historico OS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Teste_Trigger_Historico_OS.cls
/*
    Classe de testes para a Trigger "Trigger_Historico_OS"
    Criado por: Juliano Szlachta
    Data: 26/06/2018
*/
@isTest
public class Teste_Trigger_Historico_OS {

    public static Triggers__c confTriggers;

	static testmethod void testeTriggerHistoricoOS()  {

    	Test.startTest();

		Triggers__c confTriggers = Teste_Util_Configuracao.criarConfiguracaoTriggers();

        confTriggers.Trigger_historico_os__c = true;
    	update confTriggers;

        Status_OS__c statusPendente = Teste_Util_Status_OS.criarStatusAutorizadoPendente();
        WorkOrder OS = Teste_Util_OS.criarOSPadrao(statusPendente.Id);
        Historico_OS__c ho = Teste_Util_Historico_OS.criarHistoricoEfetivo(OS.Id);
        ho.Observacao__c = 'Teste';
        update ho;

		Test.stopTest();

	}	
	
}